// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Kotlin back end). Do not edit by hand.

package cloud.charging.v2g.iso20.common

import cloud.charging.v2g.exi.BitReader
import cloud.charging.v2g.exi.BitWriter

data class AdditionalServiceListType(
    val additionalService: List<AdditionalServiceType>
)

internal fun encodeAdditionalServiceListType(w: BitWriter, msg: AdditionalServiceListType) {
    val list = msg.additionalService
    require(list.size in 1..5) { "list size out of schema range" }
    for (i in list.indices) {
        w.writeBits(0u, if (i == 0) 1 else 2)   // SE(item)
        encodeAdditionalServiceType(w, list[i])
    }
    w.writeBits(1u, 2)   // list terminator / element EE
}

internal fun decodeAdditionalServiceListType(r: BitReader): AdditionalServiceListType {
    val list = ArrayList<AdditionalServiceType>()
    r.readBits(1)   // SE(item) first
    list.add(decodeAdditionalServiceType(r))
    while (true) {
        val ec = r.readBits(2)
        if (ec == 1u) break   // element EE
        require(ec == 0u && list.size < 5) { "invalid repeating-element event code" }
        list.add(decodeAdditionalServiceType(r))
    }
    return AdditionalServiceListType(list)
}
