// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Kotlin back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cloud.charging.v2g.iso20.common

import cloud.charging.v2g.exi.BitReader
import cloud.charging.v2g.exi.BitWriter

data class ChargingScheduleType(
    val powerSchedule: PowerScheduleType,
    val absolutePriceSchedule: AbsolutePriceScheduleType?,
    val priceLevelSchedule: PriceLevelScheduleType?
)

internal fun encodeChargingScheduleType(w: BitWriter, msg: ChargingScheduleType) {
    w.writeBits(0u, 1)   // SE
    encodePowerScheduleType(w, msg.powerSchedule)
    var st24 = 0
    var done24 = false
    while (!done24) {
        when (st24) {
            0 -> {
                if (msg.absolutePriceSchedule != null) {
                    w.writeBits(0u, 2)   // AbsolutePriceSchedule
                    encodeAbsolutePriceScheduleType(w, msg.absolutePriceSchedule!!)
                    st24 = 1
                } else if (msg.priceLevelSchedule != null) {
                    w.writeBits(1u, 2)   // PriceLevelSchedule
                    encodePriceLevelScheduleType(w, msg.priceLevelSchedule!!)
                    st24 = 1
                } else {
                    w.writeBits(2u, 2)   // element EE
                    done24 = true
                }
            }
            1 -> {
                w.writeBits(0u, 1)   // element EE
                done24 = true
            }
        }
    }
}

internal fun decodeChargingScheduleType(r: BitReader): ChargingScheduleType {
    r.readBits(1)   // SE
    val _powerSchedule = decodePowerScheduleType(r)
    var _absolutePriceSchedule: AbsolutePriceScheduleType? = null
    var _priceLevelSchedule: PriceLevelScheduleType? = null
    var st25 = 0
    var done25 = false
    while (!done25) {
        when (st25) {
            0 -> {
                when (r.readBits(2)) {
                    0u -> {   // AbsolutePriceSchedule
                        _absolutePriceSchedule = decodeAbsolutePriceScheduleType(r)
                        st25 = 1
                    }
                    1u -> {   // PriceLevelSchedule
                        _priceLevelSchedule = decodePriceLevelScheduleType(r)
                        st25 = 1
                    }
                    2u -> done25 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            1 -> {
                when (r.readBits(1)) {
                    0u -> done25 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
        }
    }
    return ChargingScheduleType(_powerSchedule, _absolutePriceSchedule, _priceLevelSchedule)
}
