// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Kotlin back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cloud.charging.v2g.iso20.common

import cloud.charging.v2g.exi.JsonArray
import cloud.charging.v2g.exi.JsonLdException
import cloud.charging.v2g.exi.JsonObject
import cloud.charging.v2g.exi.JsonPrimitives
import cloud.charging.v2g.exi.JsonValue

internal fun toJsonChargingScheduleType(value: ChargingScheduleType): JsonObject {

    val json = JsonObject()

    json["@type"] = JsonValue.of("ChargingScheduleType")

    json["powerSchedule"] = CommonMessagesCodecJson.toJson(value.powerSchedule)
    value.absolutePriceSchedule?.let { json["absolutePriceSchedule"] = CommonMessagesCodecJson.toJson(it) }

    value.priceLevelSchedule?.let { json["priceLevelSchedule"] = CommonMessagesCodecJson.toJson(it) }

    return json
}

internal fun parseJsonChargingScheduleType(json: JsonObject): ChargingScheduleType =
    ChargingScheduleType(
        JsonPrimitives.cast<PowerScheduleType>(CommonMessagesCodecJson.parseJson(JsonPrimitives.required(json, "powerSchedule", "ChargingScheduleType"), "ChargingScheduleType.powerSchedule"), "powerSchedule", "ChargingScheduleType"),
        JsonPrimitives.optional(json, "absolutePriceSchedule")?.let { JsonPrimitives.cast<AbsolutePriceScheduleType>(CommonMessagesCodecJson.parseJson(it, "ChargingScheduleType.absolutePriceSchedule"), "absolutePriceSchedule", "ChargingScheduleType") },
        JsonPrimitives.optional(json, "priceLevelSchedule")?.let { JsonPrimitives.cast<PriceLevelScheduleType>(CommonMessagesCodecJson.parseJson(it, "ChargingScheduleType.priceLevelSchedule"), "priceLevelSchedule", "ChargingScheduleType") }
    )

