// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Kotlin back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cloud.charging.v2g.iso20.common

import cloud.charging.v2g.exi.BitReader
import cloud.charging.v2g.exi.BitWriter

class ServiceSelectionReqType(
    override val header: MessageHeaderType,
    val selectedEnergyTransferService: SelectedServiceType,
    val selectedVASList: SelectedServiceListType?
) : V2GRequestType(header)

internal fun encodeServiceSelectionReqType(w: BitWriter, msg: ServiceSelectionReqType) {
    w.writeBits(0u, 1)   // SE
    encodeMessageHeaderType(w, msg.header)
    w.writeBits(0u, 1)   // SE
    encodeSelectedServiceType(w, msg.selectedEnergyTransferService)
    var st4 = 0
    var done4 = false
    while (!done4) {
        when (st4) {
            0 -> {
                if (msg.selectedVASList != null) {
                    w.writeBits(0u, 2)   // SelectedVASList
                    encodeSelectedServiceListType(w, msg.selectedVASList!!)
                    st4 = 1
                } else {
                    w.writeBits(1u, 2)   // element EE
                    done4 = true
                }
            }
            1 -> {
                w.writeBits(0u, 1)   // element EE
                done4 = true
            }
        }
    }
}

internal fun decodeServiceSelectionReqType(r: BitReader): ServiceSelectionReqType {
    r.readBits(1)   // SE
    val _header = decodeMessageHeaderType(r)
    r.readBits(1)   // SE
    val _selectedEnergyTransferService = decodeSelectedServiceType(r)
    var _selectedVASList: SelectedServiceListType? = null
    var st5 = 0
    var done5 = false
    while (!done5) {
        when (st5) {
            0 -> {
                when (r.readBits(2)) {
                    0u -> {
                        _selectedVASList = decodeSelectedServiceListType(r)
                        st5 = 1
                    }
                    1u -> done5 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            1 -> {
                when (r.readBits(1)) {
                    0u -> done5 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
        }
    }
    return ServiceSelectionReqType(_header, _selectedEnergyTransferService, _selectedVASList)
}
