// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Kotlin back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cloud.charging.v2g.iso20.common

import cloud.charging.v2g.exi.BitReader
import cloud.charging.v2g.exi.BitWriter
import cloud.charging.v2g.exi.ExiPrimitives

class SessionSetupRes(
    override val header: MessageHeaderType,
    override val responseCode: ResponseCode,
    val eVSEID: String
) : V2GResponseType(header, responseCode)

internal fun encodeSessionSetupRes(w: BitWriter, msg: SessionSetupRes) {
    w.writeBits(0u, 1)   // SE
    encodeMessageHeaderType(w, msg.header)
    w.writeBits(0u, 1)   // SE
    w.writeBits(0u, 1)   // value-start
    w.writeBits(msg.responseCode.ordinal.toUInt(), 6)
    w.writeBits(0u, 1)   // child EE
    w.writeBits(0u, 1)   // SE
    w.writeBits(0u, 1)   // value-start
    ExiPrimitives.writeStringValue(w, msg.eVSEID)
    w.writeBits(0u, 1)   // child EE
    w.writeBits(0u, 1)   // element EE
}

internal fun decodeSessionSetupRes(r: BitReader): SessionSetupRes {
    r.readBits(1)   // SE
    val _header = decodeMessageHeaderType(r)
    r.readBits(1)   // SE
    r.readBits(1)   // value-start
    val _responseCode = ResponseCode.entries[r.readBits(6).toInt()]
    r.readBits(1)   // child EE
    r.readBits(1)   // SE
    r.readBits(1)   // value-start
    val _eVSEID = ExiPrimitives.readStringValue(r, "EVSEID")
    r.readBits(1)   // child EE
    r.readBits(1)   // element EE
    return SessionSetupRes(_header, _responseCode, _eVSEID)
}
