// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Kotlin back end). Do not edit by hand.

package cloud.charging.v2g.iso20.common

import cloud.charging.v2g.exi.JsonArray
import cloud.charging.v2g.exi.JsonLdException
import cloud.charging.v2g.exi.JsonObject
import cloud.charging.v2g.exi.JsonPrimitives
import cloud.charging.v2g.exi.JsonValue

internal fun toJsonSessionSetupResType(value: SessionSetupResType): JsonObject {

    val json = JsonObject()

    json["@type"] = JsonValue.of("SessionSetupResType")

    json["header"] = CommonMessagesCodecJson.toJson(value.header)
    json["responseCode"] = JsonValue.of(value.responseCode.name)
    json["evseid"] = JsonValue.of(value.eVSEID)
    return json
}

internal fun parseJsonSessionSetupResType(json: JsonObject): SessionSetupResType =
    SessionSetupResType(
        JsonPrimitives.cast<MessageHeaderType>(CommonMessagesCodecJson.parseJson(JsonPrimitives.required(json, "header", "SessionSetupResType"), "SessionSetupResType.header"), "header", "SessionSetupResType"),
        JsonPrimitives.enumeration(JsonPrimitives.required(json, "responseCode", "SessionSetupResType"), "responseCode", "SessionSetupResType", ResponseCode.values()),
        JsonPrimitives.stringValue(JsonPrimitives.required(json, "evseid", "SessionSetupResType"), "evseid", "SessionSetupResType")
    )

