// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Kotlin back end). Do not edit by hand.

package cloud.charging.v2g.iso20.common

import cloud.charging.v2g.exi.BitReader
import cloud.charging.v2g.exi.BitWriter
import cloud.charging.v2g.exi.ExiPrimitives

data class SupportedProvidersListType(
    val providerID: List<String>
)

internal fun encodeSupportedProvidersListType(w: BitWriter, msg: SupportedProvidersListType) {
    val list = msg.providerID
    require(list.size in 1..128) { "list size out of schema range" }
    for (i in list.indices) {
        w.writeBits(0u, if (i == 0) 1 else 2)   // SE(item)
        w.writeBits(0u, 1)   // value-start
        ExiPrimitives.writeStringValue(w, list[i])
        w.writeBits(0u, 1)   // child EE
    }
    w.writeBits(1u, 2)   // list terminator / element EE
}

internal fun decodeSupportedProvidersListType(r: BitReader): SupportedProvidersListType {
    val list = ArrayList<String>()
    r.readBits(1)   // SE(item) first
    r.readBits(1)   // value-start
    val listFirst = ExiPrimitives.readStringValue(r, "ProviderID")
    r.readBits(1)   // child EE
    list.add(listFirst)
    while (true) {
        val ec = r.readBits(2)
        if (ec == 1u) break   // element EE
        require(ec == 0u && list.size < 128) { "invalid repeating-element event code" }
        r.readBits(1)   // value-start
        val listNext = ExiPrimitives.readStringValue(r, "ProviderID")
        r.readBits(1)   // child EE
        list.add(listNext)
    }
    return SupportedProvidersListType(list)
}
