// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Kotlin back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cloud.charging.v2g.iso20.common

import cloud.charging.v2g.exi.JsonArray
import cloud.charging.v2g.exi.JsonLdException
import cloud.charging.v2g.exi.JsonObject
import cloud.charging.v2g.exi.JsonPrimitives
import cloud.charging.v2g.exi.JsonValue

internal fun toJsonVehicleCheckInReqType(value: VehicleCheckInReqType): JsonObject {

    val json = JsonObject()

    json["@type"] = JsonValue.of("VehicleCheckInReqType")

    json["header"] = CommonMessagesCodecJson.toJson(value.header)
    json["evCheckInStatus"] = JsonValue.of(value.eVCheckInStatus.name)
    json["parkingMethod"] = JsonValue.of(value.parkingMethod.name)
    value.vehicleFrame?.let { json["vehicleFrame"] = JsonValue.of(it) }

    value.deviceOffset?.let { json["deviceOffset"] = JsonValue.of(it) }

    value.vehicleTravel?.let { json["vehicleTravel"] = JsonValue.of(it) }

    return json
}

internal fun parseJsonVehicleCheckInReqType(json: JsonObject): VehicleCheckInReqType =
    VehicleCheckInReqType(
        JsonPrimitives.cast<MessageHeaderType>(CommonMessagesCodecJson.parseJson(JsonPrimitives.required(json, "header", "VehicleCheckInReqType"), "VehicleCheckInReqType.header"), "header", "VehicleCheckInReqType"),
        JsonPrimitives.enumeration(JsonPrimitives.required(json, "evCheckInStatus", "VehicleCheckInReqType"), "evCheckInStatus", "VehicleCheckInReqType", EvCheckInStatus.values()),
        JsonPrimitives.enumeration(JsonPrimitives.required(json, "parkingMethod", "VehicleCheckInReqType"), "parkingMethod", "VehicleCheckInReqType", ParkingMethod.values()),
        JsonPrimitives.optional(json, "vehicleFrame")?.let { JsonPrimitives.int16(it, "vehicleFrame", "VehicleCheckInReqType") },
        JsonPrimitives.optional(json, "deviceOffset")?.let { JsonPrimitives.int16(it, "deviceOffset", "VehicleCheckInReqType") },
        JsonPrimitives.optional(json, "vehicleTravel")?.let { JsonPrimitives.int16(it, "vehicleTravel", "VehicleCheckInReqType") }
    )

