// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Kotlin back end). Do not edit by hand.

package cloud.charging.v2g.iso20.acdp

import cloud.charging.v2g.exi.BitReader
import cloud.charging.v2g.exi.BitWriter

class ACDP_SystemStatusRes(
    override val header: MessageHeaderType,
    override val responseCode: ResponseCode,
    val eVSEMechanicalChargingDeviceStatus: MechanicalChargingDeviceStatus,
    val eVSEReadyToCharge: Boolean,
    val eVSEIsolationStatus: IsolationStatus,
    val eVSEDisabled: Boolean,
    val eVSEUtilityInterruptEvent: Boolean,
    val eVSEEmergencyShutdown: Boolean,
    val eVSEMalfunction: Boolean,
    val eVInChargePosition: Boolean,
    val eVAssociationStatus: Boolean
) : V2GResponseType(header, responseCode)

internal fun encodeACDP_SystemStatusRes(w: BitWriter, msg: ACDP_SystemStatusRes) {
    w.writeBits(0u, 1)   // SE
    encodeMessageHeaderType(w, msg.header)
    w.writeBits(0u, 1)   // SE
    w.writeBits(0u, 1)   // value-start
    w.writeBits(msg.responseCode.ordinal.toUInt(), 6)
    w.writeBits(0u, 1)   // child EE
    w.writeBits(0u, 1)   // SE
    w.writeBits(0u, 1)   // value-start
    w.writeBits(msg.eVSEMechanicalChargingDeviceStatus.ordinal.toUInt(), 2)
    w.writeBits(0u, 1)   // child EE
    w.writeBits(0u, 1)   // SE
    w.writeBits(0u, 1)   // value-start
    w.writeBits(if (msg.eVSEReadyToCharge) 1u else 0u, 1)
    w.writeBits(0u, 1)   // child EE
    w.writeBits(0u, 1)   // SE
    w.writeBits(0u, 1)   // value-start
    w.writeBits(msg.eVSEIsolationStatus.ordinal.toUInt(), 2)
    w.writeBits(0u, 1)   // child EE
    w.writeBits(0u, 1)   // SE
    w.writeBits(0u, 1)   // value-start
    w.writeBits(if (msg.eVSEDisabled) 1u else 0u, 1)
    w.writeBits(0u, 1)   // child EE
    w.writeBits(0u, 1)   // SE
    w.writeBits(0u, 1)   // value-start
    w.writeBits(if (msg.eVSEUtilityInterruptEvent) 1u else 0u, 1)
    w.writeBits(0u, 1)   // child EE
    w.writeBits(0u, 1)   // SE
    w.writeBits(0u, 1)   // value-start
    w.writeBits(if (msg.eVSEEmergencyShutdown) 1u else 0u, 1)
    w.writeBits(0u, 1)   // child EE
    w.writeBits(0u, 1)   // SE
    w.writeBits(0u, 1)   // value-start
    w.writeBits(if (msg.eVSEMalfunction) 1u else 0u, 1)
    w.writeBits(0u, 1)   // child EE
    w.writeBits(0u, 1)   // SE
    w.writeBits(0u, 1)   // value-start
    w.writeBits(if (msg.eVInChargePosition) 1u else 0u, 1)
    w.writeBits(0u, 1)   // child EE
    w.writeBits(0u, 1)   // SE
    w.writeBits(0u, 1)   // value-start
    w.writeBits(if (msg.eVAssociationStatus) 1u else 0u, 1)
    w.writeBits(0u, 1)   // child EE
    w.writeBits(0u, 1)   // element EE
}

internal fun decodeACDP_SystemStatusRes(r: BitReader): ACDP_SystemStatusRes {
    r.readBits(1)   // SE
    val _header = decodeMessageHeaderType(r)
    r.readBits(1)   // SE
    r.readBits(1)   // value-start
    val _responseCode = ResponseCode.entries[r.readBits(6).toInt()]
    r.readBits(1)   // child EE
    r.readBits(1)   // SE
    r.readBits(1)   // value-start
    val _eVSEMechanicalChargingDeviceStatus = MechanicalChargingDeviceStatus.entries[r.readBits(2).toInt()]
    r.readBits(1)   // child EE
    r.readBits(1)   // SE
    r.readBits(1)   // value-start
    val _eVSEReadyToCharge = r.readBits(1).toInt() != 0
    r.readBits(1)   // child EE
    r.readBits(1)   // SE
    r.readBits(1)   // value-start
    val _eVSEIsolationStatus = IsolationStatus.entries[r.readBits(2).toInt()]
    r.readBits(1)   // child EE
    r.readBits(1)   // SE
    r.readBits(1)   // value-start
    val _eVSEDisabled = r.readBits(1).toInt() != 0
    r.readBits(1)   // child EE
    r.readBits(1)   // SE
    r.readBits(1)   // value-start
    val _eVSEUtilityInterruptEvent = r.readBits(1).toInt() != 0
    r.readBits(1)   // child EE
    r.readBits(1)   // SE
    r.readBits(1)   // value-start
    val _eVSEEmergencyShutdown = r.readBits(1).toInt() != 0
    r.readBits(1)   // child EE
    r.readBits(1)   // SE
    r.readBits(1)   // value-start
    val _eVSEMalfunction = r.readBits(1).toInt() != 0
    r.readBits(1)   // child EE
    r.readBits(1)   // SE
    r.readBits(1)   // value-start
    val _eVInChargePosition = r.readBits(1).toInt() != 0
    r.readBits(1)   // child EE
    r.readBits(1)   // SE
    r.readBits(1)   // value-start
    val _eVAssociationStatus = r.readBits(1).toInt() != 0
    r.readBits(1)   // child EE
    r.readBits(1)   // element EE
    return ACDP_SystemStatusRes(_header, _responseCode, _eVSEMechanicalChargingDeviceStatus, _eVSEReadyToCharge, _eVSEIsolationStatus, _eVSEDisabled, _eVSEUtilityInterruptEvent, _eVSEEmergencyShutdown, _eVSEMalfunction, _eVInChargePosition, _eVAssociationStatus)
}
