// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Kotlin back end). Do not edit by hand.

package cloud.charging.v2g.iso20.acdp

import cloud.charging.v2g.exi.JsonArray
import cloud.charging.v2g.exi.JsonLdException
import cloud.charging.v2g.exi.JsonObject
import cloud.charging.v2g.exi.JsonPrimitives
import cloud.charging.v2g.exi.JsonValue

object ACDPCodecJson {

    /** The vocabulary these messages are written in: the XSD target namespace. */
    const val CONTEXT = "urn:iso:std:iso:15118:-20:ACDP"

    /** The JSON-LD form of any generated message or type. */
    fun toJson(value: Any): JsonObject =
        when (value) {
            is ACDP_ConnectReq -> toJsonACDP_ConnectReq(value)
            is ACDP_ConnectReqType -> toJsonACDP_ConnectReqType(value)
            is ACDP_ConnectRes -> toJsonACDP_ConnectRes(value)
            is ACDP_ConnectResType -> toJsonACDP_ConnectResType(value)
            is ACDP_DisconnectReq -> toJsonACDP_DisconnectReq(value)
            is ACDP_DisconnectRes -> toJsonACDP_DisconnectRes(value)
            is ACDP_SystemStatusReq -> toJsonACDP_SystemStatusReq(value)
            is ACDP_SystemStatusReqType -> toJsonACDP_SystemStatusReqType(value)
            is ACDP_SystemStatusRes -> toJsonACDP_SystemStatusRes(value)
            is ACDP_SystemStatusResType -> toJsonACDP_SystemStatusResType(value)
            is ACDP_VehiclePositioningReq -> toJsonACDP_VehiclePositioningReq(value)
            is ACDP_VehiclePositioningReqType -> toJsonACDP_VehiclePositioningReqType(value)
            is ACDP_VehiclePositioningRes -> toJsonACDP_VehiclePositioningRes(value)
            is ACDP_VehiclePositioningResType -> toJsonACDP_VehiclePositioningResType(value)
            is CanonicalizationMethodType -> toJsonCanonicalizationMethodType(value)
            is DetailedCostType -> toJsonDetailedCostType(value)
            is DetailedTaxType -> toJsonDetailedTaxType(value)
            is DigestMethodType -> toJsonDigestMethodType(value)
            is DisplayParametersType -> toJsonDisplayParametersType(value)
            is EVSEStatusType -> toJsonEVSEStatusType(value)
            is EVTechnicalStatusType -> toJsonEVTechnicalStatusType(value)
            is ListOfRootCertificateIDsType -> toJsonListOfRootCertificateIDsType(value)
            is MessageHeaderType -> toJsonMessageHeaderType(value)
            is MeterInfoType -> toJsonMeterInfoType(value)
            is RationalNumberType -> toJsonRationalNumberType(value)
            is ReceiptType -> toJsonReceiptType(value)
            is ReferenceType -> toJsonReferenceType(value)
            is SignatureMethodType -> toJsonSignatureMethodType(value)
            is SignatureType -> toJsonSignatureType(value)
            is SignatureValueType -> toJsonSignatureValueType(value)
            is SignedInfoType -> toJsonSignedInfoType(value)
            is TransformType -> toJsonTransformType(value)
            is TransformsType -> toJsonTransformsType(value)
            is X509IssuerSerialType -> toJsonX509IssuerSerialType(value)
            is KeyInfo -> toJsonKeyInfo(value)
            is Object -> toJsonObject(value)

            else -> throw JsonLdException(
                "${value::class.simpleName} is not a type of this message set.")
        }

    /** Reads any generated message or type back, by its `@type`. */
    fun parseJson(node: JsonValue?, what: String = "the document"): Any {

        val json = JsonPrimitives.obj(node, what)

        return when (val type = JsonPrimitives.typeTag(json, what)) {
            "ACDP_VehiclePositioningReqType" -> parseJsonACDP_VehiclePositioningReqType(json)
            "ACDP_VehiclePositioningResType" -> parseJsonACDP_VehiclePositioningResType(json)
            "ACDP_ConnectReqType" -> parseJsonACDP_ConnectReqType(json)
            "ACDP_ConnectResType" -> parseJsonACDP_ConnectResType(json)
            "ACDP_SystemStatusReqType" -> parseJsonACDP_SystemStatusReqType(json)
            "ACDP_SystemStatusResType" -> parseJsonACDP_SystemStatusResType(json)
            "EVTechnicalStatusType" -> parseJsonEVTechnicalStatusType(json)
            "MessageHeaderType" -> parseJsonMessageHeaderType(json)
            "DisplayParametersType" -> parseJsonDisplayParametersType(json)
            "EVSEStatusType" -> parseJsonEVSEStatusType(json)
            "RationalNumberType" -> parseJsonRationalNumberType(json)
            "MeterInfoType" -> parseJsonMeterInfoType(json)
            "DetailedCostType" -> parseJsonDetailedCostType(json)
            "DetailedTaxType" -> parseJsonDetailedTaxType(json)
            "ReceiptType" -> parseJsonReceiptType(json)
            "ListOfRootCertificateIDsType" -> parseJsonListOfRootCertificateIDsType(json)
            "SignatureType" -> parseJsonSignatureType(json)
            "SignatureValueType" -> parseJsonSignatureValueType(json)
            "SignedInfoType" -> parseJsonSignedInfoType(json)
            "CanonicalizationMethodType" -> parseJsonCanonicalizationMethodType(json)
            "SignatureMethodType" -> parseJsonSignatureMethodType(json)
            "ReferenceType" -> parseJsonReferenceType(json)
            "TransformsType" -> parseJsonTransformsType(json)
            "TransformType" -> parseJsonTransformType(json)
            "DigestMethodType" -> parseJsonDigestMethodType(json)
            "X509IssuerSerialType" -> parseJsonX509IssuerSerialType(json)
            "ACDP_VehiclePositioningReq" -> parseJsonACDP_VehiclePositioningReq(json)
            "ACDP_VehiclePositioningRes" -> parseJsonACDP_VehiclePositioningRes(json)
            "ACDP_ConnectReq" -> parseJsonACDP_ConnectReq(json)
            "ACDP_ConnectRes" -> parseJsonACDP_ConnectRes(json)
            "ACDP_DisconnectReq" -> parseJsonACDP_DisconnectReq(json)
            "ACDP_DisconnectRes" -> parseJsonACDP_DisconnectRes(json)
            "ACDP_SystemStatusReq" -> parseJsonACDP_SystemStatusReq(json)
            "ACDP_SystemStatusRes" -> parseJsonACDP_SystemStatusRes(json)
            "KeyInfo" -> parseJsonKeyInfo(json)
            "Object" -> parseJsonObject(json)

            else -> throw JsonLdException(
                "$what has @type '$type', which is not a type of this message set.")
        }
    }
}
