// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Kotlin back end). Do not edit by hand.

package cloud.charging.v2g.iso20.acdp

import cloud.charging.v2g.exi.BitReader
import cloud.charging.v2g.exi.BitWriter
import cloud.charging.v2g.exi.ExiPrimitives

data class CanonicalizationMethodType(
    val algorithm: String,
    val aNY: ByteArray?
)

internal fun encodeCanonicalizationMethodType(w: BitWriter, msg: CanonicalizationMethodType) {
    w.writeBits(0u, 1)   // AT(required attribute)
    ExiPrimitives.writeStringValue(w, msg.algorithm)
    var st18 = 0
    var done18 = false
    while (!done18) {
        when (st18) {
            0 -> {
                if (msg.aNY != null) {
                    w.writeBits(2u, 2)   // ANY
                    w.writeBits(0u, 1)   // value-start
                    ExiPrimitives.writeBinary(w, msg.aNY!!)
                    w.writeBits(0u, 1)   // child EE
                    st18 = 1
                } else {
                    w.writeBits(1u, 2)   // element EE
                    done18 = true
                }
            }
            1 -> {
                w.writeBits(0u, 1)   // element EE
                done18 = true
            }
        }
    }
}

internal fun decodeCanonicalizationMethodType(r: BitReader): CanonicalizationMethodType {
    r.readBits(1)   // AT(required attribute)
    val _algorithm = ExiPrimitives.readStringValue(r, "Algorithm")
    var _aNY: ByteArray? = null
    var st19 = 0
    var done19 = false
    while (!done19) {
        when (st19) {
            0 -> {
                when (r.readBits(2)) {
                    1u -> done19 = true   // element EE
                    2u -> {   // ANY
                        r.readBits(1)   // value-start
                        _aNY = ExiPrimitives.readBinary(r)
                        r.readBits(1)   // child EE
                        st19 = 1
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            1 -> {
                when (r.readBits(1)) {
                    0u -> done19 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
        }
    }
    return CanonicalizationMethodType(_algorithm, _aNY)
}
