// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Kotlin back end). Do not edit by hand.

package cloud.charging.v2g.iso20.acdersae

import cloud.charging.v2g.exi.BitReader
import cloud.charging.v2g.exi.BitWriter

data class AC_CPDReqEnergyTransferMode(
    val eVMaximumChargePower: RationalNumberType,
    val eVMaximumChargePower_L2: RationalNumberType?,
    val eVMaximumChargePower_L3: RationalNumberType?,
    val eVMinimumChargePower: RationalNumberType,
    val eVMinimumChargePower_L2: RationalNumberType?,
    val eVMinimumChargePower_L3: RationalNumberType?
)

internal fun encodeAC_CPDReqEnergyTransferMode(w: BitWriter, msg: AC_CPDReqEnergyTransferMode) {
    w.writeBits(0u, 1)   // SE
    encodeRationalNumberType(w, msg.eVMaximumChargePower)
    var st282 = 0
    var done282 = false
    while (!done282) {
        when (st282) {
            0 -> {
                if (msg.eVMaximumChargePower_L2 != null) {
                    w.writeBits(0u, 2)   // EVMaximumChargePower_L2
                    encodeRationalNumberType(w, msg.eVMaximumChargePower_L2!!)
                    st282 = 1
                } else if (msg.eVMaximumChargePower_L3 != null) {
                    w.writeBits(1u, 2)   // EVMaximumChargePower_L3
                    encodeRationalNumberType(w, msg.eVMaximumChargePower_L3!!)
                    st282 = 2
                } else {
                    w.writeBits(2u, 2)   // SE(EVMinimumChargePower)
                    encodeRationalNumberType(w, msg.eVMinimumChargePower)
                    done282 = true
                }
            }
            1 -> {
                if (msg.eVMaximumChargePower_L3 != null) {
                    w.writeBits(0u, 2)   // EVMaximumChargePower_L3
                    encodeRationalNumberType(w, msg.eVMaximumChargePower_L3!!)
                    st282 = 2
                } else {
                    w.writeBits(1u, 2)   // SE(EVMinimumChargePower)
                    encodeRationalNumberType(w, msg.eVMinimumChargePower)
                    done282 = true
                }
            }
            2 -> {
                w.writeBits(0u, 1)   // SE(EVMinimumChargePower)
                encodeRationalNumberType(w, msg.eVMinimumChargePower)
                done282 = true
            }
        }
    }
    var st283 = 0
    var done283 = false
    while (!done283) {
        when (st283) {
            0 -> {
                if (msg.eVMinimumChargePower_L2 != null) {
                    w.writeBits(0u, 2)   // EVMinimumChargePower_L2
                    encodeRationalNumberType(w, msg.eVMinimumChargePower_L2!!)
                    st283 = 1
                } else if (msg.eVMinimumChargePower_L3 != null) {
                    w.writeBits(1u, 2)   // EVMinimumChargePower_L3
                    encodeRationalNumberType(w, msg.eVMinimumChargePower_L3!!)
                    st283 = 2
                } else {
                    w.writeBits(2u, 2)   // element EE
                    done283 = true
                }
            }
            1 -> {
                if (msg.eVMinimumChargePower_L3 != null) {
                    w.writeBits(0u, 2)   // EVMinimumChargePower_L3
                    encodeRationalNumberType(w, msg.eVMinimumChargePower_L3!!)
                    st283 = 2
                } else {
                    w.writeBits(1u, 2)   // element EE
                    done283 = true
                }
            }
            2 -> {
                w.writeBits(0u, 1)   // element EE
                done283 = true
            }
        }
    }
}

internal fun decodeAC_CPDReqEnergyTransferMode(r: BitReader): AC_CPDReqEnergyTransferMode {
    r.readBits(1)   // SE
    val _eVMaximumChargePower = decodeRationalNumberType(r)
    var _eVMaximumChargePower_L2: RationalNumberType? = null
    var _eVMaximumChargePower_L3: RationalNumberType? = null
    var _eVMinimumChargePower: RationalNumberType? = null
    var st284 = 0
    var done284 = false
    while (!done284) {
        when (st284) {
            0 -> {
                when (r.readBits(2)) {
                    0u -> {
                        _eVMaximumChargePower_L2 = decodeRationalNumberType(r)
                        st284 = 1
                    }
                    1u -> {
                        _eVMaximumChargePower_L3 = decodeRationalNumberType(r)
                        st284 = 2
                    }
                    2u -> {   // SE(EVMinimumChargePower)
                        _eVMinimumChargePower = decodeRationalNumberType(r)
                        done284 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            1 -> {
                when (r.readBits(2)) {
                    0u -> {
                        _eVMaximumChargePower_L3 = decodeRationalNumberType(r)
                        st284 = 2
                    }
                    1u -> {   // SE(EVMinimumChargePower)
                        _eVMinimumChargePower = decodeRationalNumberType(r)
                        done284 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            2 -> {
                when (r.readBits(1)) {
                    0u -> {   // SE(EVMinimumChargePower)
                        _eVMinimumChargePower = decodeRationalNumberType(r)
                        done284 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
        }
    }
    var _eVMinimumChargePower_L2: RationalNumberType? = null
    var _eVMinimumChargePower_L3: RationalNumberType? = null
    var st285 = 0
    var done285 = false
    while (!done285) {
        when (st285) {
            0 -> {
                when (r.readBits(2)) {
                    0u -> {
                        _eVMinimumChargePower_L2 = decodeRationalNumberType(r)
                        st285 = 1
                    }
                    1u -> {
                        _eVMinimumChargePower_L3 = decodeRationalNumberType(r)
                        st285 = 2
                    }
                    2u -> done285 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            1 -> {
                when (r.readBits(2)) {
                    0u -> {
                        _eVMinimumChargePower_L3 = decodeRationalNumberType(r)
                        st285 = 2
                    }
                    1u -> done285 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            2 -> {
                when (r.readBits(1)) {
                    0u -> done285 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
        }
    }
    return AC_CPDReqEnergyTransferMode(_eVMaximumChargePower, _eVMaximumChargePower_L2, _eVMaximumChargePower_L3, _eVMinimumChargePower!!, _eVMinimumChargePower_L2, _eVMinimumChargePower_L3)
}
