// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Kotlin back end). Do not edit by hand.

package cloud.charging.v2g.iso20.acdersae

import cloud.charging.v2g.exi.JsonArray
import cloud.charging.v2g.exi.JsonLdException
import cloud.charging.v2g.exi.JsonObject
import cloud.charging.v2g.exi.JsonPrimitives
import cloud.charging.v2g.exi.JsonValue

internal fun toJsonAC_ChargeLoopResType(value: AC_ChargeLoopResType): JsonObject {

    val json = JsonObject()

    json["@type"] = JsonValue.of("AC_ChargeLoopResType")

    json["header"] = AcDerSaeCodecJson.toJson(value.header)
    json["responseCode"] = JsonValue.of(value.responseCode.name)
    value.eVSEStatus?.let { json["evseStatus"] = AcDerSaeCodecJson.toJson(it) }

    value.meterInfo?.let { json["meterInfo"] = AcDerSaeCodecJson.toJson(it) }

    value.receipt?.let { json["receipt"] = AcDerSaeCodecJson.toJson(it) }

    value.eVSETargetFrequency?.let { json["evseTargetFrequency"] = AcDerSaeCodecJson.toJson(it) }

    json["clResControlMode"] = AcDerSaeCodecJson.toJson(value.cLResControlMode)
    return json
}

internal fun parseJsonAC_ChargeLoopResType(json: JsonObject): AC_ChargeLoopResType =
    AC_ChargeLoopResType(
        JsonPrimitives.cast<MessageHeaderType>(AcDerSaeCodecJson.parseJson(JsonPrimitives.required(json, "header", "AC_ChargeLoopResType"), "AC_ChargeLoopResType.header"), "header", "AC_ChargeLoopResType"),
        JsonPrimitives.enumeration(JsonPrimitives.required(json, "responseCode", "AC_ChargeLoopResType"), "responseCode", "AC_ChargeLoopResType", ResponseCode.values()),
        JsonPrimitives.optional(json, "evseStatus")?.let { JsonPrimitives.cast<EVSEStatusType>(AcDerSaeCodecJson.parseJson(it, "AC_ChargeLoopResType.evseStatus"), "evseStatus", "AC_ChargeLoopResType") },
        JsonPrimitives.optional(json, "meterInfo")?.let { JsonPrimitives.cast<MeterInfoType>(AcDerSaeCodecJson.parseJson(it, "AC_ChargeLoopResType.meterInfo"), "meterInfo", "AC_ChargeLoopResType") },
        JsonPrimitives.optional(json, "receipt")?.let { JsonPrimitives.cast<ReceiptType>(AcDerSaeCodecJson.parseJson(it, "AC_ChargeLoopResType.receipt"), "receipt", "AC_ChargeLoopResType") },
        JsonPrimitives.optional(json, "evseTargetFrequency")?.let { JsonPrimitives.cast<RationalNumberType>(AcDerSaeCodecJson.parseJson(it, "AC_ChargeLoopResType.evseTargetFrequency"), "evseTargetFrequency", "AC_ChargeLoopResType") },
        JsonPrimitives.cast<CLResControlModeType>(AcDerSaeCodecJson.parseJson(JsonPrimitives.required(json, "clResControlMode", "AC_ChargeLoopResType"), "AC_ChargeLoopResType.clResControlMode"), "clResControlMode", "AC_ChargeLoopResType")
    )

