// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Kotlin back end). Do not edit by hand.

package cloud.charging.v2g.iso20.acdersae

import cloud.charging.v2g.exi.JsonArray
import cloud.charging.v2g.exi.JsonLdException
import cloud.charging.v2g.exi.JsonObject
import cloud.charging.v2g.exi.JsonPrimitives
import cloud.charging.v2g.exi.JsonValue

internal fun toJsonEVReactivePowerType(value: EVReactivePowerType): JsonObject {

    val json = JsonObject()

    json["@type"] = JsonValue.of("EVReactivePowerType")

    json["evMaximumVarAbsorptionDuringCharging"] = AcDerSaeCodecJson.toJson(value.eVMaximumVarAbsorptionDuringCharging)
    value.eVMaximumVarAbsorptionDuringCharging_L2?.let { json["evMaximumVarAbsorptionDuringCharging_L2"] = AcDerSaeCodecJson.toJson(it) }

    value.eVMaximumVarAbsorptionDuringCharging_L3?.let { json["evMaximumVarAbsorptionDuringCharging_L3"] = AcDerSaeCodecJson.toJson(it) }

    value.eVMinimumVarAbsorptionDuringCharging?.let { json["evMinimumVarAbsorptionDuringCharging"] = AcDerSaeCodecJson.toJson(it) }

    value.eVMinimumVarAbsorptionDuringCharging_L2?.let { json["evMinimumVarAbsorptionDuringCharging_L2"] = AcDerSaeCodecJson.toJson(it) }

    value.eVMinimumVarAbsorptionDuringCharging_L3?.let { json["evMinimumVarAbsorptionDuringCharging_L3"] = AcDerSaeCodecJson.toJson(it) }

    json["evMaximumVarInjectionDuringCharging"] = AcDerSaeCodecJson.toJson(value.eVMaximumVarInjectionDuringCharging)
    value.eVMaximumVarInjectionDuringCharging_L2?.let { json["evMaximumVarInjectionDuringCharging_L2"] = AcDerSaeCodecJson.toJson(it) }

    value.eVMaximumVarInjectionDuringCharging_L3?.let { json["evMaximumVarInjectionDuringCharging_L3"] = AcDerSaeCodecJson.toJson(it) }

    value.eVMinimumVarInjectionDuringCharging?.let { json["evMinimumVarInjectionDuringCharging"] = AcDerSaeCodecJson.toJson(it) }

    value.eVMinimumVarInjectionDuringCharging_L2?.let { json["evMinimumVarInjectionDuringCharging_L2"] = AcDerSaeCodecJson.toJson(it) }

    value.eVMinimumVarInjectionDuringCharging_L3?.let { json["evMinimumVarInjectionDuringCharging_L3"] = AcDerSaeCodecJson.toJson(it) }

    json["evMaximumVarAbsorptionDuringDischarging"] = AcDerSaeCodecJson.toJson(value.eVMaximumVarAbsorptionDuringDischarging)
    value.eVMaximumVarAbsorptionDuringDischarging_L2?.let { json["evMaximumVarAbsorptionDuringDischarging_L2"] = AcDerSaeCodecJson.toJson(it) }

    value.eVMaximumVarAbsorptionDuringDischarging_L3?.let { json["evMaximumVarAbsorptionDuringDischarging_L3"] = AcDerSaeCodecJson.toJson(it) }

    value.eVMinimumVarAbsorptionDuringDischarging?.let { json["evMinimumVarAbsorptionDuringDischarging"] = AcDerSaeCodecJson.toJson(it) }

    value.eVMinimumVarAbsorptionDuringDischarging_L2?.let { json["evMinimumVarAbsorptionDuringDischarging_L2"] = AcDerSaeCodecJson.toJson(it) }

    value.eVMinimumVarAbsorptionDuringDischarging_L3?.let { json["evMinimumVarAbsorptionDuringDischarging_L3"] = AcDerSaeCodecJson.toJson(it) }

    json["evMaximumVarInjectionDuringDischarging"] = AcDerSaeCodecJson.toJson(value.eVMaximumVarInjectionDuringDischarging)
    value.eVMaximumVarInjectionDuringDischarging_L2?.let { json["evMaximumVarInjectionDuringDischarging_L2"] = AcDerSaeCodecJson.toJson(it) }

    value.eVMaximumVarInjectionDuringDischarging_L3?.let { json["evMaximumVarInjectionDuringDischarging_L3"] = AcDerSaeCodecJson.toJson(it) }

    value.eVMinimumVarInjectionDuringDischarging?.let { json["evMinimumVarInjectionDuringDischarging"] = AcDerSaeCodecJson.toJson(it) }

    value.eVMinimumVarInjectionDuringDischarging_L2?.let { json["evMinimumVarInjectionDuringDischarging_L2"] = AcDerSaeCodecJson.toJson(it) }

    value.eVMinimumVarInjectionDuringDischarging_L3?.let { json["evMinimumVarInjectionDuringDischarging_L3"] = AcDerSaeCodecJson.toJson(it) }

    return json
}

internal fun parseJsonEVReactivePowerType(json: JsonObject): EVReactivePowerType =
    EVReactivePowerType(
        JsonPrimitives.cast<RationalNumberType>(AcDerSaeCodecJson.parseJson(JsonPrimitives.required(json, "evMaximumVarAbsorptionDuringCharging", "EVReactivePowerType"), "EVReactivePowerType.evMaximumVarAbsorptionDuringCharging"), "evMaximumVarAbsorptionDuringCharging", "EVReactivePowerType"),
        JsonPrimitives.optional(json, "evMaximumVarAbsorptionDuringCharging_L2")?.let { JsonPrimitives.cast<RationalNumberType>(AcDerSaeCodecJson.parseJson(it, "EVReactivePowerType.evMaximumVarAbsorptionDuringCharging_L2"), "evMaximumVarAbsorptionDuringCharging_L2", "EVReactivePowerType") },
        JsonPrimitives.optional(json, "evMaximumVarAbsorptionDuringCharging_L3")?.let { JsonPrimitives.cast<RationalNumberType>(AcDerSaeCodecJson.parseJson(it, "EVReactivePowerType.evMaximumVarAbsorptionDuringCharging_L3"), "evMaximumVarAbsorptionDuringCharging_L3", "EVReactivePowerType") },
        JsonPrimitives.optional(json, "evMinimumVarAbsorptionDuringCharging")?.let { JsonPrimitives.cast<RationalNumberType>(AcDerSaeCodecJson.parseJson(it, "EVReactivePowerType.evMinimumVarAbsorptionDuringCharging"), "evMinimumVarAbsorptionDuringCharging", "EVReactivePowerType") },
        JsonPrimitives.optional(json, "evMinimumVarAbsorptionDuringCharging_L2")?.let { JsonPrimitives.cast<RationalNumberType>(AcDerSaeCodecJson.parseJson(it, "EVReactivePowerType.evMinimumVarAbsorptionDuringCharging_L2"), "evMinimumVarAbsorptionDuringCharging_L2", "EVReactivePowerType") },
        JsonPrimitives.optional(json, "evMinimumVarAbsorptionDuringCharging_L3")?.let { JsonPrimitives.cast<RationalNumberType>(AcDerSaeCodecJson.parseJson(it, "EVReactivePowerType.evMinimumVarAbsorptionDuringCharging_L3"), "evMinimumVarAbsorptionDuringCharging_L3", "EVReactivePowerType") },
        JsonPrimitives.cast<RationalNumberType>(AcDerSaeCodecJson.parseJson(JsonPrimitives.required(json, "evMaximumVarInjectionDuringCharging", "EVReactivePowerType"), "EVReactivePowerType.evMaximumVarInjectionDuringCharging"), "evMaximumVarInjectionDuringCharging", "EVReactivePowerType"),
        JsonPrimitives.optional(json, "evMaximumVarInjectionDuringCharging_L2")?.let { JsonPrimitives.cast<RationalNumberType>(AcDerSaeCodecJson.parseJson(it, "EVReactivePowerType.evMaximumVarInjectionDuringCharging_L2"), "evMaximumVarInjectionDuringCharging_L2", "EVReactivePowerType") },
        JsonPrimitives.optional(json, "evMaximumVarInjectionDuringCharging_L3")?.let { JsonPrimitives.cast<RationalNumberType>(AcDerSaeCodecJson.parseJson(it, "EVReactivePowerType.evMaximumVarInjectionDuringCharging_L3"), "evMaximumVarInjectionDuringCharging_L3", "EVReactivePowerType") },
        JsonPrimitives.optional(json, "evMinimumVarInjectionDuringCharging")?.let { JsonPrimitives.cast<RationalNumberType>(AcDerSaeCodecJson.parseJson(it, "EVReactivePowerType.evMinimumVarInjectionDuringCharging"), "evMinimumVarInjectionDuringCharging", "EVReactivePowerType") },
        JsonPrimitives.optional(json, "evMinimumVarInjectionDuringCharging_L2")?.let { JsonPrimitives.cast<RationalNumberType>(AcDerSaeCodecJson.parseJson(it, "EVReactivePowerType.evMinimumVarInjectionDuringCharging_L2"), "evMinimumVarInjectionDuringCharging_L2", "EVReactivePowerType") },
        JsonPrimitives.optional(json, "evMinimumVarInjectionDuringCharging_L3")?.let { JsonPrimitives.cast<RationalNumberType>(AcDerSaeCodecJson.parseJson(it, "EVReactivePowerType.evMinimumVarInjectionDuringCharging_L3"), "evMinimumVarInjectionDuringCharging_L3", "EVReactivePowerType") },
        JsonPrimitives.cast<RationalNumberType>(AcDerSaeCodecJson.parseJson(JsonPrimitives.required(json, "evMaximumVarAbsorptionDuringDischarging", "EVReactivePowerType"), "EVReactivePowerType.evMaximumVarAbsorptionDuringDischarging"), "evMaximumVarAbsorptionDuringDischarging", "EVReactivePowerType"),
        JsonPrimitives.optional(json, "evMaximumVarAbsorptionDuringDischarging_L2")?.let { JsonPrimitives.cast<RationalNumberType>(AcDerSaeCodecJson.parseJson(it, "EVReactivePowerType.evMaximumVarAbsorptionDuringDischarging_L2"), "evMaximumVarAbsorptionDuringDischarging_L2", "EVReactivePowerType") },
        JsonPrimitives.optional(json, "evMaximumVarAbsorptionDuringDischarging_L3")?.let { JsonPrimitives.cast<RationalNumberType>(AcDerSaeCodecJson.parseJson(it, "EVReactivePowerType.evMaximumVarAbsorptionDuringDischarging_L3"), "evMaximumVarAbsorptionDuringDischarging_L3", "EVReactivePowerType") },
        JsonPrimitives.optional(json, "evMinimumVarAbsorptionDuringDischarging")?.let { JsonPrimitives.cast<RationalNumberType>(AcDerSaeCodecJson.parseJson(it, "EVReactivePowerType.evMinimumVarAbsorptionDuringDischarging"), "evMinimumVarAbsorptionDuringDischarging", "EVReactivePowerType") },
        JsonPrimitives.optional(json, "evMinimumVarAbsorptionDuringDischarging_L2")?.let { JsonPrimitives.cast<RationalNumberType>(AcDerSaeCodecJson.parseJson(it, "EVReactivePowerType.evMinimumVarAbsorptionDuringDischarging_L2"), "evMinimumVarAbsorptionDuringDischarging_L2", "EVReactivePowerType") },
        JsonPrimitives.optional(json, "evMinimumVarAbsorptionDuringDischarging_L3")?.let { JsonPrimitives.cast<RationalNumberType>(AcDerSaeCodecJson.parseJson(it, "EVReactivePowerType.evMinimumVarAbsorptionDuringDischarging_L3"), "evMinimumVarAbsorptionDuringDischarging_L3", "EVReactivePowerType") },
        JsonPrimitives.cast<RationalNumberType>(AcDerSaeCodecJson.parseJson(JsonPrimitives.required(json, "evMaximumVarInjectionDuringDischarging", "EVReactivePowerType"), "EVReactivePowerType.evMaximumVarInjectionDuringDischarging"), "evMaximumVarInjectionDuringDischarging", "EVReactivePowerType"),
        JsonPrimitives.optional(json, "evMaximumVarInjectionDuringDischarging_L2")?.let { JsonPrimitives.cast<RationalNumberType>(AcDerSaeCodecJson.parseJson(it, "EVReactivePowerType.evMaximumVarInjectionDuringDischarging_L2"), "evMaximumVarInjectionDuringDischarging_L2", "EVReactivePowerType") },
        JsonPrimitives.optional(json, "evMaximumVarInjectionDuringDischarging_L3")?.let { JsonPrimitives.cast<RationalNumberType>(AcDerSaeCodecJson.parseJson(it, "EVReactivePowerType.evMaximumVarInjectionDuringDischarging_L3"), "evMaximumVarInjectionDuringDischarging_L3", "EVReactivePowerType") },
        JsonPrimitives.optional(json, "evMinimumVarInjectionDuringDischarging")?.let { JsonPrimitives.cast<RationalNumberType>(AcDerSaeCodecJson.parseJson(it, "EVReactivePowerType.evMinimumVarInjectionDuringDischarging"), "evMinimumVarInjectionDuringDischarging", "EVReactivePowerType") },
        JsonPrimitives.optional(json, "evMinimumVarInjectionDuringDischarging_L2")?.let { JsonPrimitives.cast<RationalNumberType>(AcDerSaeCodecJson.parseJson(it, "EVReactivePowerType.evMinimumVarInjectionDuringDischarging_L2"), "evMinimumVarInjectionDuringDischarging_L2", "EVReactivePowerType") },
        JsonPrimitives.optional(json, "evMinimumVarInjectionDuringDischarging_L3")?.let { JsonPrimitives.cast<RationalNumberType>(AcDerSaeCodecJson.parseJson(it, "EVReactivePowerType.evMinimumVarInjectionDuringDischarging_L3"), "evMinimumVarInjectionDuringDischarging_L3", "EVReactivePowerType") }
    )

