// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Kotlin back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cloud.charging.v2g.iso20.acdersae

import cloud.charging.v2g.exi.JsonArray
import cloud.charging.v2g.exi.JsonLdException
import cloud.charging.v2g.exi.JsonObject
import cloud.charging.v2g.exi.JsonPrimitives
import cloud.charging.v2g.exi.JsonValue

internal fun toJsonVoltWattType(value: VoltWattType): JsonObject {

    val json = JsonObject()

    json["@type"] = JsonValue.of("VoltWattType")

    json["enable"] = JsonValue.of(value.enable)
    value.priority?.let { json["priority"] = JsonValue.of(it) }

    json["xUnit"] = JsonValue.of(value.xUnit.name)
    json["yUnit"] = JsonValue.of(value.yUnit.name)
    json["curveDataPoints"] = AcDerSaeCodecJson.toJson(value.curveDataPoints)
    value.curveDataPoints_L2?.let { json["curveDataPoints_L2"] = AcDerSaeCodecJson.toJson(it) }

    value.curveDataPoints_L3?.let { json["curveDataPoints_L3"] = AcDerSaeCodecJson.toJson(it) }

    json["openLoopResponseTime"] = AcDerSaeCodecJson.toJson(value.openLoopResponseTime)
    value.timeConstantPT1?.let { json["timeConstantPT1"] = JsonValue.of(it) }

    return json
}

internal fun parseJsonVoltWattType(json: JsonObject): VoltWattType =
    VoltWattType(
        JsonPrimitives.bool(JsonPrimitives.required(json, "enable", "VoltWattType"), "enable", "VoltWattType"),
        JsonPrimitives.optional(json, "priority")?.let { JsonPrimitives.uint16(it, "priority", "VoltWattType") },
        JsonPrimitives.enumeration(JsonPrimitives.required(json, "xUnit", "VoltWattType"), "xUnit", "VoltWattType", DerUnit.values()),
        JsonPrimitives.enumeration(JsonPrimitives.required(json, "yUnit", "VoltWattType"), "yUnit", "VoltWattType", DerUnit.values()),
        JsonPrimitives.cast<CurveDataPointsListType>(AcDerSaeCodecJson.parseJson(JsonPrimitives.required(json, "curveDataPoints", "VoltWattType"), "VoltWattType.curveDataPoints"), "curveDataPoints", "VoltWattType"),
        JsonPrimitives.optional(json, "curveDataPoints_L2")?.let { JsonPrimitives.cast<CurveDataPointsListType>(AcDerSaeCodecJson.parseJson(it, "VoltWattType.curveDataPoints_L2"), "curveDataPoints_L2", "VoltWattType") },
        JsonPrimitives.optional(json, "curveDataPoints_L3")?.let { JsonPrimitives.cast<CurveDataPointsListType>(AcDerSaeCodecJson.parseJson(it, "VoltWattType.curveDataPoints_L3"), "curveDataPoints_L3", "VoltWattType") },
        JsonPrimitives.cast<RationalNumberType>(AcDerSaeCodecJson.parseJson(JsonPrimitives.required(json, "openLoopResponseTime", "VoltWattType"), "VoltWattType.openLoopResponseTime"), "openLoopResponseTime", "VoltWattType"),
        JsonPrimitives.optional(json, "timeConstantPT1")?.let { JsonPrimitives.uint32(it, "timeConstantPT1", "VoltWattType") }
    )

