// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Kotlin back end). Do not edit by hand.

package cloud.charging.v2g.iso20.acdersae

import cloud.charging.v2g.exi.BitReader
import cloud.charging.v2g.exi.BitWriter
import cloud.charging.v2g.exi.ExiPrimitives

data class WattVarType(
    val enable: Boolean,
    val priority: UShort?,
    val xUnit: DerUnit,
    val yUnit: DerUnit,
    val curveDataPoints: CurveDataPointsListType,
    val curveDataPoints_L2: CurveDataPointsListType?,
    val curveDataPoints_L3: CurveDataPointsListType?,
    val openLoopResponseTime: RationalNumberType?,
    val timeConstantPT1: UInt?
)

internal fun encodeWattVarType(w: BitWriter, msg: WattVarType) {
    w.writeBits(0u, 1)   // SE
    w.writeBits(0u, 1)   // value-start
    w.writeBits(if (msg.enable) 1u else 0u, 1)
    w.writeBits(0u, 1)   // child EE
    var st94 = 0
    var done94 = false
    while (!done94) {
        when (st94) {
            0 -> {
                if (msg.priority != null) {
                    w.writeBits(0u, 2)   // Priority
                    w.writeBits(0u, 1)   // value-start
                    ExiPrimitives.writeUnsignedInteger(w, msg.priority!!.toULong())
                    w.writeBits(0u, 1)   // child EE
                    st94 = 1
                } else {
                    w.writeBits(1u, 2)   // SE(XUnit)
                    w.writeBits(0u, 1)   // value-start
                    w.writeBits(msg.xUnit.ordinal.toUInt(), 4)
                    w.writeBits(0u, 1)   // child EE
                    done94 = true
                }
            }
            1 -> {
                w.writeBits(0u, 1)   // SE(XUnit)
                w.writeBits(0u, 1)   // value-start
                w.writeBits(msg.xUnit.ordinal.toUInt(), 4)
                w.writeBits(0u, 1)   // child EE
                done94 = true
            }
        }
    }
    w.writeBits(0u, 1)   // SE
    w.writeBits(0u, 1)   // value-start
    w.writeBits(msg.yUnit.ordinal.toUInt(), 4)
    w.writeBits(0u, 1)   // child EE
    w.writeBits(0u, 1)   // SE
    encodeCurveDataPointsListType(w, msg.curveDataPoints)
    var st95 = 0
    var done95 = false
    while (!done95) {
        when (st95) {
            0 -> {
                if (msg.curveDataPoints_L2 != null) {
                    w.writeBits(0u, 3)   // CurveDataPoints_L2
                    encodeCurveDataPointsListType(w, msg.curveDataPoints_L2!!)
                    st95 = 1
                } else if (msg.curveDataPoints_L3 != null) {
                    w.writeBits(1u, 3)   // CurveDataPoints_L3
                    encodeCurveDataPointsListType(w, msg.curveDataPoints_L3!!)
                    st95 = 2
                } else if (msg.openLoopResponseTime != null) {
                    w.writeBits(2u, 3)   // OpenLoopResponseTime
                    encodeRationalNumberType(w, msg.openLoopResponseTime!!)
                    st95 = 3
                } else if (msg.timeConstantPT1 != null) {
                    w.writeBits(3u, 3)   // TimeConstantPT1
                    w.writeBits(0u, 1)   // value-start
                    ExiPrimitives.writeUnsignedInteger(w, msg.timeConstantPT1!!.toULong())
                    w.writeBits(0u, 1)   // child EE
                    st95 = 4
                } else {
                    w.writeBits(4u, 3)   // element EE
                    done95 = true
                }
            }
            1 -> {
                if (msg.curveDataPoints_L3 != null) {
                    w.writeBits(0u, 3)   // CurveDataPoints_L3
                    encodeCurveDataPointsListType(w, msg.curveDataPoints_L3!!)
                    st95 = 2
                } else if (msg.openLoopResponseTime != null) {
                    w.writeBits(1u, 3)   // OpenLoopResponseTime
                    encodeRationalNumberType(w, msg.openLoopResponseTime!!)
                    st95 = 3
                } else if (msg.timeConstantPT1 != null) {
                    w.writeBits(2u, 3)   // TimeConstantPT1
                    w.writeBits(0u, 1)   // value-start
                    ExiPrimitives.writeUnsignedInteger(w, msg.timeConstantPT1!!.toULong())
                    w.writeBits(0u, 1)   // child EE
                    st95 = 4
                } else {
                    w.writeBits(3u, 3)   // element EE
                    done95 = true
                }
            }
            2 -> {
                if (msg.openLoopResponseTime != null) {
                    w.writeBits(0u, 2)   // OpenLoopResponseTime
                    encodeRationalNumberType(w, msg.openLoopResponseTime!!)
                    st95 = 3
                } else if (msg.timeConstantPT1 != null) {
                    w.writeBits(1u, 2)   // TimeConstantPT1
                    w.writeBits(0u, 1)   // value-start
                    ExiPrimitives.writeUnsignedInteger(w, msg.timeConstantPT1!!.toULong())
                    w.writeBits(0u, 1)   // child EE
                    st95 = 4
                } else {
                    w.writeBits(2u, 2)   // element EE
                    done95 = true
                }
            }
            3 -> {
                if (msg.timeConstantPT1 != null) {
                    w.writeBits(0u, 2)   // TimeConstantPT1
                    w.writeBits(0u, 1)   // value-start
                    ExiPrimitives.writeUnsignedInteger(w, msg.timeConstantPT1!!.toULong())
                    w.writeBits(0u, 1)   // child EE
                    st95 = 4
                } else {
                    w.writeBits(1u, 2)   // element EE
                    done95 = true
                }
            }
            4 -> {
                w.writeBits(0u, 1)   // element EE
                done95 = true
            }
        }
    }
}

internal fun decodeWattVarType(r: BitReader): WattVarType {
    r.readBits(1)   // SE
    r.readBits(1)   // value-start
    val _enable = r.readBits(1).toInt() != 0
    r.readBits(1)   // child EE
    var _priority: UShort? = null
    var _xUnit: DerUnit? = null
    var st96 = 0
    var done96 = false
    while (!done96) {
        when (st96) {
            0 -> {
                when (r.readBits(2)) {
                    0u -> {
                        r.readBits(1)   // value-start
                        _priority = ExiPrimitives.readUnsignedInteger(r).toUShort()
                        r.readBits(1)   // child EE
                        st96 = 1
                    }
                    1u -> {   // SE(XUnit)
                        r.readBits(1)   // value-start
                        _xUnit = DerUnit.entries[r.readBits(4).toInt()]
                        r.readBits(1)   // child EE
                        done96 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            1 -> {
                when (r.readBits(1)) {
                    0u -> {   // SE(XUnit)
                        r.readBits(1)   // value-start
                        _xUnit = DerUnit.entries[r.readBits(4).toInt()]
                        r.readBits(1)   // child EE
                        done96 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
        }
    }
    r.readBits(1)   // SE
    r.readBits(1)   // value-start
    val _yUnit = DerUnit.entries[r.readBits(4).toInt()]
    r.readBits(1)   // child EE
    r.readBits(1)   // SE
    val _curveDataPoints = decodeCurveDataPointsListType(r)
    var _curveDataPoints_L2: CurveDataPointsListType? = null
    var _curveDataPoints_L3: CurveDataPointsListType? = null
    var _openLoopResponseTime: RationalNumberType? = null
    var _timeConstantPT1: UInt? = null
    var st97 = 0
    var done97 = false
    while (!done97) {
        when (st97) {
            0 -> {
                when (r.readBits(3)) {
                    0u -> {
                        _curveDataPoints_L2 = decodeCurveDataPointsListType(r)
                        st97 = 1
                    }
                    1u -> {
                        _curveDataPoints_L3 = decodeCurveDataPointsListType(r)
                        st97 = 2
                    }
                    2u -> {
                        _openLoopResponseTime = decodeRationalNumberType(r)
                        st97 = 3
                    }
                    3u -> {
                        r.readBits(1)   // value-start
                        _timeConstantPT1 = ExiPrimitives.readUnsignedInteger(r).toUInt()
                        r.readBits(1)   // child EE
                        st97 = 4
                    }
                    4u -> done97 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            1 -> {
                when (r.readBits(3)) {
                    0u -> {
                        _curveDataPoints_L3 = decodeCurveDataPointsListType(r)
                        st97 = 2
                    }
                    1u -> {
                        _openLoopResponseTime = decodeRationalNumberType(r)
                        st97 = 3
                    }
                    2u -> {
                        r.readBits(1)   // value-start
                        _timeConstantPT1 = ExiPrimitives.readUnsignedInteger(r).toUInt()
                        r.readBits(1)   // child EE
                        st97 = 4
                    }
                    3u -> done97 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            2 -> {
                when (r.readBits(2)) {
                    0u -> {
                        _openLoopResponseTime = decodeRationalNumberType(r)
                        st97 = 3
                    }
                    1u -> {
                        r.readBits(1)   // value-start
                        _timeConstantPT1 = ExiPrimitives.readUnsignedInteger(r).toUInt()
                        r.readBits(1)   // child EE
                        st97 = 4
                    }
                    2u -> done97 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            3 -> {
                when (r.readBits(2)) {
                    0u -> {
                        r.readBits(1)   // value-start
                        _timeConstantPT1 = ExiPrimitives.readUnsignedInteger(r).toUInt()
                        r.readBits(1)   // child EE
                        st97 = 4
                    }
                    1u -> done97 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            4 -> {
                when (r.readBits(1)) {
                    0u -> done97 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
        }
    }
    return WattVarType(_enable, _priority, _xUnit!!, _yUnit, _curveDataPoints, _curveDataPoints_L2, _curveDataPoints_L3, _openLoopResponseTime, _timeConstantPT1)
}
