// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (TypeScript back end). Do not edit by hand.
// Schema target namespace: cloud.charging.v2g.iso2

import type { JsonObject, JsonValue } from "../runtime/index.ts";
import { JsonPrimitives } from "../runtime/index.ts";
import { AC_EVSEChargeParameterType } from "./AC_EVSEChargeParameterType.ts";
import { AC_EVSEStatusType } from "./AC_EVSEStatusType.ts";
import { PhysicalValueType } from "./PhysicalValueType.ts";
import { Iso15118_2CodecJson } from "./Iso15118_2CodecJson.Json.ts";

export function toJSONAC_EVSEChargeParameterType(value: AC_EVSEChargeParameterType): JsonObject {

    const json: JsonObject = {};

    json["@type"] = "AC_EVSEChargeParameterType";

    json["ac_EVSEStatus"] = Iso15118_2CodecJson.toJSON(value.aC_EVSEStatus);
    json["evseNominalVoltage"] = Iso15118_2CodecJson.toJSON(value.eVSENominalVoltage);
    json["evseMaxCurrent"] = Iso15118_2CodecJson.toJSON(value.eVSEMaxCurrent);
    return json;
}

export function parseJSONAC_EVSEChargeParameterType(json: JsonObject): AC_EVSEChargeParameterType {
    return new AC_EVSEChargeParameterType(
        JsonPrimitives.cast(Iso15118_2CodecJson.parseJSON(JsonPrimitives.required(json, "ac_EVSEStatus", "AC_EVSEChargeParameterType"), "AC_EVSEChargeParameterType.ac_EVSEStatus"), AC_EVSEStatusType, "ac_EVSEStatus", "AC_EVSEChargeParameterType"),
        JsonPrimitives.cast(Iso15118_2CodecJson.parseJSON(JsonPrimitives.required(json, "evseNominalVoltage", "AC_EVSEChargeParameterType"), "AC_EVSEChargeParameterType.evseNominalVoltage"), PhysicalValueType, "evseNominalVoltage", "AC_EVSEChargeParameterType"),
        JsonPrimitives.cast(Iso15118_2CodecJson.parseJSON(JsonPrimitives.required(json, "evseMaxCurrent", "AC_EVSEChargeParameterType"), "AC_EVSEChargeParameterType.evseMaxCurrent"), PhysicalValueType, "evseMaxCurrent", "AC_EVSEChargeParameterType")
    );
}

