// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (TypeScript back end). Do not edit by hand.
// Schema target namespace: cloud.charging.v2g.iso2

import type { JsonObject, JsonValue } from "../runtime/index.ts";
import { JsonPrimitives } from "../runtime/index.ts";
import { AC_EVChargeParameterType } from "./AC_EVChargeParameterType.ts";
import { PhysicalValueType } from "./PhysicalValueType.ts";
import { Iso15118_2CodecJson } from "./Iso15118_2CodecJson.Json.ts";

export function toJSONAC_EVChargeParameterType(value: AC_EVChargeParameterType): JsonObject {

    const json: JsonObject = {};

    json["@type"] = "AC_EVChargeParameterType";

    if (value.departureTime !== null) {
        json["departureTime"] = value.departureTime;
    }

    json["eAmount"] = Iso15118_2CodecJson.toJSON(value.eAmount);
    json["evMaxVoltage"] = Iso15118_2CodecJson.toJSON(value.eVMaxVoltage);
    json["evMaxCurrent"] = Iso15118_2CodecJson.toJSON(value.eVMaxCurrent);
    json["evMinCurrent"] = Iso15118_2CodecJson.toJSON(value.eVMinCurrent);
    return json;
}

export function parseJSONAC_EVChargeParameterType(json: JsonObject): AC_EVChargeParameterType {
    return new AC_EVChargeParameterType(
        ((n) => n === null ? null : JsonPrimitives.int(n, "departureTime", "AC_EVChargeParameterType"))(JsonPrimitives.optional(json, "departureTime")),
        JsonPrimitives.cast(Iso15118_2CodecJson.parseJSON(JsonPrimitives.required(json, "eAmount", "AC_EVChargeParameterType"), "AC_EVChargeParameterType.eAmount"), PhysicalValueType, "eAmount", "AC_EVChargeParameterType"),
        JsonPrimitives.cast(Iso15118_2CodecJson.parseJSON(JsonPrimitives.required(json, "evMaxVoltage", "AC_EVChargeParameterType"), "AC_EVChargeParameterType.evMaxVoltage"), PhysicalValueType, "evMaxVoltage", "AC_EVChargeParameterType"),
        JsonPrimitives.cast(Iso15118_2CodecJson.parseJSON(JsonPrimitives.required(json, "evMaxCurrent", "AC_EVChargeParameterType"), "AC_EVChargeParameterType.evMaxCurrent"), PhysicalValueType, "evMaxCurrent", "AC_EVChargeParameterType"),
        JsonPrimitives.cast(Iso15118_2CodecJson.parseJSON(JsonPrimitives.required(json, "evMinCurrent", "AC_EVChargeParameterType"), "AC_EVChargeParameterType.evMinCurrent"), PhysicalValueType, "evMinCurrent", "AC_EVChargeParameterType")
    );
}

