// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (TypeScript back end). Do not edit by hand.
// Schema target namespace: cloud.charging.v2g.iso2

import type { JsonObject, JsonValue } from "../runtime/index.ts";
import { JsonPrimitives } from "../runtime/index.ts";
import { AuthorizationResType } from "./AuthorizationResType.ts";
import { EVSEProcessing, EVSEProcessingNames } from "./EVSEProcessing.ts";
import { ResponseCode, ResponseCodeNames } from "./ResponseCode.ts";

export function toJSONAuthorizationResType(value: AuthorizationResType): JsonObject {

    const json: JsonObject = {};

    json["@type"] = "AuthorizationResType";

    json["responseCode"] = ResponseCodeNames[value.responseCode];
    json["evseProcessing"] = EVSEProcessingNames[value.eVSEProcessing];
    return json;
}

export function parseJSONAuthorizationResType(json: JsonObject): AuthorizationResType {
    return new AuthorizationResType(
        JsonPrimitives.enumeration(JsonPrimitives.required(json, "responseCode", "AuthorizationResType"), "responseCode", "AuthorizationResType", "ResponseCode", ResponseCodeNames) as ResponseCode,
        JsonPrimitives.enumeration(JsonPrimitives.required(json, "evseProcessing", "AuthorizationResType"), "evseProcessing", "AuthorizationResType", "EVSEProcessing", EVSEProcessingNames) as EVSEProcessing
    );
}

