// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (TypeScript back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Schema target namespace: cloud.charging.v2g.iso2

import { BitReader, BitWriter, ExiError, ExiPrimitives } from "../runtime/index.ts";
import { BodyBaseType } from "./BodyBaseType.ts";

export class AuthorizationReqType extends BodyBaseType {
    readonly id: string | null;
    readonly genChallenge: Uint8Array | null;

    constructor(id: string | null, genChallenge: Uint8Array | null) {
        super();
        this.id = id;
        this.genChallenge = genChallenge;
    }
}

export function encodeAuthorizationReqType(w: BitWriter, msg: AuthorizationReqType): void {
    let st31 = 0
    let done31 = false
    while (!done31) {
        { const _c32 = st31; if (false) {}   // dispatch
            else if (_c32 === 0) {
                if (msg.id != null) {
                    w.writeBits(0, 2)   // Id
                    ExiPrimitives.writeStringValue(w, msg.id!)
                    st31 = 1
                } else if (msg.genChallenge != null) {
                    w.writeBits(1, 2)   // GenChallenge
                    w.writeBits(0, 1)   // value-start
                    ExiPrimitives.writeBinary(w, msg.genChallenge!)
                    w.writeBits(0, 1)   // child EE
                    st31 = 2
                } else {
                    w.writeBits(2, 2)   // element EE
                    done31 = true
                }
            }
            else if (_c32 === 1) {
                if (msg.genChallenge != null) {
                    w.writeBits(0, 2)   // GenChallenge
                    w.writeBits(0, 1)   // value-start
                    ExiPrimitives.writeBinary(w, msg.genChallenge!)
                    w.writeBits(0, 1)   // child EE
                    st31 = 2
                } else {
                    w.writeBits(1, 2)   // element EE
                    done31 = true
                }
            }
            else if (_c32 === 2) {
                w.writeBits(0, 1)   // element EE
                done31 = true
            }
        }
    }
}

export function decodeAuthorizationReqType(r: BitReader): AuthorizationReqType {
    let _id: string | null = null
    let _genChallenge: Uint8Array | null = null
    let st33 = 0
    let done33 = false
    while (!done33) {
        { const _c34 = st33; if (false) {}   // dispatch
            else if (_c34 === 0) {
                { const _c35 = r.readBits(2); if (false) {}   // dispatch
                    else if (_c35 === 0) {
                        _id = ExiPrimitives.readStringValue(r, "Id")
                        st33 = 1
                    }
                    else if (_c35 === 1) {
                        r.readBits(1)   // value-start
                        _genChallenge = ExiPrimitives.readBinary(r)
                        r.readBits(1)   // child EE
                        st33 = 2
                    }
                    else if (_c35 === 2) done33 = true;   // element EE
                    else throw ExiError.invalidEventCode("optional run");
                }
            }
            else if (_c34 === 1) {
                { const _c36 = r.readBits(2); if (false) {}   // dispatch
                    else if (_c36 === 0) {
                        r.readBits(1)   // value-start
                        _genChallenge = ExiPrimitives.readBinary(r)
                        r.readBits(1)   // child EE
                        st33 = 2
                    }
                    else if (_c36 === 1) done33 = true;   // element EE
                    else throw ExiError.invalidEventCode("optional run");
                }
            }
            else if (_c34 === 2) {
                { const _c37 = r.readBits(1); if (false) {}   // dispatch
                    else if (_c37 === 0) done33 = true;   // element EE
                    else throw ExiError.invalidEventCode("optional run");
                }
            }
        }
    }
    return new AuthorizationReqType(_id, _genChallenge);
}
