// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (TypeScript back end). Do not edit by hand.
// Schema target namespace: cloud.charging.v2g.iso2

export const EVSEProcessing = {
    Finished: 0,
    Ongoing: 1,
    Ongoing_WaitingForCustomerInteraction: 2,
} as const;

export type EVSEProcessing = (typeof EVSEProcessing)[keyof typeof EVSEProcessing];

export const EVSEProcessingNames = ["Finished", "Ongoing", "Ongoing_WaitingForCustomerInteraction"] as const;
