// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (TypeScript back end). Do not edit by hand.
// Schema target namespace: cloud.charging.v2g.iso2

import type { JsonObject, JsonValue } from "../runtime/index.ts";
import { JsonPrimitives } from "../runtime/index.ts";
import { PaymentDetailsResType } from "./PaymentDetailsResType.ts";
import { ResponseCode, ResponseCodeNames } from "./ResponseCode.ts";

export function toJSONPaymentDetailsResType(value: PaymentDetailsResType): JsonObject {

    const json: JsonObject = {};

    json["@type"] = "PaymentDetailsResType";

    json["responseCode"] = ResponseCodeNames[value.responseCode];
    json["genChallenge"] = JsonPrimitives.toHex(value.genChallenge);
    json["evseTimeStamp"] = value.eVSETimeStamp.toString();
    return json;
}

export function parseJSONPaymentDetailsResType(json: JsonObject): PaymentDetailsResType {
    return new PaymentDetailsResType(
        JsonPrimitives.enumeration(JsonPrimitives.required(json, "responseCode", "PaymentDetailsResType"), "responseCode", "PaymentDetailsResType", "ResponseCode", ResponseCodeNames) as ResponseCode,
        JsonPrimitives.binary(JsonPrimitives.required(json, "genChallenge", "PaymentDetailsResType"), "genChallenge", "PaymentDetailsResType"),
        JsonPrimitives.big(JsonPrimitives.required(json, "evseTimeStamp", "PaymentDetailsResType"), "evseTimeStamp", "PaymentDetailsResType")
    );
}

