// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (TypeScript back end). Do not edit by hand.
// Schema target namespace: cloud.charging.v2g.iso2

import type { JsonObject, JsonValue } from "../runtime/index.ts";
import { JsonPrimitives } from "../runtime/index.ts";
import { PhysicalValueType } from "./PhysicalValueType.ts";
import { UnitSymbol, UnitSymbolNames } from "./UnitSymbol.ts";

export function toJSONPhysicalValueType(value: PhysicalValueType): JsonObject {

    const json: JsonObject = {};

    json["@type"] = "PhysicalValueType";

    json["multiplier"] = value.multiplier;
    json["unit"] = UnitSymbolNames[value.unit];
    json["value"] = value.value;
    return json;
}

export function parseJSONPhysicalValueType(json: JsonObject): PhysicalValueType {
    return new PhysicalValueType(
        JsonPrimitives.int(JsonPrimitives.required(json, "multiplier", "PhysicalValueType"), "multiplier", "PhysicalValueType"),
        JsonPrimitives.enumeration(JsonPrimitives.required(json, "unit", "PhysicalValueType"), "unit", "PhysicalValueType", "UnitSymbol", UnitSymbolNames) as UnitSymbol,
        JsonPrimitives.int(JsonPrimitives.required(json, "value", "PhysicalValueType"), "value", "PhysicalValueType")
    );
}

