// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (TypeScript back end). Do not edit by hand.
// Schema target namespace: cloud.charging.v2g.iso2

export const ServiceCategory = {
    EVCharging: 0,
    Internet: 1,
    ContractCertificate: 2,
    OtherCustom: 3,
} as const;

export type ServiceCategory = (typeof ServiceCategory)[keyof typeof ServiceCategory];

export const ServiceCategoryNames = ["EVCharging", "Internet", "ContractCertificate", "OtherCustom"] as const;
