// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (TypeScript back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Schema target namespace: cloud.charging.v2g.iso2

import type { JsonObject, JsonValue } from "../runtime/index.ts";
import { JsonPrimitives } from "../runtime/index.ts";
import { EnergyTransferMode, EnergyTransferModeNames } from "./EnergyTransferMode.ts";
import { SupportedEnergyTransferModeType } from "./SupportedEnergyTransferModeType.ts";

export function toJSONSupportedEnergyTransferModeType(value: SupportedEnergyTransferModeType): JsonObject {

    const json: JsonObject = {};

    json["@type"] = "SupportedEnergyTransferModeType";

    json["energyTransferMode"] = value.energyTransferMode.map(item => EnergyTransferModeNames[item]);

    return json;
}

export function parseJSONSupportedEnergyTransferModeType(json: JsonObject): SupportedEnergyTransferModeType {
    return new SupportedEnergyTransferModeType(
        ((a) => Array.isArray(a) ? a.map(it => JsonPrimitives.enumeration(it, "energyTransferMode", "SupportedEnergyTransferModeType", "EnergyTransferMode", EnergyTransferModeNames) as EnergyTransferMode) : [])(JsonPrimitives.optional(json, "energyTransferMode"))
    );
}

