// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (TypeScript back end). Do not edit by hand.
// Schema target namespace: cloud.charging.v2g.iso20.common

import type { JsonObject, JsonValue } from "../runtime/index.ts";
import { JsonPrimitives } from "../runtime/index.ts";
import { Authorization, AuthorizationNames } from "./Authorization.ts";
import { AuthorizationSetupRes } from "./AuthorizationSetupRes.ts";
import { EIM_ASResAuthorizationModeType } from "./EIM_ASResAuthorizationModeType.ts";
import { MessageHeaderType } from "./MessageHeaderType.ts";
import { PnC_ASResAuthorizationModeType } from "./PnC_ASResAuthorizationModeType.ts";
import { ResponseCode, ResponseCodeNames } from "./ResponseCode.ts";
import { CommonMessagesCodecJson } from "./CommonMessagesCodecJson.Json.ts";

export function toJSONAuthorizationSetupRes(value: AuthorizationSetupRes): JsonObject {

    const json: JsonObject = {};

    json["@context"] = CommonMessagesCodecJson.context;
    json["@type"] = "AuthorizationSetupRes";

    json["header"] = CommonMessagesCodecJson.toJSON(value.header);
    json["responseCode"] = ResponseCodeNames[value.responseCode];
    json["authorizationServices"] = value.authorizationServices.map(item => AuthorizationNames[item]);

    json["certificateInstallationService"] = value.certificateInstallationService;
    if (value.eIM_ASResAuthorizationMode !== null) {
        json["eim_ASResAuthorizationMode"] = CommonMessagesCodecJson.toJSON(value.eIM_ASResAuthorizationMode);
    }

    if (value.pnC_ASResAuthorizationMode !== null) {
        json["pnC_ASResAuthorizationMode"] = CommonMessagesCodecJson.toJSON(value.pnC_ASResAuthorizationMode);
    }

    return json;
}

export function parseJSONAuthorizationSetupRes(json: JsonObject): AuthorizationSetupRes {
    return new AuthorizationSetupRes(
        JsonPrimitives.cast(CommonMessagesCodecJson.parseJSON(JsonPrimitives.required(json, "header", "AuthorizationSetupRes"), "AuthorizationSetupRes.header"), MessageHeaderType, "header", "AuthorizationSetupRes"),
        JsonPrimitives.enumeration(JsonPrimitives.required(json, "responseCode", "AuthorizationSetupRes"), "responseCode", "AuthorizationSetupRes", "ResponseCode", ResponseCodeNames) as ResponseCode,
        JsonPrimitives.array(json, "authorizationServices", "AuthorizationSetupRes").map(it => JsonPrimitives.enumeration(it, "authorizationServices", "AuthorizationSetupRes", "Authorization", AuthorizationNames) as Authorization),
        JsonPrimitives.bool(JsonPrimitives.required(json, "certificateInstallationService", "AuthorizationSetupRes"), "certificateInstallationService", "AuthorizationSetupRes"),
        ((n) => n === null ? null : JsonPrimitives.cast(CommonMessagesCodecJson.parseJSON(n, "AuthorizationSetupRes.eim_ASResAuthorizationMode"), EIM_ASResAuthorizationModeType, "eim_ASResAuthorizationMode", "AuthorizationSetupRes"))(JsonPrimitives.optional(json, "eim_ASResAuthorizationMode")),
        ((n) => n === null ? null : JsonPrimitives.cast(CommonMessagesCodecJson.parseJSON(n, "AuthorizationSetupRes.pnC_ASResAuthorizationMode"), PnC_ASResAuthorizationModeType, "pnC_ASResAuthorizationMode", "AuthorizationSetupRes"))(JsonPrimitives.optional(json, "pnC_ASResAuthorizationMode"))
    );
}

