// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (TypeScript back end). Do not edit by hand.
// Schema target namespace: cloud.charging.v2g.iso20.common

import { BitReader, BitWriter, ExiError, ExiPrimitives } from "../runtime/index.ts";
import { SubCertificatesType, encodeSubCertificatesType, decodeSubCertificatesType } from "./SubCertificatesType.ts";

export class CertificateChainType {
    readonly certificate: Uint8Array;
    readonly subCertificates: SubCertificatesType | null;

    constructor(certificate: Uint8Array, subCertificates: SubCertificatesType | null) {
        this.certificate = certificate;
        this.subCertificates = subCertificates;
    }
}

export function encodeCertificateChainType(w: BitWriter, msg: CertificateChainType): void {
    w.writeBits(0, 1)   // SE
    w.writeBits(0, 1)   // value-start
    ExiPrimitives.writeBinary(w, msg.certificate)
    w.writeBits(0, 1)   // child EE
    let st224 = 0
    let done224 = false
    while (!done224) {
        { const _c225 = st224; if (false) {}   // dispatch
            else if (_c225 === 0) {
                if (msg.subCertificates != null) {
                    w.writeBits(0, 2)   // SubCertificates
                    encodeSubCertificatesType(w, msg.subCertificates!)
                    st224 = 1
                } else {
                    w.writeBits(1, 2)   // element EE
                    done224 = true
                }
            }
            else if (_c225 === 1) {
                w.writeBits(0, 1)   // element EE
                done224 = true
            }
        }
    }
}

export function decodeCertificateChainType(r: BitReader): CertificateChainType {
    r.readBits(1)   // SE
    r.readBits(1)   // value-start
    const _certificate = ExiPrimitives.readBinary(r)
    r.readBits(1)   // child EE
    let _subCertificates: SubCertificatesType | null = null
    let st226 = 0
    let done226 = false
    while (!done226) {
        { const _c227 = st226; if (false) {}   // dispatch
            else if (_c227 === 0) {
                { const _c228 = r.readBits(2); if (false) {}   // dispatch
                    else if (_c228 === 0) {
                        _subCertificates = decodeSubCertificatesType(r)
                        st226 = 1
                    }
                    else if (_c228 === 1) done226 = true;   // element EE
                    else throw ExiError.invalidEventCode("optional run");
                }
            }
            else if (_c227 === 1) {
                { const _c229 = r.readBits(1); if (false) {}   // dispatch
                    else if (_c229 === 0) done226 = true;   // element EE
                    else throw ExiError.invalidEventCode("optional run");
                }
            }
        }
    }
    return new CertificateChainType(_certificate, _subCertificates);
}
