// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (TypeScript back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Schema target namespace: cloud.charging.v2g.iso20.common

import { BitReader, BitWriter, ExiError } from "../runtime/index.ts";
import { EMAIDListType, encodeEMAIDListType, decodeEMAIDListType } from "./EMAIDListType.ts";
import { ListOfRootCertificateIDsType, encodeListOfRootCertificateIDsType, decodeListOfRootCertificateIDsType } from "./ListOfRootCertificateIDsType.ts";
import { MessageHeaderType, encodeMessageHeaderType, decodeMessageHeaderType } from "./MessageHeaderType.ts";
import { SignedCertificateChainType, encodeSignedCertificateChainType, decodeSignedCertificateChainType } from "./SignedCertificateChainType.ts";
import { V2GRequestType } from "./V2GRequestType.ts";

export class CertificateInstallationReq extends V2GRequestType {
    readonly oEMProvisioningCertificateChain: SignedCertificateChainType;
    readonly listOfRootCertificateIDs: ListOfRootCertificateIDsType;
    readonly maximumContractCertificateChains: number;
    readonly prioritizedEMAIDs: EMAIDListType | null;

    constructor(header: MessageHeaderType, oEMProvisioningCertificateChain: SignedCertificateChainType, listOfRootCertificateIDs: ListOfRootCertificateIDsType, maximumContractCertificateChains: number, prioritizedEMAIDs: EMAIDListType | null) {
        super(header);
        this.oEMProvisioningCertificateChain = oEMProvisioningCertificateChain;
        this.listOfRootCertificateIDs = listOfRootCertificateIDs;
        this.maximumContractCertificateChains = maximumContractCertificateChains;
        this.prioritizedEMAIDs = prioritizedEMAIDs;
    }
}

export function encodeCertificateInstallationReq(w: BitWriter, msg: CertificateInstallationReq): void {
    w.writeBits(0, 1)   // SE
    encodeMessageHeaderType(w, msg.header)
    w.writeBits(0, 1)   // SE
    encodeSignedCertificateChainType(w, msg.oEMProvisioningCertificateChain)
    w.writeBits(0, 1)   // SE
    encodeListOfRootCertificateIDsType(w, msg.listOfRootCertificateIDs)
    w.writeBits(0, 1)   // SE
    w.writeBits(0, 1)   // value-start
    w.writeBits(msg.maximumContractCertificateChains, 8)
    w.writeBits(0, 1)   // child EE
    let st387 = 0
    let done387 = false
    while (!done387) {
        { const _c388 = st387; if (false) {}   // dispatch
            else if (_c388 === 0) {
                if (msg.prioritizedEMAIDs != null) {
                    w.writeBits(0, 2)   // PrioritizedEMAIDs
                    encodeEMAIDListType(w, msg.prioritizedEMAIDs!)
                    st387 = 1
                } else {
                    w.writeBits(1, 2)   // element EE
                    done387 = true
                }
            }
            else if (_c388 === 1) {
                w.writeBits(0, 1)   // element EE
                done387 = true
            }
        }
    }
}

export function decodeCertificateInstallationReq(r: BitReader): CertificateInstallationReq {
    r.readBits(1)   // SE
    const _header = decodeMessageHeaderType(r)
    r.readBits(1)   // SE
    const _oEMProvisioningCertificateChain = decodeSignedCertificateChainType(r)
    r.readBits(1)   // SE
    const _listOfRootCertificateIDs = decodeListOfRootCertificateIDsType(r)
    r.readBits(1)   // SE
    r.readBits(1)   // value-start
    const _maximumContractCertificateChains = r.readBits(8)
    r.readBits(1)   // child EE
    let _prioritizedEMAIDs: EMAIDListType | null = null
    let st389 = 0
    let done389 = false
    while (!done389) {
        { const _c390 = st389; if (false) {}   // dispatch
            else if (_c390 === 0) {
                { const _c391 = r.readBits(2); if (false) {}   // dispatch
                    else if (_c391 === 0) {
                        _prioritizedEMAIDs = decodeEMAIDListType(r)
                        st389 = 1
                    }
                    else if (_c391 === 1) done389 = true;   // element EE
                    else throw ExiError.invalidEventCode("optional run");
                }
            }
            else if (_c390 === 1) {
                { const _c392 = r.readBits(1); if (false) {}   // dispatch
                    else if (_c392 === 0) done389 = true;   // element EE
                    else throw ExiError.invalidEventCode("optional run");
                }
            }
        }
    }
    return new CertificateInstallationReq(_header, _oEMProvisioningCertificateChain, _listOfRootCertificateIDs, _maximumContractCertificateChains, _prioritizedEMAIDs);
}
