// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (TypeScript back end). Do not edit by hand.
// Schema target namespace: cloud.charging.v2g.iso20.common

import type { JsonObject, JsonValue } from "../runtime/index.ts";
import { JsonPrimitives } from "../runtime/index.ts";
import { OverstayRuleType } from "./OverstayRuleType.ts";
import { RationalNumberType } from "./RationalNumberType.ts";
import { CommonMessagesCodecJson } from "./CommonMessagesCodecJson.Json.ts";

export function toJSONOverstayRuleType(value: OverstayRuleType): JsonObject {

    const json: JsonObject = {};

    json["@type"] = "OverstayRuleType";

    if (value.overstayRuleDescription !== null) {
        json["overstayRuleDescription"] = value.overstayRuleDescription;
    }

    json["startTime"] = value.startTime;
    json["overstayFee"] = CommonMessagesCodecJson.toJSON(value.overstayFee);
    json["overstayFeePeriod"] = value.overstayFeePeriod;
    return json;
}

export function parseJSONOverstayRuleType(json: JsonObject): OverstayRuleType {
    return new OverstayRuleType(
        ((n) => n === null ? null : JsonPrimitives.stringValue(n, "overstayRuleDescription", "OverstayRuleType"))(JsonPrimitives.optional(json, "overstayRuleDescription")),
        JsonPrimitives.int(JsonPrimitives.required(json, "startTime", "OverstayRuleType"), "startTime", "OverstayRuleType"),
        JsonPrimitives.cast(CommonMessagesCodecJson.parseJSON(JsonPrimitives.required(json, "overstayFee", "OverstayRuleType"), "OverstayRuleType.overstayFee"), RationalNumberType, "overstayFee", "OverstayRuleType"),
        JsonPrimitives.int(JsonPrimitives.required(json, "overstayFeePeriod", "OverstayRuleType"), "overstayFeePeriod", "OverstayRuleType")
    );
}

