// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (TypeScript back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Schema target namespace: cloud.charging.v2g.iso20.common

import type { JsonObject, JsonValue } from "../runtime/index.ts";
import { JsonPrimitives } from "../runtime/index.ts";
import { OverstayRuleListType } from "./OverstayRuleListType.ts";
import { OverstayRuleType } from "./OverstayRuleType.ts";
import { RationalNumberType } from "./RationalNumberType.ts";
import { CommonMessagesCodecJson } from "./CommonMessagesCodecJson.Json.ts";

export function toJSONOverstayRuleListType(value: OverstayRuleListType): JsonObject {

    const json: JsonObject = {};

    json["@type"] = "OverstayRuleListType";

    if (value.overstayTimeThreshold !== null) {
        json["overstayTimeThreshold"] = value.overstayTimeThreshold;
    }

    if (value.overstayPowerThreshold !== null) {
        json["overstayPowerThreshold"] = CommonMessagesCodecJson.toJSON(value.overstayPowerThreshold);
    }

    json["overstayRule"] = value.overstayRule.map(item => CommonMessagesCodecJson.toJSON(item));

    return json;
}

export function parseJSONOverstayRuleListType(json: JsonObject): OverstayRuleListType {
    return new OverstayRuleListType(
        ((n) => n === null ? null : JsonPrimitives.int(n, "overstayTimeThreshold", "OverstayRuleListType"))(JsonPrimitives.optional(json, "overstayTimeThreshold")),
        ((n) => n === null ? null : JsonPrimitives.cast(CommonMessagesCodecJson.parseJSON(n, "OverstayRuleListType.overstayPowerThreshold"), RationalNumberType, "overstayPowerThreshold", "OverstayRuleListType"))(JsonPrimitives.optional(json, "overstayPowerThreshold")),
        JsonPrimitives.array(json, "overstayRule", "OverstayRuleListType").map(it => JsonPrimitives.cast(CommonMessagesCodecJson.parseJSON(it, "OverstayRuleListType.overstayRule"), OverstayRuleType, "overstayRule", "OverstayRuleListType"))
    );
}

