// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (TypeScript back end). Do not edit by hand.
// Schema target namespace: cloud.charging.v2g.iso20.common

import type { JsonObject, JsonValue } from "../runtime/index.ts";
import { JsonPrimitives } from "../runtime/index.ts";
import { Dynamic_SEResControlModeType } from "./Dynamic_SEResControlModeType.ts";
import { MessageHeaderType } from "./MessageHeaderType.ts";
import { Processing, ProcessingNames } from "./Processing.ts";
import { ResponseCode, ResponseCodeNames } from "./ResponseCode.ts";
import { ScheduleExchangeResType } from "./ScheduleExchangeResType.ts";
import { Scheduled_SEResControlModeType } from "./Scheduled_SEResControlModeType.ts";
import { CommonMessagesCodecJson } from "./CommonMessagesCodecJson.Json.ts";

export function toJSONScheduleExchangeResType(value: ScheduleExchangeResType): JsonObject {

    const json: JsonObject = {};

    json["@type"] = "ScheduleExchangeResType";

    json["header"] = CommonMessagesCodecJson.toJSON(value.header);
    json["responseCode"] = ResponseCodeNames[value.responseCode];
    json["evseProcessing"] = ProcessingNames[value.eVSEProcessing];
    if (value.goToPause !== null) {
        json["goToPause"] = value.goToPause;
    }

    if (value.dynamic_SEResControlMode !== null) {
        json["dynamic_SEResControlMode"] = CommonMessagesCodecJson.toJSON(value.dynamic_SEResControlMode);
    }

    if (value.scheduled_SEResControlMode !== null) {
        json["scheduled_SEResControlMode"] = CommonMessagesCodecJson.toJSON(value.scheduled_SEResControlMode);
    }

    return json;
}

export function parseJSONScheduleExchangeResType(json: JsonObject): ScheduleExchangeResType {
    return new ScheduleExchangeResType(
        JsonPrimitives.cast(CommonMessagesCodecJson.parseJSON(JsonPrimitives.required(json, "header", "ScheduleExchangeResType"), "ScheduleExchangeResType.header"), MessageHeaderType, "header", "ScheduleExchangeResType"),
        JsonPrimitives.enumeration(JsonPrimitives.required(json, "responseCode", "ScheduleExchangeResType"), "responseCode", "ScheduleExchangeResType", "ResponseCode", ResponseCodeNames) as ResponseCode,
        JsonPrimitives.enumeration(JsonPrimitives.required(json, "evseProcessing", "ScheduleExchangeResType"), "evseProcessing", "ScheduleExchangeResType", "Processing", ProcessingNames) as Processing,
        ((n) => n === null ? null : JsonPrimitives.bool(n, "goToPause", "ScheduleExchangeResType"))(JsonPrimitives.optional(json, "goToPause")),
        ((n) => n === null ? null : JsonPrimitives.cast(CommonMessagesCodecJson.parseJSON(n, "ScheduleExchangeResType.dynamic_SEResControlMode"), Dynamic_SEResControlModeType, "dynamic_SEResControlMode", "ScheduleExchangeResType"))(JsonPrimitives.optional(json, "dynamic_SEResControlMode")),
        ((n) => n === null ? null : JsonPrimitives.cast(CommonMessagesCodecJson.parseJSON(n, "ScheduleExchangeResType.scheduled_SEResControlMode"), Scheduled_SEResControlModeType, "scheduled_SEResControlMode", "ScheduleExchangeResType"))(JsonPrimitives.optional(json, "scheduled_SEResControlMode"))
    );
}

