// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (TypeScript back end). Do not edit by hand.
// Schema target namespace: cloud.charging.v2g.iso20.common

import { BitReader, BitWriter, ExiError } from "../runtime/index.ts";
import { ScheduleTupleType, encodeScheduleTupleType, decodeScheduleTupleType } from "./ScheduleTupleType.ts";

export class Scheduled_SEResControlModeType {
    readonly scheduleTuple: readonly ScheduleTupleType[];

    constructor(scheduleTuple: readonly ScheduleTupleType[]) {
        this.scheduleTuple = scheduleTuple;
    }
}

export function encodeScheduled_SEResControlModeType(w: BitWriter, msg: Scheduled_SEResControlModeType): void {
    const list = msg.scheduleTuple
    if (list.length < 1 || list.length > 3) throw new RangeError("list: list size out of schema range");
    for (let i = 0; i < list.length; i++) {
        w.writeBits(0, i === 0 ? 1 : 2);   // SE(item)
        encodeScheduleTupleType(w, list[i])
    }
    w.writeBits(1, 2)   // list terminator / element EE
}

export function decodeScheduled_SEResControlModeType(r: BitReader): Scheduled_SEResControlModeType {
    const list = new Array<ScheduleTupleType>()
    r.readBits(1)   // SE(item) first
    list.push(decodeScheduleTupleType(r));
    while (true) {
        const ec = r.readBits(2)
        if (ec === 1) break;   // element EE
        if (!(ec === 0 && list.length < 3)) throw ExiError.invalidEventCode("repeating element");
        list.push(decodeScheduleTupleType(r));
    }
    return new Scheduled_SEResControlModeType(list);
}
