// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (TypeScript back end). Do not edit by hand.
// Schema target namespace: cloud.charging.v2g.iso20.common

import { BitReader, BitWriter, ExiError } from "../runtime/index.ts";
import { Dynamic_SEReqControlModeType, encodeDynamic_SEReqControlModeType, decodeDynamic_SEReqControlModeType } from "./Dynamic_SEReqControlModeType.ts";
import { MessageHeaderType, encodeMessageHeaderType, decodeMessageHeaderType } from "./MessageHeaderType.ts";
import { Scheduled_SEReqControlModeType, encodeScheduled_SEReqControlModeType, decodeScheduled_SEReqControlModeType } from "./Scheduled_SEReqControlModeType.ts";
import { V2GRequestType } from "./V2GRequestType.ts";

export class ScheduleExchangeReq extends V2GRequestType {
    readonly maximumSupportingPoints: number;
    readonly dynamic_SEReqControlMode: Dynamic_SEReqControlModeType | null;
    readonly scheduled_SEReqControlMode: Scheduled_SEReqControlModeType | null;

    constructor(header: MessageHeaderType, maximumSupportingPoints: number, dynamic_SEReqControlMode: Dynamic_SEReqControlModeType | null, scheduled_SEReqControlMode: Scheduled_SEReqControlModeType | null) {
        super(header);
        this.maximumSupportingPoints = maximumSupportingPoints;
        this.dynamic_SEReqControlMode = dynamic_SEReqControlMode;
        this.scheduled_SEReqControlMode = scheduled_SEReqControlMode;
    }
}

export function encodeScheduleExchangeReq(w: BitWriter, msg: ScheduleExchangeReq): void {
    w.writeBits(0, 1)   // SE
    encodeMessageHeaderType(w, msg.header)
    w.writeBits(0, 1)   // SE
    w.writeBits(0, 1)   // value-start
    w.writeBits((msg.maximumSupportingPoints - 12), 10)
    w.writeBits(0, 1)   // child EE
    if (msg.dynamic_SEReqControlMode != null) {
        w.writeBits(0, 2)   // Dynamic_SEReqControlMode
        encodeDynamic_SEReqControlModeType(w, msg.dynamic_SEReqControlMode!)
    } else if (msg.scheduled_SEReqControlMode != null) {
        w.writeBits(1, 2)   // Scheduled_SEReqControlMode
        encodeScheduled_SEReqControlModeType(w, msg.scheduled_SEReqControlMode!)
    } else {
        throw new TypeError("no choice alternative set");
    }
    w.writeBits(0, 1)   // element EE
}

export function decodeScheduleExchangeReq(r: BitReader): ScheduleExchangeReq {
    r.readBits(1)   // SE
    const _header = decodeMessageHeaderType(r)
    r.readBits(1)   // SE
    r.readBits(1)   // value-start
    const _maximumSupportingPoints = (r.readBits(10) + 12)
    r.readBits(1)   // child EE
    let _dynamic_SEReqControlMode: Dynamic_SEReqControlModeType = null
    let _scheduled_SEReqControlMode: Scheduled_SEReqControlModeType = null
    { const _c360 = r.readBits(2); if (false) {}   // dispatch
        else if (_c360 === 0) {   // Dynamic_SEReqControlMode
            _dynamic_SEReqControlMode = decodeDynamic_SEReqControlModeType(r)
        }
        else if (_c360 === 1) {   // Scheduled_SEReqControlMode
            _scheduled_SEReqControlMode = decodeScheduled_SEReqControlModeType(r)
        }
        else throw ExiError.invalidEventCode("choice");
    }
    r.readBits(1)   // element EE
    return new ScheduleExchangeReq(_header, _maximumSupportingPoints, _dynamic_SEReqControlMode, _scheduled_SEReqControlMode);
}
