// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (TypeScript back end). Do not edit by hand.
// Schema target namespace: cloud.charging.v2g.iso20.common

import { BitReader, BitWriter, ExiPrimitives } from "../runtime/index.ts";

export class SelectedServiceType {
    readonly serviceID: number;
    readonly parameterSetID: number;

    constructor(serviceID: number, parameterSetID: number) {
        this.serviceID = serviceID;
        this.parameterSetID = parameterSetID;
    }
}

export function encodeSelectedServiceType(w: BitWriter, msg: SelectedServiceType): void {
    w.writeBits(0, 1)   // SE
    w.writeBits(0, 1)   // value-start
    ExiPrimitives.writeUnsignedInteger(w, BigInt(msg.serviceID));
    w.writeBits(0, 1)   // child EE
    w.writeBits(0, 1)   // SE
    w.writeBits(0, 1)   // value-start
    ExiPrimitives.writeUnsignedInteger(w, BigInt(msg.parameterSetID));
    w.writeBits(0, 1)   // child EE
    w.writeBits(0, 1)   // element EE
}

export function decodeSelectedServiceType(r: BitReader): SelectedServiceType {
    r.readBits(1)   // SE
    r.readBits(1)   // value-start
    const _serviceID = Number(ExiPrimitives.readUnsignedInteger(r))
    r.readBits(1)   // child EE
    r.readBits(1)   // SE
    r.readBits(1)   // value-start
    const _parameterSetID = Number(ExiPrimitives.readUnsignedInteger(r))
    r.readBits(1)   // child EE
    r.readBits(1)   // element EE
    return new SelectedServiceType(_serviceID, _parameterSetID);
}
