// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (TypeScript back end). Do not edit by hand.
// Schema target namespace: cloud.charging.v2g.iso20.common

import type { JsonObject, JsonValue } from "../runtime/index.ts";
import { JsonPrimitives } from "../runtime/index.ts";
import { SupportedProvidersListType } from "./SupportedProvidersListType.ts";

export function toJSONSupportedProvidersListType(value: SupportedProvidersListType): JsonObject {

    const json: JsonObject = {};

    json["@type"] = "SupportedProvidersListType";

    json["providerID"] = value.providerID.map(item => item);

    return json;
}

export function parseJSONSupportedProvidersListType(json: JsonObject): SupportedProvidersListType {
    return new SupportedProvidersListType(
        ((a) => Array.isArray(a) ? a.map(it => JsonPrimitives.stringValue(it, "providerID", "SupportedProvidersListType")) : [])(JsonPrimitives.optional(json, "providerID"))
    );
}

