// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (TypeScript back end). Do not edit by hand.
// Schema target namespace: cloud.charging.v2g.iso20.common

import { BitReader, BitWriter, ExiError } from "../runtime/index.ts";
import { TaxRuleType, encodeTaxRuleType, decodeTaxRuleType } from "./TaxRuleType.ts";

export class TaxRuleListType {
    readonly taxRule: readonly TaxRuleType[];

    constructor(taxRule: readonly TaxRuleType[]) {
        this.taxRule = taxRule;
    }
}

export function encodeTaxRuleListType(w: BitWriter, msg: TaxRuleListType): void {
    const list = msg.taxRule
    if (list.length < 1 || list.length > 10) throw new RangeError("list: list size out of schema range");
    for (let i = 0; i < list.length; i++) {
        w.writeBits(0, i === 0 ? 1 : 2);   // SE(item)
        encodeTaxRuleType(w, list[i])
    }
    w.writeBits(1, 2)   // list terminator / element EE
}

export function decodeTaxRuleListType(r: BitReader): TaxRuleListType {
    const list = new Array<TaxRuleType>()
    r.readBits(1)   // SE(item) first
    list.push(decodeTaxRuleType(r));
    while (true) {
        const ec = r.readBits(2)
        if (ec === 1) break;   // element EE
        if (!(ec === 0 && list.length < 10)) throw ExiError.invalidEventCode("repeating element");
        list.push(decodeTaxRuleType(r));
    }
    return new TaxRuleListType(list);
}
