// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Swift back end). Do not edit by hand.
// Schema target namespace: ExiXmlDsig

import ExiRuntime

public final class CanonicalizationMethodType {
    public var algorithm: String
    public var aNY: [UInt8]?

    public init(algorithm: String, aNY: [UInt8]? = nil) {
        self.algorithm = algorithm
        self.aNY = aNY
    }
}

internal func encodeCanonicalizationMethodType(_ w: BitWriter, _ msg: CanonicalizationMethodType) {
    w.writeBits(0, 1)   // AT(required attribute)
    ExiPrimitives.writeStringValue(w, msg.algorithm)
    var st8 = 0
    var done8 = false
    while !done8 {
        switch st8 {
        case 0:
            if let v = msg.aNY {
                w.writeBits(2, 2)   // ANY
                w.writeBits(0, 1)   // value-start
                ExiPrimitives.writeBinary(w, v)
                w.writeBits(0, 1)   // child EE
                st8 = 1
            } else {
                w.writeBits(1, 2)   // element EE
                done8 = true
            }
        case 1:
            w.writeBits(0, 1)   // element EE
            done8 = true
        default:
            done8 = true
        }
    }
}

internal func decodeCanonicalizationMethodType(_ r: BitReader) throws -> CanonicalizationMethodType {
    _ = try r.readBits(1)   // AT(required attribute)
    let _algorithm = try ExiPrimitives.readStringValue(r, slot: "Algorithm")
    var _aNY: [UInt8]? = nil
    var st9 = 0
    var done9 = false
    while !done9 {
        switch st9 {
        case 0:
            switch try r.readBits(2) {
            case 2:   // ANY
                _ = try r.readBits(1)   // value-start
                _aNY = try ExiPrimitives.readBinary(r)
                _ = try r.readBits(1)   // child EE
                st9 = 1
            case 1:   // element EE
                done9 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 1:
            switch try r.readBits(1) {
            case 0:   // element EE
                done9 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        default:
            done9 = true
        }
    }
    return CanonicalizationMethodType(algorithm: _algorithm, aNY: _aNY)
}
