// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Swift back end). Do not edit by hand.
// Schema target namespace: ExiXmlDsig

/// Opaque placeholder for the un-modelled XMLDSig element `KeyInfo`.
///
/// Only ever encoded or decoded as absent; a present instance fails loud.
public struct KeyInfo: Equatable, Sendable {
    public init() {}
}
