// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Swift back end). Do not edit by hand.
// Schema target namespace: ExiXmlDsig

import ExiRuntime

public final class SignedInfoType {
    public var id: String?
    public var canonicalizationMethod: CanonicalizationMethodType
    public var signatureMethod: SignatureMethodType
    public var reference: [ReferenceType]

    public init(id: String? = nil, canonicalizationMethod: CanonicalizationMethodType, signatureMethod: SignatureMethodType, reference: [ReferenceType]) {
        self.id = id
        self.canonicalizationMethod = canonicalizationMethod
        self.signatureMethod = signatureMethod
        self.reference = reference
    }
}

internal func encodeSignedInfoType(_ w: BitWriter, _ msg: SignedInfoType) {
    var st6 = 0
    var done6 = false
    while !done6 {
        switch st6 {
        case 0:
            if let v = msg.id {
                w.writeBits(0, 2)   // Id
                ExiPrimitives.writeStringValue(w, v)
                st6 = 1
            } else {
                w.writeBits(1, 2)   // SE(CanonicalizationMethod)
                encodeCanonicalizationMethodType(w, msg.canonicalizationMethod)
                done6 = true
            }
        case 1:
            w.writeBits(0, 1)   // SE(CanonicalizationMethod)
            encodeCanonicalizationMethodType(w, msg.canonicalizationMethod)
            done6 = true
        default:
            done6 = true
        }
    }
    w.writeBits(0, 1)   // SE
    encodeSignatureMethodType(w, msg.signatureMethod)
    let referenceList = msg.reference
    precondition((1...2147483647).contains(referenceList.count), "list size out of schema range")
    for (i, item) in referenceList.enumerated() {
        w.writeBits(0, i == 0 ? 1 : 2)   // SE(item)
        encodeReferenceType(w, item)
    }
    w.writeBits(1, 2)   // list terminator / element EE
}

internal func decodeSignedInfoType(_ r: BitReader) throws -> SignedInfoType {
    var _id: String? = nil
    var _canonicalizationMethod: CanonicalizationMethodType? = nil
    var st7 = 0
    var done7 = false
    while !done7 {
        switch st7 {
        case 0:
            switch try r.readBits(2) {
            case 0:   // Id
                _id = try ExiPrimitives.readStringValue(r, slot: "Id")
                st7 = 1
            case 1:   // SE(CanonicalizationMethod)
                _canonicalizationMethod = try decodeCanonicalizationMethodType(r)
                done7 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 1:
            switch try r.readBits(1) {
            case 0:   // SE(CanonicalizationMethod)
                _canonicalizationMethod = try decodeCanonicalizationMethodType(r)
                done7 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        default:
            done7 = true
        }
    }
    guard let _canonicalizationMethod else {
        throw ExiError.invalidEventCode("CanonicalizationMethod is required but the element ended")
    }
    _ = try r.readBits(1)   // SE
    let _signatureMethod = try decodeSignatureMethodType(r)
    var referenceList = [ReferenceType]()
    _ = try r.readBits(1)   // SE(item) first
    referenceList.append(try decodeReferenceType(r))
    while true {
        let ec = try r.readBits(2)
        if ec == 1 { break }   // element EE
        guard ec == 0, referenceList.count < 2147483647 else {
            throw ExiError.invalidEventCode("repeating element")
        }
        referenceList.append(try decodeReferenceType(r))
    }
    return SignedInfoType(id: _id, canonicalizationMethod: _canonicalizationMethod, signatureMethod: _signatureMethod, reference: referenceList)
}
