// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Kotlin back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cloud.charging.v2g.iso20.ac

import cloud.charging.v2g.exi.BitReader
import cloud.charging.v2g.exi.BitWriter

data class AC_CPDResEnergyTransferMode(
    val eVSEMaximumChargePower: RationalNumberType,
    val eVSEMaximumChargePower_L2: RationalNumberType?,
    val eVSEMaximumChargePower_L3: RationalNumberType?,
    val eVSEMinimumChargePower: RationalNumberType,
    val eVSEMinimumChargePower_L2: RationalNumberType?,
    val eVSEMinimumChargePower_L3: RationalNumberType?,
    val eVSENominalFrequency: RationalNumberType,
    val maximumPowerAsymmetry: RationalNumberType?,
    val eVSEPowerRampLimitation: RationalNumberType?,
    val eVSEPresentActivePower: RationalNumberType?,
    val eVSEPresentActivePower_L2: RationalNumberType?,
    val eVSEPresentActivePower_L3: RationalNumberType?
)

internal fun encodeAC_CPDResEnergyTransferMode(w: BitWriter, msg: AC_CPDResEnergyTransferMode) {
    w.writeBits(0u, 1)   // SE
    encodeRationalNumberType(w, msg.eVSEMaximumChargePower)
    var st110 = 0
    var done110 = false
    while (!done110) {
        when (st110) {
            0 -> {
                if (msg.eVSEMaximumChargePower_L2 != null) {
                    w.writeBits(0u, 2)   // EVSEMaximumChargePower_L2
                    encodeRationalNumberType(w, msg.eVSEMaximumChargePower_L2!!)
                    st110 = 1
                } else if (msg.eVSEMaximumChargePower_L3 != null) {
                    w.writeBits(1u, 2)   // EVSEMaximumChargePower_L3
                    encodeRationalNumberType(w, msg.eVSEMaximumChargePower_L3!!)
                    st110 = 2
                } else {
                    w.writeBits(2u, 2)   // SE(EVSEMinimumChargePower)
                    encodeRationalNumberType(w, msg.eVSEMinimumChargePower)
                    done110 = true
                }
            }
            1 -> {
                if (msg.eVSEMaximumChargePower_L3 != null) {
                    w.writeBits(0u, 2)   // EVSEMaximumChargePower_L3
                    encodeRationalNumberType(w, msg.eVSEMaximumChargePower_L3!!)
                    st110 = 2
                } else {
                    w.writeBits(1u, 2)   // SE(EVSEMinimumChargePower)
                    encodeRationalNumberType(w, msg.eVSEMinimumChargePower)
                    done110 = true
                }
            }
            2 -> {
                w.writeBits(0u, 1)   // SE(EVSEMinimumChargePower)
                encodeRationalNumberType(w, msg.eVSEMinimumChargePower)
                done110 = true
            }
        }
    }
    var st111 = 0
    var done111 = false
    while (!done111) {
        when (st111) {
            0 -> {
                if (msg.eVSEMinimumChargePower_L2 != null) {
                    w.writeBits(0u, 2)   // EVSEMinimumChargePower_L2
                    encodeRationalNumberType(w, msg.eVSEMinimumChargePower_L2!!)
                    st111 = 1
                } else if (msg.eVSEMinimumChargePower_L3 != null) {
                    w.writeBits(1u, 2)   // EVSEMinimumChargePower_L3
                    encodeRationalNumberType(w, msg.eVSEMinimumChargePower_L3!!)
                    st111 = 2
                } else {
                    w.writeBits(2u, 2)   // SE(EVSENominalFrequency)
                    encodeRationalNumberType(w, msg.eVSENominalFrequency)
                    done111 = true
                }
            }
            1 -> {
                if (msg.eVSEMinimumChargePower_L3 != null) {
                    w.writeBits(0u, 2)   // EVSEMinimumChargePower_L3
                    encodeRationalNumberType(w, msg.eVSEMinimumChargePower_L3!!)
                    st111 = 2
                } else {
                    w.writeBits(1u, 2)   // SE(EVSENominalFrequency)
                    encodeRationalNumberType(w, msg.eVSENominalFrequency)
                    done111 = true
                }
            }
            2 -> {
                w.writeBits(0u, 1)   // SE(EVSENominalFrequency)
                encodeRationalNumberType(w, msg.eVSENominalFrequency)
                done111 = true
            }
        }
    }
    var st112 = 0
    var done112 = false
    while (!done112) {
        when (st112) {
            0 -> {
                if (msg.maximumPowerAsymmetry != null) {
                    w.writeBits(0u, 3)   // MaximumPowerAsymmetry
                    encodeRationalNumberType(w, msg.maximumPowerAsymmetry!!)
                    st112 = 1
                } else if (msg.eVSEPowerRampLimitation != null) {
                    w.writeBits(1u, 3)   // EVSEPowerRampLimitation
                    encodeRationalNumberType(w, msg.eVSEPowerRampLimitation!!)
                    st112 = 2
                } else if (msg.eVSEPresentActivePower != null) {
                    w.writeBits(2u, 3)   // EVSEPresentActivePower
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower!!)
                    st112 = 3
                } else if (msg.eVSEPresentActivePower_L2 != null) {
                    w.writeBits(3u, 3)   // EVSEPresentActivePower_L2
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower_L2!!)
                    st112 = 4
                } else if (msg.eVSEPresentActivePower_L3 != null) {
                    w.writeBits(4u, 3)   // EVSEPresentActivePower_L3
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower_L3!!)
                    st112 = 5
                } else {
                    w.writeBits(5u, 3)   // element EE
                    done112 = true
                }
            }
            1 -> {
                if (msg.eVSEPowerRampLimitation != null) {
                    w.writeBits(0u, 3)   // EVSEPowerRampLimitation
                    encodeRationalNumberType(w, msg.eVSEPowerRampLimitation!!)
                    st112 = 2
                } else if (msg.eVSEPresentActivePower != null) {
                    w.writeBits(1u, 3)   // EVSEPresentActivePower
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower!!)
                    st112 = 3
                } else if (msg.eVSEPresentActivePower_L2 != null) {
                    w.writeBits(2u, 3)   // EVSEPresentActivePower_L2
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower_L2!!)
                    st112 = 4
                } else if (msg.eVSEPresentActivePower_L3 != null) {
                    w.writeBits(3u, 3)   // EVSEPresentActivePower_L3
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower_L3!!)
                    st112 = 5
                } else {
                    w.writeBits(4u, 3)   // element EE
                    done112 = true
                }
            }
            2 -> {
                if (msg.eVSEPresentActivePower != null) {
                    w.writeBits(0u, 3)   // EVSEPresentActivePower
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower!!)
                    st112 = 3
                } else if (msg.eVSEPresentActivePower_L2 != null) {
                    w.writeBits(1u, 3)   // EVSEPresentActivePower_L2
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower_L2!!)
                    st112 = 4
                } else if (msg.eVSEPresentActivePower_L3 != null) {
                    w.writeBits(2u, 3)   // EVSEPresentActivePower_L3
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower_L3!!)
                    st112 = 5
                } else {
                    w.writeBits(3u, 3)   // element EE
                    done112 = true
                }
            }
            3 -> {
                if (msg.eVSEPresentActivePower_L2 != null) {
                    w.writeBits(0u, 2)   // EVSEPresentActivePower_L2
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower_L2!!)
                    st112 = 4
                } else if (msg.eVSEPresentActivePower_L3 != null) {
                    w.writeBits(1u, 2)   // EVSEPresentActivePower_L3
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower_L3!!)
                    st112 = 5
                } else {
                    w.writeBits(2u, 2)   // element EE
                    done112 = true
                }
            }
            4 -> {
                if (msg.eVSEPresentActivePower_L3 != null) {
                    w.writeBits(0u, 2)   // EVSEPresentActivePower_L3
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower_L3!!)
                    st112 = 5
                } else {
                    w.writeBits(1u, 2)   // element EE
                    done112 = true
                }
            }
            5 -> {
                w.writeBits(0u, 1)   // element EE
                done112 = true
            }
        }
    }
}

internal fun decodeAC_CPDResEnergyTransferMode(r: BitReader): AC_CPDResEnergyTransferMode {
    r.readBits(1)   // SE
    val _eVSEMaximumChargePower = decodeRationalNumberType(r)
    var _eVSEMaximumChargePower_L2: RationalNumberType? = null
    var _eVSEMaximumChargePower_L3: RationalNumberType? = null
    var _eVSEMinimumChargePower: RationalNumberType? = null
    var st113 = 0
    var done113 = false
    while (!done113) {
        when (st113) {
            0 -> {
                when (r.readBits(2)) {
                    0u -> {
                        _eVSEMaximumChargePower_L2 = decodeRationalNumberType(r)
                        st113 = 1
                    }
                    1u -> {
                        _eVSEMaximumChargePower_L3 = decodeRationalNumberType(r)
                        st113 = 2
                    }
                    2u -> {   // SE(EVSEMinimumChargePower)
                        _eVSEMinimumChargePower = decodeRationalNumberType(r)
                        done113 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            1 -> {
                when (r.readBits(2)) {
                    0u -> {
                        _eVSEMaximumChargePower_L3 = decodeRationalNumberType(r)
                        st113 = 2
                    }
                    1u -> {   // SE(EVSEMinimumChargePower)
                        _eVSEMinimumChargePower = decodeRationalNumberType(r)
                        done113 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            2 -> {
                when (r.readBits(1)) {
                    0u -> {   // SE(EVSEMinimumChargePower)
                        _eVSEMinimumChargePower = decodeRationalNumberType(r)
                        done113 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
        }
    }
    var _eVSEMinimumChargePower_L2: RationalNumberType? = null
    var _eVSEMinimumChargePower_L3: RationalNumberType? = null
    var _eVSENominalFrequency: RationalNumberType? = null
    var st114 = 0
    var done114 = false
    while (!done114) {
        when (st114) {
            0 -> {
                when (r.readBits(2)) {
                    0u -> {
                        _eVSEMinimumChargePower_L2 = decodeRationalNumberType(r)
                        st114 = 1
                    }
                    1u -> {
                        _eVSEMinimumChargePower_L3 = decodeRationalNumberType(r)
                        st114 = 2
                    }
                    2u -> {   // SE(EVSENominalFrequency)
                        _eVSENominalFrequency = decodeRationalNumberType(r)
                        done114 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            1 -> {
                when (r.readBits(2)) {
                    0u -> {
                        _eVSEMinimumChargePower_L3 = decodeRationalNumberType(r)
                        st114 = 2
                    }
                    1u -> {   // SE(EVSENominalFrequency)
                        _eVSENominalFrequency = decodeRationalNumberType(r)
                        done114 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            2 -> {
                when (r.readBits(1)) {
                    0u -> {   // SE(EVSENominalFrequency)
                        _eVSENominalFrequency = decodeRationalNumberType(r)
                        done114 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
        }
    }
    var _maximumPowerAsymmetry: RationalNumberType? = null
    var _eVSEPowerRampLimitation: RationalNumberType? = null
    var _eVSEPresentActivePower: RationalNumberType? = null
    var _eVSEPresentActivePower_L2: RationalNumberType? = null
    var _eVSEPresentActivePower_L3: RationalNumberType? = null
    var st115 = 0
    var done115 = false
    while (!done115) {
        when (st115) {
            0 -> {
                when (r.readBits(3)) {
                    0u -> {
                        _maximumPowerAsymmetry = decodeRationalNumberType(r)
                        st115 = 1
                    }
                    1u -> {
                        _eVSEPowerRampLimitation = decodeRationalNumberType(r)
                        st115 = 2
                    }
                    2u -> {
                        _eVSEPresentActivePower = decodeRationalNumberType(r)
                        st115 = 3
                    }
                    3u -> {
                        _eVSEPresentActivePower_L2 = decodeRationalNumberType(r)
                        st115 = 4
                    }
                    4u -> {
                        _eVSEPresentActivePower_L3 = decodeRationalNumberType(r)
                        st115 = 5
                    }
                    5u -> done115 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            1 -> {
                when (r.readBits(3)) {
                    0u -> {
                        _eVSEPowerRampLimitation = decodeRationalNumberType(r)
                        st115 = 2
                    }
                    1u -> {
                        _eVSEPresentActivePower = decodeRationalNumberType(r)
                        st115 = 3
                    }
                    2u -> {
                        _eVSEPresentActivePower_L2 = decodeRationalNumberType(r)
                        st115 = 4
                    }
                    3u -> {
                        _eVSEPresentActivePower_L3 = decodeRationalNumberType(r)
                        st115 = 5
                    }
                    4u -> done115 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            2 -> {
                when (r.readBits(3)) {
                    0u -> {
                        _eVSEPresentActivePower = decodeRationalNumberType(r)
                        st115 = 3
                    }
                    1u -> {
                        _eVSEPresentActivePower_L2 = decodeRationalNumberType(r)
                        st115 = 4
                    }
                    2u -> {
                        _eVSEPresentActivePower_L3 = decodeRationalNumberType(r)
                        st115 = 5
                    }
                    3u -> done115 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            3 -> {
                when (r.readBits(2)) {
                    0u -> {
                        _eVSEPresentActivePower_L2 = decodeRationalNumberType(r)
                        st115 = 4
                    }
                    1u -> {
                        _eVSEPresentActivePower_L3 = decodeRationalNumberType(r)
                        st115 = 5
                    }
                    2u -> done115 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            4 -> {
                when (r.readBits(2)) {
                    0u -> {
                        _eVSEPresentActivePower_L3 = decodeRationalNumberType(r)
                        st115 = 5
                    }
                    1u -> done115 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            5 -> {
                when (r.readBits(1)) {
                    0u -> done115 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
        }
    }
    return AC_CPDResEnergyTransferMode(_eVSEMaximumChargePower, _eVSEMaximumChargePower_L2, _eVSEMaximumChargePower_L3, _eVSEMinimumChargePower!!, _eVSEMinimumChargePower_L2, _eVSEMinimumChargePower_L3, _eVSENominalFrequency!!, _maximumPowerAsymmetry, _eVSEPowerRampLimitation, _eVSEPresentActivePower, _eVSEPresentActivePower_L2, _eVSEPresentActivePower_L3)
}
