// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Kotlin back end). Do not edit by hand.

package cloud.charging.v2g.iso20.ac

import cloud.charging.v2g.exi.BitReader
import cloud.charging.v2g.exi.BitWriter

class AC_ChargeParameterDiscoveryReq(
    override val header: MessageHeaderType,
    val aC_CPDReqEnergyTransferMode: AC_CPDReqEnergyTransferModeType
) : ChargeParameterDiscoveryReqType(header)

internal fun encodeAC_ChargeParameterDiscoveryReq(w: BitWriter, msg: AC_ChargeParameterDiscoveryReq) {
    w.writeBits(0u, 1)   // SE
    encodeMessageHeaderType(w, msg.header)
    when (val v = msg.aC_CPDReqEnergyTransferMode) {
        is BPT_AC_CPDReqEnergyTransferModeType -> {
            w.writeBits(1u, 2)   // BPT_AC_CPDReqEnergyTransferMode
            encodeBPT_AC_CPDReqEnergyTransferModeType(w, v)
        }
        else -> {
            require(v::class == AC_CPDReqEnergyTransferModeType::class) { "AC_CPDReqEnergyTransferMode: ${v::class.simpleName} is not a substitution member" }
            w.writeBits(0u, 2)   // AC_CPDReqEnergyTransferMode
            encodeAC_CPDReqEnergyTransferModeType(w, v)
        }
    }
    w.writeBits(0u, 1)   // element EE
}

internal fun decodeAC_ChargeParameterDiscoveryReq(r: BitReader): AC_ChargeParameterDiscoveryReq {
    r.readBits(1)   // SE
    val _header = decodeMessageHeaderType(r)
    val _aC_CPDReqEnergyTransferMode: AC_CPDReqEnergyTransferModeType = when (r.readBits(2)) {
        0u -> decodeAC_CPDReqEnergyTransferModeType(r)
        1u -> decodeBPT_AC_CPDReqEnergyTransferModeType(r)
        else -> throw IllegalArgumentException("unknown substitution index")
    }
    r.readBits(1)   // element EE
    return AC_ChargeParameterDiscoveryReq(_header, _aC_CPDReqEnergyTransferMode)
}
