// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Kotlin back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cloud.charging.v2g.iso20.ac

import cloud.charging.v2g.exi.BitReader
import cloud.charging.v2g.exi.BitWriter
import cloud.charging.v2g.exi.ExiPrimitives

data class ReferenceType(
    val id: String?,
    val type: String?,
    val uRI: String?,
    val transforms: TransformsType?,
    val digestMethod: DigestMethodType,
    val digestValue: ByteArray
)

internal fun encodeReferenceType(w: BitWriter, msg: ReferenceType) {
    var st96 = 0
    var done96 = false
    while (!done96) {
        when (st96) {
            0 -> {
                if (msg.id != null) {
                    w.writeBits(0u, 3)   // Id
                    ExiPrimitives.writeStringValue(w, msg.id!!)
                    st96 = 1
                } else if (msg.type != null) {
                    w.writeBits(1u, 3)   // Type
                    ExiPrimitives.writeStringValue(w, msg.type!!)
                    st96 = 2
                } else if (msg.uRI != null) {
                    w.writeBits(2u, 3)   // URI
                    ExiPrimitives.writeStringValue(w, msg.uRI!!)
                    st96 = 3
                } else if (msg.transforms != null) {
                    w.writeBits(3u, 3)   // Transforms
                    encodeTransformsType(w, msg.transforms!!)
                    st96 = 4
                } else {
                    w.writeBits(4u, 3)   // SE(DigestMethod)
                    encodeDigestMethodType(w, msg.digestMethod)
                    done96 = true
                }
            }
            1 -> {
                if (msg.type != null) {
                    w.writeBits(0u, 3)   // Type
                    ExiPrimitives.writeStringValue(w, msg.type!!)
                    st96 = 2
                } else if (msg.uRI != null) {
                    w.writeBits(1u, 3)   // URI
                    ExiPrimitives.writeStringValue(w, msg.uRI!!)
                    st96 = 3
                } else if (msg.transforms != null) {
                    w.writeBits(2u, 3)   // Transforms
                    encodeTransformsType(w, msg.transforms!!)
                    st96 = 4
                } else {
                    w.writeBits(3u, 3)   // SE(DigestMethod)
                    encodeDigestMethodType(w, msg.digestMethod)
                    done96 = true
                }
            }
            2 -> {
                if (msg.uRI != null) {
                    w.writeBits(0u, 2)   // URI
                    ExiPrimitives.writeStringValue(w, msg.uRI!!)
                    st96 = 3
                } else if (msg.transforms != null) {
                    w.writeBits(1u, 2)   // Transforms
                    encodeTransformsType(w, msg.transforms!!)
                    st96 = 4
                } else {
                    w.writeBits(2u, 2)   // SE(DigestMethod)
                    encodeDigestMethodType(w, msg.digestMethod)
                    done96 = true
                }
            }
            3 -> {
                if (msg.transforms != null) {
                    w.writeBits(0u, 2)   // Transforms
                    encodeTransformsType(w, msg.transforms!!)
                    st96 = 4
                } else {
                    w.writeBits(1u, 2)   // SE(DigestMethod)
                    encodeDigestMethodType(w, msg.digestMethod)
                    done96 = true
                }
            }
            4 -> {
                w.writeBits(0u, 1)   // SE(DigestMethod)
                encodeDigestMethodType(w, msg.digestMethod)
                done96 = true
            }
        }
    }
    w.writeBits(0u, 1)   // SE
    w.writeBits(0u, 1)   // value-start
    ExiPrimitives.writeBinary(w, msg.digestValue)
    w.writeBits(0u, 1)   // child EE
    w.writeBits(0u, 1)   // element EE
}

internal fun decodeReferenceType(r: BitReader): ReferenceType {
    var _id: String? = null
    var _type: String? = null
    var _uRI: String? = null
    var _transforms: TransformsType? = null
    var _digestMethod: DigestMethodType? = null
    var st97 = 0
    var done97 = false
    while (!done97) {
        when (st97) {
            0 -> {
                when (r.readBits(3)) {
                    0u -> {
                        _id = ExiPrimitives.readStringValue(r, "Id")
                        st97 = 1
                    }
                    1u -> {
                        _type = ExiPrimitives.readStringValue(r, "Type")
                        st97 = 2
                    }
                    2u -> {
                        _uRI = ExiPrimitives.readStringValue(r, "URI")
                        st97 = 3
                    }
                    3u -> {
                        _transforms = decodeTransformsType(r)
                        st97 = 4
                    }
                    4u -> {   // SE(DigestMethod)
                        _digestMethod = decodeDigestMethodType(r)
                        done97 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            1 -> {
                when (r.readBits(3)) {
                    0u -> {
                        _type = ExiPrimitives.readStringValue(r, "Type")
                        st97 = 2
                    }
                    1u -> {
                        _uRI = ExiPrimitives.readStringValue(r, "URI")
                        st97 = 3
                    }
                    2u -> {
                        _transforms = decodeTransformsType(r)
                        st97 = 4
                    }
                    3u -> {   // SE(DigestMethod)
                        _digestMethod = decodeDigestMethodType(r)
                        done97 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            2 -> {
                when (r.readBits(2)) {
                    0u -> {
                        _uRI = ExiPrimitives.readStringValue(r, "URI")
                        st97 = 3
                    }
                    1u -> {
                        _transforms = decodeTransformsType(r)
                        st97 = 4
                    }
                    2u -> {   // SE(DigestMethod)
                        _digestMethod = decodeDigestMethodType(r)
                        done97 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            3 -> {
                when (r.readBits(2)) {
                    0u -> {
                        _transforms = decodeTransformsType(r)
                        st97 = 4
                    }
                    1u -> {   // SE(DigestMethod)
                        _digestMethod = decodeDigestMethodType(r)
                        done97 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            4 -> {
                when (r.readBits(1)) {
                    0u -> {   // SE(DigestMethod)
                        _digestMethod = decodeDigestMethodType(r)
                        done97 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
        }
    }
    r.readBits(1)   // SE
    r.readBits(1)   // value-start
    val _digestValue = ExiPrimitives.readBinary(r)
    r.readBits(1)   // child EE
    r.readBits(1)   // element EE
    return ReferenceType(_id, _type, _uRI, _transforms, _digestMethod!!, _digestValue)
}
