// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Kotlin back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cloud.charging.v2g.iso20.ac

import cloud.charging.v2g.exi.BitReader
import cloud.charging.v2g.exi.BitWriter
import cloud.charging.v2g.exi.ExiPrimitives

data class SignatureType(
    val id: String?,
    val signedInfo: SignedInfoType,
    val signatureValue: SignatureValueType,
    val keyInfo: KeyInfo?,
    val `object`: Object?
)

internal fun encodeSignatureType(w: BitWriter, msg: SignatureType) {
    var st84 = 0
    var done84 = false
    while (!done84) {
        when (st84) {
            0 -> {
                if (msg.id != null) {
                    w.writeBits(0u, 2)   // Id
                    ExiPrimitives.writeStringValue(w, msg.id!!)
                    st84 = 1
                } else {
                    w.writeBits(1u, 2)   // SE(SignedInfo)
                    encodeSignedInfoType(w, msg.signedInfo)
                    done84 = true
                }
            }
            1 -> {
                w.writeBits(0u, 1)   // SE(SignedInfo)
                encodeSignedInfoType(w, msg.signedInfo)
                done84 = true
            }
        }
    }
    w.writeBits(0u, 1)   // SE
    encodeSignatureValueType(w, msg.signatureValue)
    var st85 = 0
    var done85 = false
    while (!done85) {
        when (st85) {
            0 -> {
                if (msg.keyInfo != null) {
                    w.writeBits(0u, 2)   // KeyInfo
                    throw UnsupportedOperationException("Encoding a present KeyInfo (XMLDSig) is not implemented in the Kotlin back end.")
                    st85 = 1
                } else if (msg.`object` != null) {
                    w.writeBits(1u, 2)   // Object
                    throw UnsupportedOperationException("Encoding a present Object (XMLDSig) is not implemented in the Kotlin back end.")
                    st85 = 2
                } else {
                    w.writeBits(2u, 2)   // element EE
                    done85 = true
                }
            }
            1 -> {
                if (msg.`object` != null) {
                    w.writeBits(0u, 2)   // Object
                    throw UnsupportedOperationException("Encoding a present Object (XMLDSig) is not implemented in the Kotlin back end.")
                    st85 = 2
                } else {
                    w.writeBits(1u, 2)   // element EE
                    done85 = true
                }
            }
            2 -> {
                w.writeBits(0u, 1)   // element EE
                done85 = true
            }
        }
    }
}

internal fun decodeSignatureType(r: BitReader): SignatureType {
    var _id: String? = null
    var _signedInfo: SignedInfoType? = null
    var st86 = 0
    var done86 = false
    while (!done86) {
        when (st86) {
            0 -> {
                when (r.readBits(2)) {
                    0u -> {
                        _id = ExiPrimitives.readStringValue(r, "Id")
                        st86 = 1
                    }
                    1u -> {   // SE(SignedInfo)
                        _signedInfo = decodeSignedInfoType(r)
                        done86 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            1 -> {
                when (r.readBits(1)) {
                    0u -> {   // SE(SignedInfo)
                        _signedInfo = decodeSignedInfoType(r)
                        done86 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
        }
    }
    r.readBits(1)   // SE
    val _signatureValue = decodeSignatureValueType(r)
    var _keyInfo: KeyInfo? = null
    var _object: Object? = null
    var st87 = 0
    var done87 = false
    while (!done87) {
        when (st87) {
            0 -> {
                when (r.readBits(2)) {
                    0u -> {
                        _keyInfo = throw UnsupportedOperationException("Decoding a present KeyInfo (XMLDSig) is not implemented in the Kotlin back end.")
                        st87 = 1
                    }
                    1u -> {
                        _object = throw UnsupportedOperationException("Decoding a present Object (XMLDSig) is not implemented in the Kotlin back end.")
                        st87 = 2
                    }
                    2u -> done87 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            1 -> {
                when (r.readBits(2)) {
                    0u -> {
                        _object = throw UnsupportedOperationException("Decoding a present Object (XMLDSig) is not implemented in the Kotlin back end.")
                        st87 = 2
                    }
                    1u -> done87 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            2 -> {
                when (r.readBits(1)) {
                    0u -> done87 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
        }
    }
    return SignatureType(_id, _signedInfo!!, _signatureValue, _keyInfo, _object)
}
