// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Swift back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import ExiRuntime

internal func toJSONBPT_Scheduled_DC_CLReqControlModeType(_ value: BPT_Scheduled_DC_CLReqControlModeType) throws -> JsonObject {

    let json = JsonObject()

    json["@type"] = JsonValue.of("BPT_Scheduled_DC_CLReqControlModeType")

    if let v = value.eVTargetEnergyRequest {
        json["evTargetEnergyRequest"] = try DCCodecJson.toJSON(v)
    }

    if let v = value.eVMaximumEnergyRequest {
        json["evMaximumEnergyRequest"] = try DCCodecJson.toJSON(v)
    }

    if let v = value.eVMinimumEnergyRequest {
        json["evMinimumEnergyRequest"] = try DCCodecJson.toJSON(v)
    }

    json["evTargetCurrent"] = try DCCodecJson.toJSON(value.eVTargetCurrent)
    json["evTargetVoltage"] = try DCCodecJson.toJSON(value.eVTargetVoltage)
    if let v = value.eVMaximumChargePower {
        json["evMaximumChargePower"] = try DCCodecJson.toJSON(v)
    }

    if let v = value.eVMinimumChargePower {
        json["evMinimumChargePower"] = try DCCodecJson.toJSON(v)
    }

    if let v = value.eVMaximumChargeCurrent {
        json["evMaximumChargeCurrent"] = try DCCodecJson.toJSON(v)
    }

    if let v = value.eVMaximumVoltage {
        json["evMaximumVoltage"] = try DCCodecJson.toJSON(v)
    }

    if let v = value.eVMinimumVoltage {
        json["evMinimumVoltage"] = try DCCodecJson.toJSON(v)
    }

    if let v = value.eVMaximumDischargePower {
        json["evMaximumDischargePower"] = try DCCodecJson.toJSON(v)
    }

    if let v = value.eVMinimumDischargePower {
        json["evMinimumDischargePower"] = try DCCodecJson.toJSON(v)
    }

    if let v = value.eVMaximumDischargeCurrent {
        json["evMaximumDischargeCurrent"] = try DCCodecJson.toJSON(v)
    }

    return json
}

internal func parseJSONBPT_Scheduled_DC_CLReqControlModeType(_ json: JsonObject) throws -> BPT_Scheduled_DC_CLReqControlModeType {

    return BPT_Scheduled_DC_CLReqControlModeType(
        eVTargetEnergyRequest: try JsonPrimitives.optional(json, "evTargetEnergyRequest").map { try JsonPrimitives.cast(DCCodecJson.parseJSON($0, "BPT_Scheduled_DC_CLReqControlModeType.evTargetEnergyRequest"), "evTargetEnergyRequest", "BPT_Scheduled_DC_CLReqControlModeType") as RationalNumberType },
        eVMaximumEnergyRequest: try JsonPrimitives.optional(json, "evMaximumEnergyRequest").map { try JsonPrimitives.cast(DCCodecJson.parseJSON($0, "BPT_Scheduled_DC_CLReqControlModeType.evMaximumEnergyRequest"), "evMaximumEnergyRequest", "BPT_Scheduled_DC_CLReqControlModeType") as RationalNumberType },
        eVMinimumEnergyRequest: try JsonPrimitives.optional(json, "evMinimumEnergyRequest").map { try JsonPrimitives.cast(DCCodecJson.parseJSON($0, "BPT_Scheduled_DC_CLReqControlModeType.evMinimumEnergyRequest"), "evMinimumEnergyRequest", "BPT_Scheduled_DC_CLReqControlModeType") as RationalNumberType },
        eVTargetCurrent: try JsonPrimitives.cast(DCCodecJson.parseJSON(try JsonPrimitives.required(json, "evTargetCurrent", "BPT_Scheduled_DC_CLReqControlModeType"), "BPT_Scheduled_DC_CLReqControlModeType.evTargetCurrent"), "evTargetCurrent", "BPT_Scheduled_DC_CLReqControlModeType") as RationalNumberType,
        eVTargetVoltage: try JsonPrimitives.cast(DCCodecJson.parseJSON(try JsonPrimitives.required(json, "evTargetVoltage", "BPT_Scheduled_DC_CLReqControlModeType"), "BPT_Scheduled_DC_CLReqControlModeType.evTargetVoltage"), "evTargetVoltage", "BPT_Scheduled_DC_CLReqControlModeType") as RationalNumberType,
        eVMaximumChargePower: try JsonPrimitives.optional(json, "evMaximumChargePower").map { try JsonPrimitives.cast(DCCodecJson.parseJSON($0, "BPT_Scheduled_DC_CLReqControlModeType.evMaximumChargePower"), "evMaximumChargePower", "BPT_Scheduled_DC_CLReqControlModeType") as RationalNumberType },
        eVMinimumChargePower: try JsonPrimitives.optional(json, "evMinimumChargePower").map { try JsonPrimitives.cast(DCCodecJson.parseJSON($0, "BPT_Scheduled_DC_CLReqControlModeType.evMinimumChargePower"), "evMinimumChargePower", "BPT_Scheduled_DC_CLReqControlModeType") as RationalNumberType },
        eVMaximumChargeCurrent: try JsonPrimitives.optional(json, "evMaximumChargeCurrent").map { try JsonPrimitives.cast(DCCodecJson.parseJSON($0, "BPT_Scheduled_DC_CLReqControlModeType.evMaximumChargeCurrent"), "evMaximumChargeCurrent", "BPT_Scheduled_DC_CLReqControlModeType") as RationalNumberType },
        eVMaximumVoltage: try JsonPrimitives.optional(json, "evMaximumVoltage").map { try JsonPrimitives.cast(DCCodecJson.parseJSON($0, "BPT_Scheduled_DC_CLReqControlModeType.evMaximumVoltage"), "evMaximumVoltage", "BPT_Scheduled_DC_CLReqControlModeType") as RationalNumberType },
        eVMinimumVoltage: try JsonPrimitives.optional(json, "evMinimumVoltage").map { try JsonPrimitives.cast(DCCodecJson.parseJSON($0, "BPT_Scheduled_DC_CLReqControlModeType.evMinimumVoltage"), "evMinimumVoltage", "BPT_Scheduled_DC_CLReqControlModeType") as RationalNumberType },
        eVMaximumDischargePower: try JsonPrimitives.optional(json, "evMaximumDischargePower").map { try JsonPrimitives.cast(DCCodecJson.parseJSON($0, "BPT_Scheduled_DC_CLReqControlModeType.evMaximumDischargePower"), "evMaximumDischargePower", "BPT_Scheduled_DC_CLReqControlModeType") as RationalNumberType },
        eVMinimumDischargePower: try JsonPrimitives.optional(json, "evMinimumDischargePower").map { try JsonPrimitives.cast(DCCodecJson.parseJSON($0, "BPT_Scheduled_DC_CLReqControlModeType.evMinimumDischargePower"), "evMinimumDischargePower", "BPT_Scheduled_DC_CLReqControlModeType") as RationalNumberType },
        eVMaximumDischargeCurrent: try JsonPrimitives.optional(json, "evMaximumDischargeCurrent").map { try JsonPrimitives.cast(DCCodecJson.parseJSON($0, "BPT_Scheduled_DC_CLReqControlModeType.evMaximumDischargeCurrent"), "evMaximumDischargeCurrent", "BPT_Scheduled_DC_CLReqControlModeType") as RationalNumberType }
    )
}

