// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Swift back end). Do not edit by hand.

import ExiRuntime

internal func toJSONDC_PreChargeRes(_ value: DC_PreChargeRes) throws -> JsonObject {

    let json = JsonObject()

    json["@context"] = JsonValue.of(DCCodecJson.context)
    json["@type"] = JsonValue.of("DC_PreChargeRes")

    json["header"] = try DCCodecJson.toJSON(value.header)
    json["responseCode"] = JsonValue.of(JsonPrimitives.fromEnumeration(value.responseCode))
    json["evsePresentVoltage"] = try DCCodecJson.toJSON(value.eVSEPresentVoltage)
    return json
}

internal func parseJSONDC_PreChargeRes(_ json: JsonObject) throws -> DC_PreChargeRes {

    return DC_PreChargeRes(
        header: try JsonPrimitives.cast(DCCodecJson.parseJSON(try JsonPrimitives.required(json, "header", "DC_PreChargeRes"), "DC_PreChargeRes.header"), "header", "DC_PreChargeRes") as MessageHeaderType,
        responseCode: try JsonPrimitives.enumeration(try JsonPrimitives.required(json, "responseCode", "DC_PreChargeRes"), "responseCode", "DC_PreChargeRes", ResponseCode.self),
        eVSEPresentVoltage: try JsonPrimitives.cast(DCCodecJson.parseJSON(try JsonPrimitives.required(json, "evsePresentVoltage", "DC_PreChargeRes"), "DC_PreChargeRes.evsePresentVoltage"), "evsePresentVoltage", "DC_PreChargeRes") as RationalNumberType
    )
}

