// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Swift back end). Do not edit by hand.
// Schema target namespace: cloud.charging.v2g.iso20.dc

import ExiRuntime

public final class ReceiptType {
    public var timeAnchor: UInt64
    public var energyCosts: DetailedCostType?
    public var occupancyCosts: DetailedCostType?
    public var additionalServicesCosts: DetailedCostType?
    public var overstayCosts: DetailedCostType?
    public var taxCosts: [DetailedTaxType]

    public init(timeAnchor: UInt64, energyCosts: DetailedCostType? = nil, occupancyCosts: DetailedCostType? = nil, additionalServicesCosts: DetailedCostType? = nil, overstayCosts: DetailedCostType? = nil, taxCosts: [DetailedTaxType]) {
        self.timeAnchor = timeAnchor
        self.energyCosts = energyCosts
        self.occupancyCosts = occupancyCosts
        self.additionalServicesCosts = additionalServicesCosts
        self.overstayCosts = overstayCosts
        self.taxCosts = taxCosts
    }
}

internal func encodeReceiptType(_ w: BitWriter, _ msg: ReceiptType) {
    w.writeBits(0, 1)   // SE
    w.writeBits(0, 1)   // value-start
    ExiPrimitives.writeUnsignedInteger(w, UInt64(msg.timeAnchor))
    w.writeBits(0, 1)   // child EE
    var st40 = 0
    var done40 = false
    while !done40 {
        switch st40 {
        case 0:
            if let v = msg.energyCosts {
                w.writeBits(0, 3)   // EnergyCosts
                encodeDetailedCostType(w, v)
                st40 = 1
            } else if let v = msg.occupancyCosts {
                w.writeBits(1, 3)   // OccupancyCosts
                encodeDetailedCostType(w, v)
                st40 = 2
            } else if let v = msg.additionalServicesCosts {
                w.writeBits(2, 3)   // AdditionalServicesCosts
                encodeDetailedCostType(w, v)
                st40 = 3
            } else if let v = msg.overstayCosts {
                w.writeBits(3, 3)   // OverstayCosts
                encodeDetailedCostType(w, v)
                st40 = 4
            } else if !msg.taxCosts.isEmpty {
                precondition(msg.taxCosts.count <= 10, "list size out of schema range")
                w.writeBits(4, 3)   // TaxCosts
                encodeDetailedTaxType(w, msg.taxCosts[0])
                for ci in 1..<msg.taxCosts.count {
                    w.writeBits(0, 2)   // TaxCosts
                    encodeDetailedTaxType(w, msg.taxCosts[ci])
                }
                w.writeBits(1, 2)   // element EE (list end)
                done40 = true
            } else {
                w.writeBits(5, 3)   // element EE
                done40 = true
            }
        case 1:
            if let v = msg.occupancyCosts {
                w.writeBits(0, 3)   // OccupancyCosts
                encodeDetailedCostType(w, v)
                st40 = 2
            } else if let v = msg.additionalServicesCosts {
                w.writeBits(1, 3)   // AdditionalServicesCosts
                encodeDetailedCostType(w, v)
                st40 = 3
            } else if let v = msg.overstayCosts {
                w.writeBits(2, 3)   // OverstayCosts
                encodeDetailedCostType(w, v)
                st40 = 4
            } else if !msg.taxCosts.isEmpty {
                precondition(msg.taxCosts.count <= 10, "list size out of schema range")
                w.writeBits(3, 3)   // TaxCosts
                encodeDetailedTaxType(w, msg.taxCosts[0])
                for ci in 1..<msg.taxCosts.count {
                    w.writeBits(0, 2)   // TaxCosts
                    encodeDetailedTaxType(w, msg.taxCosts[ci])
                }
                w.writeBits(1, 2)   // element EE (list end)
                done40 = true
            } else {
                w.writeBits(4, 3)   // element EE
                done40 = true
            }
        case 2:
            if let v = msg.additionalServicesCosts {
                w.writeBits(0, 3)   // AdditionalServicesCosts
                encodeDetailedCostType(w, v)
                st40 = 3
            } else if let v = msg.overstayCosts {
                w.writeBits(1, 3)   // OverstayCosts
                encodeDetailedCostType(w, v)
                st40 = 4
            } else if !msg.taxCosts.isEmpty {
                precondition(msg.taxCosts.count <= 10, "list size out of schema range")
                w.writeBits(2, 3)   // TaxCosts
                encodeDetailedTaxType(w, msg.taxCosts[0])
                for ci in 1..<msg.taxCosts.count {
                    w.writeBits(0, 2)   // TaxCosts
                    encodeDetailedTaxType(w, msg.taxCosts[ci])
                }
                w.writeBits(1, 2)   // element EE (list end)
                done40 = true
            } else {
                w.writeBits(3, 3)   // element EE
                done40 = true
            }
        case 3:
            if let v = msg.overstayCosts {
                w.writeBits(0, 2)   // OverstayCosts
                encodeDetailedCostType(w, v)
                st40 = 4
            } else if !msg.taxCosts.isEmpty {
                precondition(msg.taxCosts.count <= 10, "list size out of schema range")
                w.writeBits(1, 2)   // TaxCosts
                encodeDetailedTaxType(w, msg.taxCosts[0])
                for ci in 1..<msg.taxCosts.count {
                    w.writeBits(0, 2)   // TaxCosts
                    encodeDetailedTaxType(w, msg.taxCosts[ci])
                }
                w.writeBits(1, 2)   // element EE (list end)
                done40 = true
            } else {
                w.writeBits(2, 2)   // element EE
                done40 = true
            }
        case 4:
            if !msg.taxCosts.isEmpty {
                precondition(msg.taxCosts.count <= 10, "list size out of schema range")
                w.writeBits(0, 2)   // TaxCosts
                encodeDetailedTaxType(w, msg.taxCosts[0])
                for ci in 1..<msg.taxCosts.count {
                    w.writeBits(0, 2)   // TaxCosts
                    encodeDetailedTaxType(w, msg.taxCosts[ci])
                }
                w.writeBits(1, 2)   // element EE (list end)
                done40 = true
            } else {
                w.writeBits(1, 2)   // element EE
                done40 = true
            }
        case 5:
            w.writeBits(0, 1)   // element EE
            done40 = true
        default:
            done40 = true
        }
    }
}

internal func decodeReceiptType(_ r: BitReader) throws -> ReceiptType {
    _ = try r.readBits(1)   // SE
    _ = try r.readBits(1)   // value-start
    let _timeAnchor = UInt64(try ExiPrimitives.readUnsignedInteger(r))
    _ = try r.readBits(1)   // child EE
    var _energyCosts: DetailedCostType? = nil
    var _occupancyCosts: DetailedCostType? = nil
    var _additionalServicesCosts: DetailedCostType? = nil
    var _overstayCosts: DetailedCostType? = nil
    var taxCostsList = [DetailedTaxType]()
    var st41 = 0
    var done41 = false
    while !done41 {
        switch st41 {
        case 0:
            switch try r.readBits(3) {
            case 0:   // EnergyCosts
                _energyCosts = try decodeDetailedCostType(r)
                st41 = 1
            case 1:   // OccupancyCosts
                _occupancyCosts = try decodeDetailedCostType(r)
                st41 = 2
            case 2:   // AdditionalServicesCosts
                _additionalServicesCosts = try decodeDetailedCostType(r)
                st41 = 3
            case 3:   // OverstayCosts
                _overstayCosts = try decodeDetailedCostType(r)
                st41 = 4
            case 4:   // TaxCosts
                taxCostsList.append(try decodeDetailedTaxType(r))
                while true {
                    let ec = try r.readBits(2)
                    if ec == 1 { break }   // element EE (list end)
                    guard ec == 0, taxCostsList.count < 10 else {
                        throw ExiError.invalidEventCode("repeating element")
                    }
                    taxCostsList.append(try decodeDetailedTaxType(r))
                }
                done41 = true
            case 5:   // element EE
                done41 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 1:
            switch try r.readBits(3) {
            case 0:   // OccupancyCosts
                _occupancyCosts = try decodeDetailedCostType(r)
                st41 = 2
            case 1:   // AdditionalServicesCosts
                _additionalServicesCosts = try decodeDetailedCostType(r)
                st41 = 3
            case 2:   // OverstayCosts
                _overstayCosts = try decodeDetailedCostType(r)
                st41 = 4
            case 3:   // TaxCosts
                taxCostsList.append(try decodeDetailedTaxType(r))
                while true {
                    let ec = try r.readBits(2)
                    if ec == 1 { break }   // element EE (list end)
                    guard ec == 0, taxCostsList.count < 10 else {
                        throw ExiError.invalidEventCode("repeating element")
                    }
                    taxCostsList.append(try decodeDetailedTaxType(r))
                }
                done41 = true
            case 4:   // element EE
                done41 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 2:
            switch try r.readBits(3) {
            case 0:   // AdditionalServicesCosts
                _additionalServicesCosts = try decodeDetailedCostType(r)
                st41 = 3
            case 1:   // OverstayCosts
                _overstayCosts = try decodeDetailedCostType(r)
                st41 = 4
            case 2:   // TaxCosts
                taxCostsList.append(try decodeDetailedTaxType(r))
                while true {
                    let ec = try r.readBits(2)
                    if ec == 1 { break }   // element EE (list end)
                    guard ec == 0, taxCostsList.count < 10 else {
                        throw ExiError.invalidEventCode("repeating element")
                    }
                    taxCostsList.append(try decodeDetailedTaxType(r))
                }
                done41 = true
            case 3:   // element EE
                done41 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 3:
            switch try r.readBits(2) {
            case 0:   // OverstayCosts
                _overstayCosts = try decodeDetailedCostType(r)
                st41 = 4
            case 1:   // TaxCosts
                taxCostsList.append(try decodeDetailedTaxType(r))
                while true {
                    let ec = try r.readBits(2)
                    if ec == 1 { break }   // element EE (list end)
                    guard ec == 0, taxCostsList.count < 10 else {
                        throw ExiError.invalidEventCode("repeating element")
                    }
                    taxCostsList.append(try decodeDetailedTaxType(r))
                }
                done41 = true
            case 2:   // element EE
                done41 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 4:
            switch try r.readBits(2) {
            case 0:   // TaxCosts
                taxCostsList.append(try decodeDetailedTaxType(r))
                while true {
                    let ec = try r.readBits(2)
                    if ec == 1 { break }   // element EE (list end)
                    guard ec == 0, taxCostsList.count < 10 else {
                        throw ExiError.invalidEventCode("repeating element")
                    }
                    taxCostsList.append(try decodeDetailedTaxType(r))
                }
                done41 = true
            case 1:   // element EE
                done41 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 5:
            switch try r.readBits(1) {
            case 0:   // element EE
                done41 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        default:
            done41 = true
        }
    }
    return ReceiptType(timeAnchor: _timeAnchor, energyCosts: _energyCosts, occupancyCosts: _occupancyCosts, additionalServicesCosts: _additionalServicesCosts, overstayCosts: _overstayCosts, taxCosts: taxCostsList)
}
