// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Swift back end). Do not edit by hand.
// Schema target namespace: cloud.charging.v2g.iso20.dc

public enum ResponseCode: Int, CaseIterable, Sendable {
    case OK
    case OK_CertificateExpiresSoon
    case OK_NewSessionEstablished
    case OK_OldSessionJoined
    case OK_PowerToleranceConfirmed
    case WARNING_AuthorizationSelectionInvalid
    case WARNING_CertificateExpired
    case WARNING_CertificateNotYetValid
    case WARNING_CertificateRevoked
    case WARNING_CertificateValidationError
    case WARNING_ChallengeInvalid
    case WARNING_EIMAuthorizationFailure
    case WARNING_eMSPUnknown
    case WARNING_EVPowerProfileViolation
    case WARNING_GeneralPnCAuthorizationError
    case WARNING_NoCertificateAvailable
    case WARNING_NoContractMatchingPCIDFound
    case WARNING_PowerToleranceNotConfirmed
    case WARNING_ScheduleRenegotiationFailed
    case WARNING_StandbyNotAllowed
    case WARNING_WPT
    case FAILED
    case FAILED_AssociationError
    case FAILED_ContactorError
    case FAILED_EVPowerProfileInvalid
    case FAILED_EVPowerProfileViolation
    case FAILED_MeteringSignatureNotValid
    case FAILED_NoEnergyTransferServiceSelected
    case FAILED_NoServiceRenegotiationSupported
    case FAILED_PauseNotAllowed
    case FAILED_PowerDeliveryNotApplied
    case FAILED_PowerToleranceNotConfirmed
    case FAILED_ScheduleRenegotiation
    case FAILED_ScheduleSelectionInvalid
    case FAILED_SequenceError
    case FAILED_ServiceIDInvalid
    case FAILED_ServiceSelectionInvalid
    case FAILED_SignatureError
    case FAILED_UnknownSession
    case FAILED_WrongChargeParameter
}
