// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Swift back end). Do not edit by hand.
// Schema target namespace: cloud.charging.v2g.iso20.dc

import ExiRuntime

public class Scheduled_DC_CLResControlModeType: Scheduled_CLResControlModeType {
    public var eVSEMaximumChargePower: RationalNumberType?
    public var eVSEMinimumChargePower: RationalNumberType?
    public var eVSEMaximumChargeCurrent: RationalNumberType?
    public var eVSEMaximumVoltage: RationalNumberType?

    public init(eVSEMaximumChargePower: RationalNumberType? = nil, eVSEMinimumChargePower: RationalNumberType? = nil, eVSEMaximumChargeCurrent: RationalNumberType? = nil, eVSEMaximumVoltage: RationalNumberType? = nil) {
        self.eVSEMaximumChargePower = eVSEMaximumChargePower
        self.eVSEMinimumChargePower = eVSEMinimumChargePower
        self.eVSEMaximumChargeCurrent = eVSEMaximumChargeCurrent
        self.eVSEMaximumVoltage = eVSEMaximumVoltage
        super.init()
    }
}

internal func encodeScheduled_DC_CLResControlModeType(_ w: BitWriter, _ msg: Scheduled_DC_CLResControlModeType) {
    var st16 = 0
    var done16 = false
    while !done16 {
        switch st16 {
        case 0:
            if let v = msg.eVSEMaximumChargePower {
                w.writeBits(0, 3)   // EVSEMaximumChargePower
                encodeRationalNumberType(w, v)
                st16 = 1
            } else if let v = msg.eVSEMinimumChargePower {
                w.writeBits(1, 3)   // EVSEMinimumChargePower
                encodeRationalNumberType(w, v)
                st16 = 2
            } else if let v = msg.eVSEMaximumChargeCurrent {
                w.writeBits(2, 3)   // EVSEMaximumChargeCurrent
                encodeRationalNumberType(w, v)
                st16 = 3
            } else if let v = msg.eVSEMaximumVoltage {
                w.writeBits(3, 3)   // EVSEMaximumVoltage
                encodeRationalNumberType(w, v)
                st16 = 4
            } else {
                w.writeBits(4, 3)   // element EE
                done16 = true
            }
        case 1:
            if let v = msg.eVSEMinimumChargePower {
                w.writeBits(0, 3)   // EVSEMinimumChargePower
                encodeRationalNumberType(w, v)
                st16 = 2
            } else if let v = msg.eVSEMaximumChargeCurrent {
                w.writeBits(1, 3)   // EVSEMaximumChargeCurrent
                encodeRationalNumberType(w, v)
                st16 = 3
            } else if let v = msg.eVSEMaximumVoltage {
                w.writeBits(2, 3)   // EVSEMaximumVoltage
                encodeRationalNumberType(w, v)
                st16 = 4
            } else {
                w.writeBits(3, 3)   // element EE
                done16 = true
            }
        case 2:
            if let v = msg.eVSEMaximumChargeCurrent {
                w.writeBits(0, 2)   // EVSEMaximumChargeCurrent
                encodeRationalNumberType(w, v)
                st16 = 3
            } else if let v = msg.eVSEMaximumVoltage {
                w.writeBits(1, 2)   // EVSEMaximumVoltage
                encodeRationalNumberType(w, v)
                st16 = 4
            } else {
                w.writeBits(2, 2)   // element EE
                done16 = true
            }
        case 3:
            if let v = msg.eVSEMaximumVoltage {
                w.writeBits(0, 2)   // EVSEMaximumVoltage
                encodeRationalNumberType(w, v)
                st16 = 4
            } else {
                w.writeBits(1, 2)   // element EE
                done16 = true
            }
        case 4:
            w.writeBits(0, 1)   // element EE
            done16 = true
        default:
            done16 = true
        }
    }
}

internal func decodeScheduled_DC_CLResControlModeType(_ r: BitReader) throws -> Scheduled_DC_CLResControlModeType {
    var _eVSEMaximumChargePower: RationalNumberType? = nil
    var _eVSEMinimumChargePower: RationalNumberType? = nil
    var _eVSEMaximumChargeCurrent: RationalNumberType? = nil
    var _eVSEMaximumVoltage: RationalNumberType? = nil
    var st17 = 0
    var done17 = false
    while !done17 {
        switch st17 {
        case 0:
            switch try r.readBits(3) {
            case 0:   // EVSEMaximumChargePower
                _eVSEMaximumChargePower = try decodeRationalNumberType(r)
                st17 = 1
            case 1:   // EVSEMinimumChargePower
                _eVSEMinimumChargePower = try decodeRationalNumberType(r)
                st17 = 2
            case 2:   // EVSEMaximumChargeCurrent
                _eVSEMaximumChargeCurrent = try decodeRationalNumberType(r)
                st17 = 3
            case 3:   // EVSEMaximumVoltage
                _eVSEMaximumVoltage = try decodeRationalNumberType(r)
                st17 = 4
            case 4:   // element EE
                done17 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 1:
            switch try r.readBits(3) {
            case 0:   // EVSEMinimumChargePower
                _eVSEMinimumChargePower = try decodeRationalNumberType(r)
                st17 = 2
            case 1:   // EVSEMaximumChargeCurrent
                _eVSEMaximumChargeCurrent = try decodeRationalNumberType(r)
                st17 = 3
            case 2:   // EVSEMaximumVoltage
                _eVSEMaximumVoltage = try decodeRationalNumberType(r)
                st17 = 4
            case 3:   // element EE
                done17 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 2:
            switch try r.readBits(2) {
            case 0:   // EVSEMaximumChargeCurrent
                _eVSEMaximumChargeCurrent = try decodeRationalNumberType(r)
                st17 = 3
            case 1:   // EVSEMaximumVoltage
                _eVSEMaximumVoltage = try decodeRationalNumberType(r)
                st17 = 4
            case 2:   // element EE
                done17 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 3:
            switch try r.readBits(2) {
            case 0:   // EVSEMaximumVoltage
                _eVSEMaximumVoltage = try decodeRationalNumberType(r)
                st17 = 4
            case 1:   // element EE
                done17 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 4:
            switch try r.readBits(1) {
            case 0:   // element EE
                done17 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        default:
            done17 = true
        }
    }
    return Scheduled_DC_CLResControlModeType(eVSEMaximumChargePower: _eVSEMaximumChargePower, eVSEMinimumChargePower: _eVSEMinimumChargePower, eVSEMaximumChargeCurrent: _eVSEMaximumChargeCurrent, eVSEMaximumVoltage: _eVSEMaximumVoltage)
}
