// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Swift back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Schema target namespace: cloud.charging.v2g.iso20.common

import ExiRuntime

public final class EVPowerProfileType {
    public var timeAnchor: UInt64
    public var dynamic_EVPPTControlMode: Dynamic_EVPPTControlModeType?
    public var scheduled_EVPPTControlMode: Scheduled_EVPPTControlModeType?
    public var eVPowerProfileEntries: EVPowerProfileEntryListType

    public init(timeAnchor: UInt64, dynamic_EVPPTControlMode: Dynamic_EVPPTControlModeType? = nil, scheduled_EVPPTControlMode: Scheduled_EVPPTControlModeType? = nil, eVPowerProfileEntries: EVPowerProfileEntryListType) {
        self.timeAnchor = timeAnchor
        self.dynamic_EVPPTControlMode = dynamic_EVPPTControlMode
        self.scheduled_EVPPTControlMode = scheduled_EVPPTControlMode
        self.eVPowerProfileEntries = eVPowerProfileEntries
    }
}

internal func encodeEVPowerProfileType(_ w: BitWriter, _ msg: EVPowerProfileType) {
    w.writeBits(0, 1)   // SE
    w.writeBits(0, 1)   // value-start
    ExiPrimitives.writeUnsignedInteger(w, UInt64(msg.timeAnchor))
    w.writeBits(0, 1)   // child EE
    if let v = msg.dynamic_EVPPTControlMode {
        w.writeBits(0, 2)   // Dynamic_EVPPTControlMode
        encodeDynamic_EVPPTControlModeType(w, v)
    } else if let v = msg.scheduled_EVPPTControlMode {
        w.writeBits(1, 2)   // Scheduled_EVPPTControlMode
        encodeScheduled_EVPPTControlModeType(w, v)
    } else {
        preconditionFailure("no choice alternative set")
    }
    w.writeBits(0, 1)   // SE
    encodeEVPowerProfileEntryListType(w, msg.eVPowerProfileEntries)
    w.writeBits(0, 1)   // element EE
}

internal func decodeEVPowerProfileType(_ r: BitReader) throws -> EVPowerProfileType {
    _ = try r.readBits(1)   // SE
    _ = try r.readBits(1)   // value-start
    let _timeAnchor = UInt64(try ExiPrimitives.readUnsignedInteger(r))
    _ = try r.readBits(1)   // child EE
    var _dynamic_EVPPTControlMode: Dynamic_EVPPTControlModeType? = nil
    var _scheduled_EVPPTControlMode: Scheduled_EVPPTControlModeType? = nil
    switch try r.readBits(2) {
    case 0:   // Dynamic_EVPPTControlMode
        _dynamic_EVPPTControlMode = try decodeDynamic_EVPPTControlModeType(r)
    case 1:   // Scheduled_EVPPTControlMode
        _scheduled_EVPPTControlMode = try decodeScheduled_EVPPTControlModeType(r)
    default:
        throw ExiError.invalidEventCode("inline choice")
    }
    _ = try r.readBits(1)   // SE
    let _eVPowerProfileEntries = try decodeEVPowerProfileEntryListType(r)
    _ = try r.readBits(1)   // element EE
    return EVPowerProfileType(timeAnchor: _timeAnchor, dynamic_EVPPTControlMode: _dynamic_EVPPTControlMode, scheduled_EVPPTControlMode: _scheduled_EVPPTControlMode, eVPowerProfileEntries: _eVPowerProfileEntries)
}
