// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Swift back end). Do not edit by hand.

import ExiRuntime

internal func toJSONOverstayRuleListType(_ value: OverstayRuleListType) throws -> JsonObject {

    let json = JsonObject()

    json["@type"] = JsonValue.of("OverstayRuleListType")

    if let v = value.overstayTimeThreshold {
        json["overstayTimeThreshold"] = JsonValue.of(v)
    }

    if let v = value.overstayPowerThreshold {
        json["overstayPowerThreshold"] = try CommonMessagesCodecJson.toJSON(v)
    }

    let _overstayRule = JsonArray()
    for item in value.overstayRule {
        _overstayRule.add(try CommonMessagesCodecJson.toJSON(item))
    }
    json["overstayRule"] = _overstayRule

    return json
}

internal func parseJSONOverstayRuleListType(_ json: JsonObject) throws -> OverstayRuleListType {

    return OverstayRuleListType(
        overstayTimeThreshold: try JsonPrimitives.optional(json, "overstayTimeThreshold").map { try JsonPrimitives.uint32($0, "overstayTimeThreshold", "OverstayRuleListType") },
        overstayPowerThreshold: try JsonPrimitives.optional(json, "overstayPowerThreshold").map { try JsonPrimitives.cast(CommonMessagesCodecJson.parseJSON($0, "OverstayRuleListType.overstayPowerThreshold"), "overstayPowerThreshold", "OverstayRuleListType") as RationalNumberType },
        overstayRule: try JsonPrimitives.array(json, "overstayRule", "OverstayRuleListType").asList.map { try JsonPrimitives.cast(CommonMessagesCodecJson.parseJSON($0, "OverstayRuleListType.overstayRule"), "overstayRule", "OverstayRuleListType") as OverstayRuleType }
    )
}

