// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Swift back end). Do not edit by hand.

import ExiRuntime

internal func toJSONParameterSetType(_ value: ParameterSetType) throws -> JsonObject {

    let json = JsonObject()

    json["@type"] = JsonValue.of("ParameterSetType")

    json["parameterSetID"] = JsonValue.of(value.parameterSetID)
    let _parameter = JsonArray()
    for item in value.parameter {
        _parameter.add(try CommonMessagesCodecJson.toJSON(item))
    }
    json["parameter"] = _parameter

    return json
}

internal func parseJSONParameterSetType(_ json: JsonObject) throws -> ParameterSetType {

    return ParameterSetType(
        parameterSetID: try JsonPrimitives.uint16(try JsonPrimitives.required(json, "parameterSetID", "ParameterSetType"), "parameterSetID", "ParameterSetType"),
        parameter: try JsonPrimitives.array(json, "parameter", "ParameterSetType").asList.map { try JsonPrimitives.cast(CommonMessagesCodecJson.parseJSON($0, "ParameterSetType.parameter"), "parameter", "ParameterSetType") as ParameterType }
    )
}

