// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Swift back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import ExiRuntime

internal func toJSONPnC_AReqAuthorizationModeType(_ value: PnC_AReqAuthorizationModeType) throws -> JsonObject {

    let json = JsonObject()

    json["@type"] = JsonValue.of("PnC_AReqAuthorizationModeType")

    json["id"] = JsonValue.of(value.id)
    json["genChallenge"] = JsonValue.of(JsonPrimitives.toHex(value.genChallenge))
    json["contractCertificateChain"] = try CommonMessagesCodecJson.toJSON(value.contractCertificateChain)
    return json
}

internal func parseJSONPnC_AReqAuthorizationModeType(_ json: JsonObject) throws -> PnC_AReqAuthorizationModeType {

    return PnC_AReqAuthorizationModeType(
        id: try JsonPrimitives.stringValue(try JsonPrimitives.required(json, "id", "PnC_AReqAuthorizationModeType"), "id", "PnC_AReqAuthorizationModeType"),
        genChallenge: try JsonPrimitives.binary(try JsonPrimitives.required(json, "genChallenge", "PnC_AReqAuthorizationModeType"), "genChallenge", "PnC_AReqAuthorizationModeType"),
        contractCertificateChain: try JsonPrimitives.cast(CommonMessagesCodecJson.parseJSON(try JsonPrimitives.required(json, "contractCertificateChain", "PnC_AReqAuthorizationModeType"), "PnC_AReqAuthorizationModeType.contractCertificateChain"), "contractCertificateChain", "PnC_AReqAuthorizationModeType") as ContractCertificateChainType
    )
}

