// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Swift back end). Do not edit by hand.

import ExiRuntime

internal func toJSONPowerScheduleEntryType(_ value: PowerScheduleEntryType) throws -> JsonObject {

    let json = JsonObject()

    json["@type"] = JsonValue.of("PowerScheduleEntryType")

    json["duration"] = JsonValue.of(value.duration)
    json["power"] = try CommonMessagesCodecJson.toJSON(value.power)
    if let v = value.power_L2 {
        json["power_L2"] = try CommonMessagesCodecJson.toJSON(v)
    }

    if let v = value.power_L3 {
        json["power_L3"] = try CommonMessagesCodecJson.toJSON(v)
    }

    return json
}

internal func parseJSONPowerScheduleEntryType(_ json: JsonObject) throws -> PowerScheduleEntryType {

    return PowerScheduleEntryType(
        duration: try JsonPrimitives.uint32(try JsonPrimitives.required(json, "duration", "PowerScheduleEntryType"), "duration", "PowerScheduleEntryType"),
        power: try JsonPrimitives.cast(CommonMessagesCodecJson.parseJSON(try JsonPrimitives.required(json, "power", "PowerScheduleEntryType"), "PowerScheduleEntryType.power"), "power", "PowerScheduleEntryType") as RationalNumberType,
        power_L2: try JsonPrimitives.optional(json, "power_L2").map { try JsonPrimitives.cast(CommonMessagesCodecJson.parseJSON($0, "PowerScheduleEntryType.power_L2"), "power_L2", "PowerScheduleEntryType") as RationalNumberType },
        power_L3: try JsonPrimitives.optional(json, "power_L3").map { try JsonPrimitives.cast(CommonMessagesCodecJson.parseJSON($0, "PowerScheduleEntryType.power_L3"), "power_L3", "PowerScheduleEntryType") as RationalNumberType }
    )
}

