// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Swift back end). Do not edit by hand.

import ExiRuntime

internal func toJSONScheduleTupleType(_ value: ScheduleTupleType) throws -> JsonObject {

    let json = JsonObject()

    json["@type"] = JsonValue.of("ScheduleTupleType")

    json["scheduleTupleID"] = JsonValue.of(value.scheduleTupleID)
    json["chargingSchedule"] = try CommonMessagesCodecJson.toJSON(value.chargingSchedule)
    if let v = value.dischargingSchedule {
        json["dischargingSchedule"] = try CommonMessagesCodecJson.toJSON(v)
    }

    return json
}

internal func parseJSONScheduleTupleType(_ json: JsonObject) throws -> ScheduleTupleType {

    return ScheduleTupleType(
        scheduleTupleID: try JsonPrimitives.uint32(try JsonPrimitives.required(json, "scheduleTupleID", "ScheduleTupleType"), "scheduleTupleID", "ScheduleTupleType"),
        chargingSchedule: try JsonPrimitives.cast(CommonMessagesCodecJson.parseJSON(try JsonPrimitives.required(json, "chargingSchedule", "ScheduleTupleType"), "ScheduleTupleType.chargingSchedule"), "chargingSchedule", "ScheduleTupleType") as ChargingScheduleType,
        dischargingSchedule: try JsonPrimitives.optional(json, "dischargingSchedule").map { try JsonPrimitives.cast(CommonMessagesCodecJson.parseJSON($0, "ScheduleTupleType.dischargingSchedule"), "dischargingSchedule", "ScheduleTupleType") as ChargingScheduleType }
    )
}

