// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Swift back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import ExiRuntime

internal func toJSONServiceDiscoveryReq(_ value: ServiceDiscoveryReq) throws -> JsonObject {

    let json = JsonObject()

    json["@context"] = JsonValue.of(CommonMessagesCodecJson.context)
    json["@type"] = JsonValue.of("ServiceDiscoveryReq")

    json["header"] = try CommonMessagesCodecJson.toJSON(value.header)
    if let v = value.supportedServiceIDs {
        json["supportedServiceIDs"] = try CommonMessagesCodecJson.toJSON(v)
    }

    return json
}

internal func parseJSONServiceDiscoveryReq(_ json: JsonObject) throws -> ServiceDiscoveryReq {

    return ServiceDiscoveryReq(
        header: try JsonPrimitives.cast(CommonMessagesCodecJson.parseJSON(try JsonPrimitives.required(json, "header", "ServiceDiscoveryReq"), "ServiceDiscoveryReq.header"), "header", "ServiceDiscoveryReq") as MessageHeaderType,
        supportedServiceIDs: try JsonPrimitives.optional(json, "supportedServiceIDs").map { try JsonPrimitives.cast(CommonMessagesCodecJson.parseJSON($0, "ServiceDiscoveryReq.supportedServiceIDs"), "supportedServiceIDs", "ServiceDiscoveryReq") as ServiceIDListType }
    )
}

