// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Swift back end). Do not edit by hand.

import ExiRuntime

internal func toJSONServiceDetailReqType(_ value: ServiceDetailReqType) throws -> JsonObject {

    let json = JsonObject()

    json["@type"] = JsonValue.of("ServiceDetailReqType")

    json["header"] = try CommonMessagesCodecJson.toJSON(value.header)
    json["serviceID"] = JsonValue.of(value.serviceID)
    return json
}

internal func parseJSONServiceDetailReqType(_ json: JsonObject) throws -> ServiceDetailReqType {

    return ServiceDetailReqType(
        header: try JsonPrimitives.cast(CommonMessagesCodecJson.parseJSON(try JsonPrimitives.required(json, "header", "ServiceDetailReqType"), "ServiceDetailReqType.header"), "header", "ServiceDetailReqType") as MessageHeaderType,
        serviceID: try JsonPrimitives.uint16(try JsonPrimitives.required(json, "serviceID", "ServiceDetailReqType"), "serviceID", "ServiceDetailReqType")
    )
}

