// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Swift back end). Do not edit by hand.

import ExiRuntime

internal func toJSONServiceIDListType(_ value: ServiceIDListType) throws -> JsonObject {

    let json = JsonObject()

    json["@type"] = JsonValue.of("ServiceIDListType")

    let _serviceID = JsonArray()
    for item in value.serviceID {
        _serviceID.add(JsonValue.of(item))
    }
    json["serviceID"] = _serviceID

    return json
}

internal func parseJSONServiceIDListType(_ json: JsonObject) throws -> ServiceIDListType {

    return ServiceIDListType(
        serviceID: try (JsonPrimitives.optional(json, "serviceID") as? JsonArray)?.asList.map { try JsonPrimitives.uint16($0, "serviceID", "ServiceIDListType") } ?? []
    )
}

