// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Swift back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import ExiRuntime

internal func toJSONSignatureType(_ value: SignatureType) throws -> JsonObject {

    let json = JsonObject()

    json["@type"] = JsonValue.of("SignatureType")

    if let v = value.id {
        json["id"] = JsonValue.of(v)
    }

    json["signedInfo"] = try CommonMessagesCodecJson.toJSON(value.signedInfo)
    json["signatureValue"] = try CommonMessagesCodecJson.toJSON(value.signatureValue)
    if let v = value.keyInfo {
        json["keyInfo"] = try CommonMessagesCodecJson.toJSON(v)
    }

    if let v = value.object {
        json["object"] = try CommonMessagesCodecJson.toJSON(v)
    }

    return json
}

internal func parseJSONSignatureType(_ json: JsonObject) throws -> SignatureType {

    return SignatureType(
        id: try JsonPrimitives.optional(json, "id").map { try JsonPrimitives.stringValue($0, "id", "SignatureType") },
        signedInfo: try JsonPrimitives.cast(CommonMessagesCodecJson.parseJSON(try JsonPrimitives.required(json, "signedInfo", "SignatureType"), "SignatureType.signedInfo"), "signedInfo", "SignatureType") as SignedInfoType,
        signatureValue: try JsonPrimitives.cast(CommonMessagesCodecJson.parseJSON(try JsonPrimitives.required(json, "signatureValue", "SignatureType"), "SignatureType.signatureValue"), "signatureValue", "SignatureType") as SignatureValueType,
        keyInfo: try JsonPrimitives.optional(json, "keyInfo").map { try JsonPrimitives.cast(CommonMessagesCodecJson.parseJSON($0, "SignatureType.keyInfo"), "keyInfo", "SignatureType") as KeyInfo },
        object: try JsonPrimitives.optional(json, "object").map { try JsonPrimitives.cast(CommonMessagesCodecJson.parseJSON($0, "SignatureType.object"), "object", "SignatureType") as Object }
    )
}

