// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Kotlin back end). Do not edit by hand.

package cloud.charging.v2g.iso2

import cloud.charging.v2g.exi.JsonArray
import cloud.charging.v2g.exi.JsonLdException
import cloud.charging.v2g.exi.JsonObject
import cloud.charging.v2g.exi.JsonPrimitives
import cloud.charging.v2g.exi.JsonValue

internal fun toJsonCertificateUpdateReqType(value: CertificateUpdateReqType): JsonObject {

    val json = JsonObject()

    json["@type"] = JsonValue.of("CertificateUpdateReqType")

    json["id"] = JsonValue.of(value.id)
    json["contractSignatureCertChain"] = Iso15118_2CodecJson.toJson(value.contractSignatureCertChain)
    json["emaid"] = JsonValue.of(value.eMAID)
    json["listOfRootCertificateIDs"] = Iso15118_2CodecJson.toJson(value.listOfRootCertificateIDs)
    return json
}

internal fun parseJsonCertificateUpdateReqType(json: JsonObject): CertificateUpdateReqType =
    CertificateUpdateReqType(
        JsonPrimitives.stringValue(JsonPrimitives.required(json, "id", "CertificateUpdateReqType"), "id", "CertificateUpdateReqType"),
        JsonPrimitives.cast<CertificateChainType>(Iso15118_2CodecJson.parseJson(JsonPrimitives.required(json, "contractSignatureCertChain", "CertificateUpdateReqType"), "CertificateUpdateReqType.contractSignatureCertChain"), "contractSignatureCertChain", "CertificateUpdateReqType"),
        JsonPrimitives.stringValue(JsonPrimitives.required(json, "emaid", "CertificateUpdateReqType"), "emaid", "CertificateUpdateReqType"),
        JsonPrimitives.cast<ListOfRootCertificateIDsType>(Iso15118_2CodecJson.parseJson(JsonPrimitives.required(json, "listOfRootCertificateIDs", "CertificateUpdateReqType"), "CertificateUpdateReqType.listOfRootCertificateIDs"), "listOfRootCertificateIDs", "CertificateUpdateReqType")
    )

