// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Kotlin back end). Do not edit by hand.

package cloud.charging.v2g.iso2

import cloud.charging.v2g.exi.BitReader
import cloud.charging.v2g.exi.BitWriter

data class ChargingProfileType(
    val profileEntry: List<ProfileEntryType>
)

internal fun encodeChargingProfileType(w: BitWriter, msg: ChargingProfileType) {
    val list = msg.profileEntry
    require(list.size in 1..24) { "list size out of schema range" }
    for (i in list.indices) {
        w.writeBits(0u, if (i == 0) 1 else 2)   // SE(item)
        encodeProfileEntryType(w, list[i])
    }
    w.writeBits(1u, 2)   // list terminator / element EE
}

internal fun decodeChargingProfileType(r: BitReader): ChargingProfileType {
    val list = ArrayList<ProfileEntryType>()
    r.readBits(1)   // SE(item) first
    list.add(decodeProfileEntryType(r))
    while (true) {
        val ec = r.readBits(2)
        if (ec == 1u) break   // element EE
        require(ec == 0u && list.size < 24) { "invalid repeating-element event code" }
        list.add(decodeProfileEntryType(r))
    }
    return ChargingProfileType(list)
}
