// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Kotlin back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cloud.charging.v2g.iso2

import cloud.charging.v2g.exi.JsonArray
import cloud.charging.v2g.exi.JsonLdException
import cloud.charging.v2g.exi.JsonObject
import cloud.charging.v2g.exi.JsonPrimitives
import cloud.charging.v2g.exi.JsonValue

internal fun toJsonMeteringReceiptReqType(value: MeteringReceiptReqType): JsonObject {

    val json = JsonObject()

    json["@type"] = JsonValue.of("MeteringReceiptReqType")

    value.id?.let { json["id"] = JsonValue.of(it) }

    json["sessionID"] = JsonValue.of(JsonPrimitives.toHex(value.sessionID))
    value.sAScheduleTupleID?.let { json["saScheduleTupleID"] = JsonValue.of(it) }

    json["meterInfo"] = Iso15118_2CodecJson.toJson(value.meterInfo)
    return json
}

internal fun parseJsonMeteringReceiptReqType(json: JsonObject): MeteringReceiptReqType =
    MeteringReceiptReqType(
        JsonPrimitives.optional(json, "id")?.let { JsonPrimitives.stringValue(it, "id", "MeteringReceiptReqType") },
        JsonPrimitives.binary(JsonPrimitives.required(json, "sessionID", "MeteringReceiptReqType"), "sessionID", "MeteringReceiptReqType"),
        JsonPrimitives.optional(json, "saScheduleTupleID")?.let { JsonPrimitives.uint8(it, "saScheduleTupleID", "MeteringReceiptReqType") },
        JsonPrimitives.cast<MeterInfoType>(Iso15118_2CodecJson.parseJson(JsonPrimitives.required(json, "meterInfo", "MeteringReceiptReqType"), "MeteringReceiptReqType.meterInfo"), "meterInfo", "MeteringReceiptReqType")
    )

