// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Kotlin back end). Do not edit by hand.

package cloud.charging.v2g.iso2

import cloud.charging.v2g.exi.JsonArray
import cloud.charging.v2g.exi.JsonLdException
import cloud.charging.v2g.exi.JsonObject
import cloud.charging.v2g.exi.JsonPrimitives
import cloud.charging.v2g.exi.JsonValue

internal fun toJsonPowerDeliveryResType(value: PowerDeliveryResType): JsonObject {

    val json = JsonObject()

    json["@type"] = JsonValue.of("PowerDeliveryResType")

    json["responseCode"] = JsonValue.of(value.responseCode.name)
    json["evseStatus"] = Iso15118_2CodecJson.toJson(value.eVSEStatus)
    return json
}

internal fun parseJsonPowerDeliveryResType(json: JsonObject): PowerDeliveryResType =
    PowerDeliveryResType(
        JsonPrimitives.enumeration(JsonPrimitives.required(json, "responseCode", "PowerDeliveryResType"), "responseCode", "PowerDeliveryResType", ResponseCode.values()),
        JsonPrimitives.cast<EVSEStatusType>(Iso15118_2CodecJson.parseJson(JsonPrimitives.required(json, "evseStatus", "PowerDeliveryResType"), "PowerDeliveryResType.evseStatus"), "evseStatus", "PowerDeliveryResType")
    )

