// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Kotlin back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cloud.charging.v2g.iso2

import cloud.charging.v2g.exi.BitReader
import cloud.charging.v2g.exi.BitWriter
import cloud.charging.v2g.exi.ExiPrimitives

data class SignatureMethodType(
    val algorithm: String,
    val hMACOutputLength: Long?,
    val aNY: ByteArray?
)

internal fun encodeSignatureMethodType(w: BitWriter, msg: SignatureMethodType) {
    w.writeBits(0u, 1)   // AT(required attribute)
    ExiPrimitives.writeStringValue(w, msg.algorithm)
    var st94 = 0
    var done94 = false
    while (!done94) {
        when (st94) {
            0 -> {
                if (msg.hMACOutputLength != null) {
                    w.writeBits(0u, 3)   // HMACOutputLength
                    w.writeBits(0u, 1)   // value-start
                    ExiPrimitives.writeSignedInteger(w, msg.hMACOutputLength!!.toLong())
                    w.writeBits(0u, 1)   // child EE
                    st94 = 1
                } else if (msg.aNY != null) {
                    w.writeBits(3u, 3)   // ANY
                    w.writeBits(0u, 1)   // value-start
                    ExiPrimitives.writeBinary(w, msg.aNY!!)
                    w.writeBits(0u, 1)   // child EE
                    st94 = 2
                } else {
                    w.writeBits(2u, 3)   // element EE
                    done94 = true
                }
            }
            1 -> {
                if (msg.aNY != null) {
                    w.writeBits(2u, 2)   // ANY
                    w.writeBits(0u, 1)   // value-start
                    ExiPrimitives.writeBinary(w, msg.aNY!!)
                    w.writeBits(0u, 1)   // child EE
                    st94 = 2
                } else {
                    w.writeBits(1u, 2)   // element EE
                    done94 = true
                }
            }
            2 -> {
                w.writeBits(0u, 1)   // element EE
                done94 = true
            }
        }
    }
}

internal fun decodeSignatureMethodType(r: BitReader): SignatureMethodType {
    r.readBits(1)   // AT(required attribute)
    val _algorithm = ExiPrimitives.readStringValue(r, "Algorithm")
    var _hMACOutputLength: Long? = null
    var _aNY: ByteArray? = null
    var st95 = 0
    var done95 = false
    while (!done95) {
        when (st95) {
            0 -> {
                when (r.readBits(3)) {
                    0u -> {
                        r.readBits(1)   // value-start
                        _hMACOutputLength = ExiPrimitives.readSignedInteger(r).toLong()
                        r.readBits(1)   // child EE
                        st95 = 1
                    }
                    2u -> done95 = true   // element EE
                    3u -> {   // ANY
                        r.readBits(1)   // value-start
                        _aNY = ExiPrimitives.readBinary(r)
                        r.readBits(1)   // child EE
                        st95 = 2
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            1 -> {
                when (r.readBits(2)) {
                    1u -> done95 = true   // element EE
                    2u -> {   // ANY
                        r.readBits(1)   // value-start
                        _aNY = ExiPrimitives.readBinary(r)
                        r.readBits(1)   // child EE
                        st95 = 2
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            2 -> {
                when (r.readBits(1)) {
                    0u -> done95 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
        }
    }
    return SignatureMethodType(_algorithm, _hMACOutputLength, _aNY)
}
