// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Kotlin back end). Do not edit by hand.

package cloud.charging.v2g.xmldsig

import cloud.charging.v2g.exi.BitReader
import cloud.charging.v2g.exi.BitWriter
import cloud.charging.v2g.exi.ExiPrimitives

data class CanonicalizationMethodType(
    val algorithm: String,
    val aNY: ByteArray?
)

internal fun encodeCanonicalizationMethodType(w: BitWriter, msg: CanonicalizationMethodType) {
    w.writeBits(0u, 1)   // AT(required attribute)
    ExiPrimitives.writeStringValue(w, msg.algorithm)
    var st8 = 0
    var done8 = false
    while (!done8) {
        when (st8) {
            0 -> {
                if (msg.aNY != null) {
                    w.writeBits(2u, 2)   // ANY
                    w.writeBits(0u, 1)   // value-start
                    ExiPrimitives.writeBinary(w, msg.aNY!!)
                    w.writeBits(0u, 1)   // child EE
                    st8 = 1
                } else {
                    w.writeBits(1u, 2)   // element EE
                    done8 = true
                }
            }
            1 -> {
                w.writeBits(0u, 1)   // element EE
                done8 = true
            }
        }
    }
}

internal fun decodeCanonicalizationMethodType(r: BitReader): CanonicalizationMethodType {
    r.readBits(1)   // AT(required attribute)
    val _algorithm = ExiPrimitives.readStringValue(r, "Algorithm")
    var _aNY: ByteArray? = null
    var st9 = 0
    var done9 = false
    while (!done9) {
        when (st9) {
            0 -> {
                when (r.readBits(2)) {
                    1u -> done9 = true   // element EE
                    2u -> {   // ANY
                        r.readBits(1)   // value-start
                        _aNY = ExiPrimitives.readBinary(r)
                        r.readBits(1)   // child EE
                        st9 = 1
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            1 -> {
                when (r.readBits(1)) {
                    0u -> done9 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
        }
    }
    return CanonicalizationMethodType(_algorithm, _aNY)
}
