// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Swift back end). Do not edit by hand.
// Schema target namespace: cloud.charging.v2g.iso2

import ExiRuntime

public final class BodyType {
    public var bodyElement: BodyBaseType?

    public init(bodyElement: BodyBaseType? = nil) {
        self.bodyElement = bodyElement
    }
}

internal func encodeBodyType(_ w: BitWriter, _ msg: BodyType) {
    var st0 = 0
    var done0 = false
    while !done0 {
        switch st0 {
        case 0:
            if let v = msg.bodyElement as? AuthorizationReqType {
                w.writeBits(0, 6)   // AuthorizationReq
                encodeAuthorizationReqType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? AuthorizationResType {
                w.writeBits(1, 6)   // AuthorizationRes
                encodeAuthorizationResType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? CableCheckReqType {
                w.writeBits(3, 6)   // CableCheckReq
                encodeCableCheckReqType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? CableCheckResType {
                w.writeBits(4, 6)   // CableCheckRes
                encodeCableCheckResType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? CertificateInstallationReqType {
                w.writeBits(5, 6)   // CertificateInstallationReq
                encodeCertificateInstallationReqType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? CertificateInstallationResType {
                w.writeBits(6, 6)   // CertificateInstallationRes
                encodeCertificateInstallationResType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? CertificateUpdateReqType {
                w.writeBits(7, 6)   // CertificateUpdateReq
                encodeCertificateUpdateReqType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? CertificateUpdateResType {
                w.writeBits(8, 6)   // CertificateUpdateRes
                encodeCertificateUpdateResType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? ChargeParameterDiscoveryReqType {
                w.writeBits(9, 6)   // ChargeParameterDiscoveryReq
                encodeChargeParameterDiscoveryReqType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? ChargeParameterDiscoveryResType {
                w.writeBits(10, 6)   // ChargeParameterDiscoveryRes
                encodeChargeParameterDiscoveryResType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? ChargingStatusReqType {
                w.writeBits(11, 6)   // ChargingStatusReq
                encodeChargingStatusReqType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? ChargingStatusResType {
                w.writeBits(12, 6)   // ChargingStatusRes
                encodeChargingStatusResType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? CurrentDemandReqType {
                w.writeBits(13, 6)   // CurrentDemandReq
                encodeCurrentDemandReqType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? CurrentDemandResType {
                w.writeBits(14, 6)   // CurrentDemandRes
                encodeCurrentDemandResType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? MeteringReceiptReqType {
                w.writeBits(15, 6)   // MeteringReceiptReq
                encodeMeteringReceiptReqType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? MeteringReceiptResType {
                w.writeBits(16, 6)   // MeteringReceiptRes
                encodeMeteringReceiptResType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? PaymentDetailsReqType {
                w.writeBits(17, 6)   // PaymentDetailsReq
                encodePaymentDetailsReqType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? PaymentDetailsResType {
                w.writeBits(18, 6)   // PaymentDetailsRes
                encodePaymentDetailsResType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? PaymentServiceSelectionReqType {
                w.writeBits(19, 6)   // PaymentServiceSelectionReq
                encodePaymentServiceSelectionReqType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? PaymentServiceSelectionResType {
                w.writeBits(20, 6)   // PaymentServiceSelectionRes
                encodePaymentServiceSelectionResType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? PowerDeliveryReqType {
                w.writeBits(21, 6)   // PowerDeliveryReq
                encodePowerDeliveryReqType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? PowerDeliveryResType {
                w.writeBits(22, 6)   // PowerDeliveryRes
                encodePowerDeliveryResType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? PreChargeReqType {
                w.writeBits(23, 6)   // PreChargeReq
                encodePreChargeReqType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? PreChargeResType {
                w.writeBits(24, 6)   // PreChargeRes
                encodePreChargeResType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? ServiceDetailReqType {
                w.writeBits(25, 6)   // ServiceDetailReq
                encodeServiceDetailReqType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? ServiceDetailResType {
                w.writeBits(26, 6)   // ServiceDetailRes
                encodeServiceDetailResType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? ServiceDiscoveryReqType {
                w.writeBits(27, 6)   // ServiceDiscoveryReq
                encodeServiceDiscoveryReqType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? ServiceDiscoveryResType {
                w.writeBits(28, 6)   // ServiceDiscoveryRes
                encodeServiceDiscoveryResType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? SessionSetupReqType {
                w.writeBits(29, 6)   // SessionSetupReq
                encodeSessionSetupReqType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? SessionSetupResType {
                w.writeBits(30, 6)   // SessionSetupRes
                encodeSessionSetupResType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? SessionStopReqType {
                w.writeBits(31, 6)   // SessionStopReq
                encodeSessionStopReqType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? SessionStopResType {
                w.writeBits(32, 6)   // SessionStopRes
                encodeSessionStopResType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? WeldingDetectionReqType {
                w.writeBits(33, 6)   // WeldingDetectionReq
                encodeWeldingDetectionReqType(w, v)
                st0 = 1
            } else if let v = msg.bodyElement as? WeldingDetectionResType {
                w.writeBits(34, 6)   // WeldingDetectionRes
                encodeWeldingDetectionResType(w, v)
                st0 = 1
            } else {
                w.writeBits(35, 6)   // element EE
                done0 = true
            }
        case 1:
            w.writeBits(0, 1)   // element EE
            done0 = true
        default:
            done0 = true
        }
    }
}

internal func decodeBodyType(_ r: BitReader) throws -> BodyType {
    var _bodyElement: BodyBaseType? = nil
    var st1 = 0
    var done1 = false
    while !done1 {
        switch st1 {
        case 0:
            switch try r.readBits(6) {
            case 0:   // AuthorizationReq
                _bodyElement = try decodeAuthorizationReqType(r)
                st1 = 1
            case 1:   // AuthorizationRes
                _bodyElement = try decodeAuthorizationResType(r)
                st1 = 1
            case 3:   // CableCheckReq
                _bodyElement = try decodeCableCheckReqType(r)
                st1 = 1
            case 4:   // CableCheckRes
                _bodyElement = try decodeCableCheckResType(r)
                st1 = 1
            case 5:   // CertificateInstallationReq
                _bodyElement = try decodeCertificateInstallationReqType(r)
                st1 = 1
            case 6:   // CertificateInstallationRes
                _bodyElement = try decodeCertificateInstallationResType(r)
                st1 = 1
            case 7:   // CertificateUpdateReq
                _bodyElement = try decodeCertificateUpdateReqType(r)
                st1 = 1
            case 8:   // CertificateUpdateRes
                _bodyElement = try decodeCertificateUpdateResType(r)
                st1 = 1
            case 9:   // ChargeParameterDiscoveryReq
                _bodyElement = try decodeChargeParameterDiscoveryReqType(r)
                st1 = 1
            case 10:   // ChargeParameterDiscoveryRes
                _bodyElement = try decodeChargeParameterDiscoveryResType(r)
                st1 = 1
            case 11:   // ChargingStatusReq
                _bodyElement = try decodeChargingStatusReqType(r)
                st1 = 1
            case 12:   // ChargingStatusRes
                _bodyElement = try decodeChargingStatusResType(r)
                st1 = 1
            case 13:   // CurrentDemandReq
                _bodyElement = try decodeCurrentDemandReqType(r)
                st1 = 1
            case 14:   // CurrentDemandRes
                _bodyElement = try decodeCurrentDemandResType(r)
                st1 = 1
            case 15:   // MeteringReceiptReq
                _bodyElement = try decodeMeteringReceiptReqType(r)
                st1 = 1
            case 16:   // MeteringReceiptRes
                _bodyElement = try decodeMeteringReceiptResType(r)
                st1 = 1
            case 17:   // PaymentDetailsReq
                _bodyElement = try decodePaymentDetailsReqType(r)
                st1 = 1
            case 18:   // PaymentDetailsRes
                _bodyElement = try decodePaymentDetailsResType(r)
                st1 = 1
            case 19:   // PaymentServiceSelectionReq
                _bodyElement = try decodePaymentServiceSelectionReqType(r)
                st1 = 1
            case 20:   // PaymentServiceSelectionRes
                _bodyElement = try decodePaymentServiceSelectionResType(r)
                st1 = 1
            case 21:   // PowerDeliveryReq
                _bodyElement = try decodePowerDeliveryReqType(r)
                st1 = 1
            case 22:   // PowerDeliveryRes
                _bodyElement = try decodePowerDeliveryResType(r)
                st1 = 1
            case 23:   // PreChargeReq
                _bodyElement = try decodePreChargeReqType(r)
                st1 = 1
            case 24:   // PreChargeRes
                _bodyElement = try decodePreChargeResType(r)
                st1 = 1
            case 25:   // ServiceDetailReq
                _bodyElement = try decodeServiceDetailReqType(r)
                st1 = 1
            case 26:   // ServiceDetailRes
                _bodyElement = try decodeServiceDetailResType(r)
                st1 = 1
            case 27:   // ServiceDiscoveryReq
                _bodyElement = try decodeServiceDiscoveryReqType(r)
                st1 = 1
            case 28:   // ServiceDiscoveryRes
                _bodyElement = try decodeServiceDiscoveryResType(r)
                st1 = 1
            case 29:   // SessionSetupReq
                _bodyElement = try decodeSessionSetupReqType(r)
                st1 = 1
            case 30:   // SessionSetupRes
                _bodyElement = try decodeSessionSetupResType(r)
                st1 = 1
            case 31:   // SessionStopReq
                _bodyElement = try decodeSessionStopReqType(r)
                st1 = 1
            case 32:   // SessionStopRes
                _bodyElement = try decodeSessionStopResType(r)
                st1 = 1
            case 33:   // WeldingDetectionReq
                _bodyElement = try decodeWeldingDetectionReqType(r)
                st1 = 1
            case 34:   // WeldingDetectionRes
                _bodyElement = try decodeWeldingDetectionResType(r)
                st1 = 1
            case 35:   // element EE
                done1 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 1:
            switch try r.readBits(1) {
            case 0:   // element EE
                done1 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        default:
            done1 = true
        }
    }
    return BodyType(bodyElement: _bodyElement)
}
