// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Swift back end). Do not edit by hand.

import ExiRuntime

internal func toJSONChargingStatusReqType(_ value: ChargingStatusReqType) throws -> JsonObject {

    let json = JsonObject()

    json["@type"] = JsonValue.of("ChargingStatusReqType")

    return json
}

internal func parseJSONChargingStatusReqType(_ json: JsonObject) throws -> ChargingStatusReqType {

    return ChargingStatusReqType()
}

