// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Swift back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import ExiRuntime

internal func toJSONMeteringReceiptResType(_ value: MeteringReceiptResType) throws -> JsonObject {

    let json = JsonObject()

    json["@type"] = JsonValue.of("MeteringReceiptResType")

    json["responseCode"] = JsonValue.of(JsonPrimitives.fromEnumeration(value.responseCode))
    json["evseStatus"] = try Iso15118_2CodecJson.toJSON(value.eVSEStatus)
    return json
}

internal func parseJSONMeteringReceiptResType(_ json: JsonObject) throws -> MeteringReceiptResType {

    return MeteringReceiptResType(
        responseCode: try JsonPrimitives.enumeration(try JsonPrimitives.required(json, "responseCode", "MeteringReceiptResType"), "responseCode", "MeteringReceiptResType", ResponseCode.self),
        eVSEStatus: try JsonPrimitives.cast(Iso15118_2CodecJson.parseJSON(try JsonPrimitives.required(json, "evseStatus", "MeteringReceiptResType"), "MeteringReceiptResType.evseStatus"), "evseStatus", "MeteringReceiptResType") as EVSEStatusType
    )
}

