// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Swift back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import ExiRuntime

internal func toJSONParameterType(_ value: ParameterType) throws -> JsonObject {

    let json = JsonObject()

    json["@type"] = JsonValue.of("ParameterType")

    json["name"] = JsonValue.of(value.name)
    if let v = value.boolValue {
        json["boolValue"] = JsonValue.of(v)
    }

    if let v = value.byteValue {
        json["byteValue"] = JsonValue.of(v)
    }

    if let v = value.shortValue {
        json["shortValue"] = JsonValue.of(v)
    }

    if let v = value.intValue {
        json["intValue"] = JsonValue.of(v)
    }

    if let v = value.physicalValue {
        json["physicalValue"] = try Iso15118_2CodecJson.toJSON(v)
    }

    if let v = value.stringValue {
        json["stringValue"] = JsonValue.of(v)
    }

    return json
}

internal func parseJSONParameterType(_ json: JsonObject) throws -> ParameterType {

    return ParameterType(
        name: try JsonPrimitives.stringValue(try JsonPrimitives.required(json, "name", "ParameterType"), "name", "ParameterType"),
        boolValue: try JsonPrimitives.optional(json, "boolValue").map { try JsonPrimitives.bool($0, "boolValue", "ParameterType") },
        byteValue: try JsonPrimitives.optional(json, "byteValue").map { try JsonPrimitives.int8($0, "byteValue", "ParameterType") },
        shortValue: try JsonPrimitives.optional(json, "shortValue").map { try JsonPrimitives.int16($0, "shortValue", "ParameterType") },
        intValue: try JsonPrimitives.optional(json, "intValue").map { try JsonPrimitives.int32($0, "intValue", "ParameterType") },
        physicalValue: try JsonPrimitives.optional(json, "physicalValue").map { try JsonPrimitives.cast(Iso15118_2CodecJson.parseJSON($0, "ParameterType.physicalValue"), "physicalValue", "ParameterType") as PhysicalValueType },
        stringValue: try JsonPrimitives.optional(json, "stringValue").map { try JsonPrimitives.stringValue($0, "stringValue", "ParameterType") }
    )
}

