// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Swift back end). Do not edit by hand.
// Schema target namespace: cloud.charging.v2g.iso2

import ExiRuntime

public final class PreChargeResType: BodyBaseType {
    public var responseCode: ResponseCode
    public var dC_EVSEStatus: DC_EVSEStatusType
    public var eVSEPresentVoltage: PhysicalValueType

    public init(responseCode: ResponseCode, dC_EVSEStatus: DC_EVSEStatusType, eVSEPresentVoltage: PhysicalValueType) {
        self.responseCode = responseCode
        self.dC_EVSEStatus = dC_EVSEStatus
        self.eVSEPresentVoltage = eVSEPresentVoltage
        super.init()
    }
}

internal func encodePreChargeResType(_ w: BitWriter, _ msg: PreChargeResType) {
    w.writeBits(0, 1)   // SE
    w.writeBits(0, 1)   // value-start
    w.writeBits(UInt32(msg.responseCode.rawValue), 5)
    w.writeBits(0, 1)   // child EE
    w.writeBits(0, 1)   // SE
    encodeDC_EVSEStatusType(w, msg.dC_EVSEStatus)
    w.writeBits(0, 1)   // SE
    encodePhysicalValueType(w, msg.eVSEPresentVoltage)
    w.writeBits(0, 1)   // element EE
}

internal func decodePreChargeResType(_ r: BitReader) throws -> PreChargeResType {
    _ = try r.readBits(1)   // SE
    _ = try r.readBits(1)   // value-start
    let _responseCode = try exiEnum(ResponseCode.self, try r.readBits(5))
    _ = try r.readBits(1)   // child EE
    _ = try r.readBits(1)   // SE
    let _dC_EVSEStatus = try decodeDC_EVSEStatusType(r)
    _ = try r.readBits(1)   // SE
    let _eVSEPresentVoltage = try decodePhysicalValueType(r)
    _ = try r.readBits(1)   // element EE
    return PreChargeResType(responseCode: _responseCode, dC_EVSEStatus: _dC_EVSEStatus, eVSEPresentVoltage: _eVSEPresentVoltage)
}
