// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Swift back end). Do not edit by hand.
// Schema target namespace: cloud.charging.v2g.iso20.acdp

import ExiRuntime

public final class ACDP_ConnectRes: V2GResponseType {
    public var eVSEProcessing: Processing
    public var eVSEElectricalChargingDeviceStatus: ElectricalChargingDeviceStatus
    public var eVSEMechanicalChargingDeviceStatus: MechanicalChargingDeviceStatus

    public init(header: MessageHeaderType, responseCode: ResponseCode, eVSEProcessing: Processing, eVSEElectricalChargingDeviceStatus: ElectricalChargingDeviceStatus, eVSEMechanicalChargingDeviceStatus: MechanicalChargingDeviceStatus) {
        self.eVSEProcessing = eVSEProcessing
        self.eVSEElectricalChargingDeviceStatus = eVSEElectricalChargingDeviceStatus
        self.eVSEMechanicalChargingDeviceStatus = eVSEMechanicalChargingDeviceStatus
        super.init(header: header, responseCode: responseCode)
    }
}

internal func encodeACDP_ConnectRes(_ w: BitWriter, _ msg: ACDP_ConnectRes) {
    w.writeBits(0, 1)   // SE
    encodeMessageHeaderType(w, msg.header)
    w.writeBits(0, 1)   // SE
    w.writeBits(0, 1)   // value-start
    w.writeBits(UInt32(msg.responseCode.rawValue), 6)
    w.writeBits(0, 1)   // child EE
    w.writeBits(0, 1)   // SE
    w.writeBits(0, 1)   // value-start
    w.writeBits(UInt32(msg.eVSEProcessing.rawValue), 2)
    w.writeBits(0, 1)   // child EE
    w.writeBits(0, 1)   // SE
    w.writeBits(0, 1)   // value-start
    w.writeBits(UInt32(msg.eVSEElectricalChargingDeviceStatus.rawValue), 2)
    w.writeBits(0, 1)   // child EE
    w.writeBits(0, 1)   // SE
    w.writeBits(0, 1)   // value-start
    w.writeBits(UInt32(msg.eVSEMechanicalChargingDeviceStatus.rawValue), 2)
    w.writeBits(0, 1)   // child EE
    w.writeBits(0, 1)   // element EE
}

internal func decodeACDP_ConnectRes(_ r: BitReader) throws -> ACDP_ConnectRes {
    _ = try r.readBits(1)   // SE
    let _header = try decodeMessageHeaderType(r)
    _ = try r.readBits(1)   // SE
    _ = try r.readBits(1)   // value-start
    let _responseCode = try exiEnum(ResponseCode.self, try r.readBits(6))
    _ = try r.readBits(1)   // child EE
    _ = try r.readBits(1)   // SE
    _ = try r.readBits(1)   // value-start
    let _eVSEProcessing = try exiEnum(Processing.self, try r.readBits(2))
    _ = try r.readBits(1)   // child EE
    _ = try r.readBits(1)   // SE
    _ = try r.readBits(1)   // value-start
    let _eVSEElectricalChargingDeviceStatus = try exiEnum(ElectricalChargingDeviceStatus.self, try r.readBits(2))
    _ = try r.readBits(1)   // child EE
    _ = try r.readBits(1)   // SE
    _ = try r.readBits(1)   // value-start
    let _eVSEMechanicalChargingDeviceStatus = try exiEnum(MechanicalChargingDeviceStatus.self, try r.readBits(2))
    _ = try r.readBits(1)   // child EE
    _ = try r.readBits(1)   // element EE
    return ACDP_ConnectRes(header: _header, responseCode: _responseCode, eVSEProcessing: _eVSEProcessing, eVSEElectricalChargingDeviceStatus: _eVSEElectricalChargingDeviceStatus, eVSEMechanicalChargingDeviceStatus: _eVSEMechanicalChargingDeviceStatus)
}
