// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Swift back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import ExiRuntime

internal func toJSONAC_ChargeParameterDiscoveryReqType(_ value: AC_ChargeParameterDiscoveryReqType) throws -> JsonObject {

    let json = JsonObject()

    json["@type"] = JsonValue.of("AC_ChargeParameterDiscoveryReqType")

    json["header"] = try AcDerIecCodecJson.toJSON(value.header)
    json["ac_CPDReqEnergyTransferMode"] = try AcDerIecCodecJson.toJSON(value.aC_CPDReqEnergyTransferMode)
    return json
}

internal func parseJSONAC_ChargeParameterDiscoveryReqType(_ json: JsonObject) throws -> AC_ChargeParameterDiscoveryReqType {

    return AC_ChargeParameterDiscoveryReqType(
        header: try JsonPrimitives.cast(AcDerIecCodecJson.parseJSON(try JsonPrimitives.required(json, "header", "AC_ChargeParameterDiscoveryReqType"), "AC_ChargeParameterDiscoveryReqType.header"), "header", "AC_ChargeParameterDiscoveryReqType") as MessageHeaderType,
        aC_CPDReqEnergyTransferMode: try JsonPrimitives.cast(AcDerIecCodecJson.parseJSON(try JsonPrimitives.required(json, "ac_CPDReqEnergyTransferMode", "AC_ChargeParameterDiscoveryReqType"), "AC_ChargeParameterDiscoveryReqType.ac_CPDReqEnergyTransferMode"), "ac_CPDReqEnergyTransferMode", "AC_ChargeParameterDiscoveryReqType") as AC_CPDReqEnergyTransferModeType
    )
}

