// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Swift back end). Do not edit by hand.

import ExiRuntime

internal func toJSONAC_ChargeLoopReq(_ value: AC_ChargeLoopReq) throws -> JsonObject {

    let json = JsonObject()

    json["@context"] = JsonValue.of(AcDerIecCodecJson.context)
    json["@type"] = JsonValue.of("AC_ChargeLoopReq")

    json["header"] = try AcDerIecCodecJson.toJSON(value.header)
    if let v = value.displayParameters {
        json["displayParameters"] = try AcDerIecCodecJson.toJSON(v)
    }

    json["meterInfoRequested"] = JsonValue.of(value.meterInfoRequested)
    json["clReqControlMode"] = try AcDerIecCodecJson.toJSON(value.cLReqControlMode)
    return json
}

internal func parseJSONAC_ChargeLoopReq(_ json: JsonObject) throws -> AC_ChargeLoopReq {

    return AC_ChargeLoopReq(
        header: try JsonPrimitives.cast(AcDerIecCodecJson.parseJSON(try JsonPrimitives.required(json, "header", "AC_ChargeLoopReq"), "AC_ChargeLoopReq.header"), "header", "AC_ChargeLoopReq") as MessageHeaderType,
        displayParameters: try JsonPrimitives.optional(json, "displayParameters").map { try JsonPrimitives.cast(AcDerIecCodecJson.parseJSON($0, "AC_ChargeLoopReq.displayParameters"), "displayParameters", "AC_ChargeLoopReq") as DisplayParametersType },
        meterInfoRequested: try JsonPrimitives.bool(try JsonPrimitives.required(json, "meterInfoRequested", "AC_ChargeLoopReq"), "meterInfoRequested", "AC_ChargeLoopReq"),
        cLReqControlMode: try JsonPrimitives.cast(AcDerIecCodecJson.parseJSON(try JsonPrimitives.required(json, "clReqControlMode", "AC_ChargeLoopReq"), "AC_ChargeLoopReq.clReqControlMode"), "clReqControlMode", "AC_ChargeLoopReq") as CLReqControlModeType
    )
}

