// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Swift back end). Do not edit by hand.

import ExiRuntime

internal func toJSONEVReactivePowerLimitsType(_ value: EVReactivePowerLimitsType) throws -> JsonObject {

    let json = JsonObject()

    json["@type"] = JsonValue.of("EVReactivePowerLimitsType")

    json["evMaximumChargeReactivePower"] = try AcDerIecCodecJson.toJSON(value.eVMaximumChargeReactivePower)
    if let v = value.eVMaximumChargeReactivePower_L2 {
        json["evMaximumChargeReactivePower_L2"] = try AcDerIecCodecJson.toJSON(v)
    }

    if let v = value.eVMaximumChargeReactivePower_L3 {
        json["evMaximumChargeReactivePower_L3"] = try AcDerIecCodecJson.toJSON(v)
    }

    if let v = value.eVMinimumChargeReactivePower {
        json["evMinimumChargeReactivePower"] = try AcDerIecCodecJson.toJSON(v)
    }

    if let v = value.eVMinimumChargeReactivePower_L2 {
        json["evMinimumChargeReactivePower_L2"] = try AcDerIecCodecJson.toJSON(v)
    }

    if let v = value.eVMinimumChargeReactivePower_L3 {
        json["evMinimumChargeReactivePower_L3"] = try AcDerIecCodecJson.toJSON(v)
    }

    json["evMaximumDischargeReactivePower"] = try AcDerIecCodecJson.toJSON(value.eVMaximumDischargeReactivePower)
    if let v = value.eVMaximumDischargeReactivePower_L2 {
        json["evMaximumDischargeReactivePower_L2"] = try AcDerIecCodecJson.toJSON(v)
    }

    if let v = value.eVMaximumDischargeReactivePower_L3 {
        json["evMaximumDischargeReactivePower_L3"] = try AcDerIecCodecJson.toJSON(v)
    }

    if let v = value.eVMinimumDischargeReactivePower {
        json["evMinimumDischargeReactivePower"] = try AcDerIecCodecJson.toJSON(v)
    }

    if let v = value.eVMinimumDischargeReactivePower_L2 {
        json["evMinimumDischargeReactivePower_L2"] = try AcDerIecCodecJson.toJSON(v)
    }

    if let v = value.eVMinimumDischargeReactivePower_L3 {
        json["evMinimumDischargeReactivePower_L3"] = try AcDerIecCodecJson.toJSON(v)
    }

    return json
}

internal func parseJSONEVReactivePowerLimitsType(_ json: JsonObject) throws -> EVReactivePowerLimitsType {

    return EVReactivePowerLimitsType(
        eVMaximumChargeReactivePower: try JsonPrimitives.cast(AcDerIecCodecJson.parseJSON(try JsonPrimitives.required(json, "evMaximumChargeReactivePower", "EVReactivePowerLimitsType"), "EVReactivePowerLimitsType.evMaximumChargeReactivePower"), "evMaximumChargeReactivePower", "EVReactivePowerLimitsType") as RationalNumberType,
        eVMaximumChargeReactivePower_L2: try JsonPrimitives.optional(json, "evMaximumChargeReactivePower_L2").map { try JsonPrimitives.cast(AcDerIecCodecJson.parseJSON($0, "EVReactivePowerLimitsType.evMaximumChargeReactivePower_L2"), "evMaximumChargeReactivePower_L2", "EVReactivePowerLimitsType") as RationalNumberType },
        eVMaximumChargeReactivePower_L3: try JsonPrimitives.optional(json, "evMaximumChargeReactivePower_L3").map { try JsonPrimitives.cast(AcDerIecCodecJson.parseJSON($0, "EVReactivePowerLimitsType.evMaximumChargeReactivePower_L3"), "evMaximumChargeReactivePower_L3", "EVReactivePowerLimitsType") as RationalNumberType },
        eVMinimumChargeReactivePower: try JsonPrimitives.optional(json, "evMinimumChargeReactivePower").map { try JsonPrimitives.cast(AcDerIecCodecJson.parseJSON($0, "EVReactivePowerLimitsType.evMinimumChargeReactivePower"), "evMinimumChargeReactivePower", "EVReactivePowerLimitsType") as RationalNumberType },
        eVMinimumChargeReactivePower_L2: try JsonPrimitives.optional(json, "evMinimumChargeReactivePower_L2").map { try JsonPrimitives.cast(AcDerIecCodecJson.parseJSON($0, "EVReactivePowerLimitsType.evMinimumChargeReactivePower_L2"), "evMinimumChargeReactivePower_L2", "EVReactivePowerLimitsType") as RationalNumberType },
        eVMinimumChargeReactivePower_L3: try JsonPrimitives.optional(json, "evMinimumChargeReactivePower_L3").map { try JsonPrimitives.cast(AcDerIecCodecJson.parseJSON($0, "EVReactivePowerLimitsType.evMinimumChargeReactivePower_L3"), "evMinimumChargeReactivePower_L3", "EVReactivePowerLimitsType") as RationalNumberType },
        eVMaximumDischargeReactivePower: try JsonPrimitives.cast(AcDerIecCodecJson.parseJSON(try JsonPrimitives.required(json, "evMaximumDischargeReactivePower", "EVReactivePowerLimitsType"), "EVReactivePowerLimitsType.evMaximumDischargeReactivePower"), "evMaximumDischargeReactivePower", "EVReactivePowerLimitsType") as RationalNumberType,
        eVMaximumDischargeReactivePower_L2: try JsonPrimitives.optional(json, "evMaximumDischargeReactivePower_L2").map { try JsonPrimitives.cast(AcDerIecCodecJson.parseJSON($0, "EVReactivePowerLimitsType.evMaximumDischargeReactivePower_L2"), "evMaximumDischargeReactivePower_L2", "EVReactivePowerLimitsType") as RationalNumberType },
        eVMaximumDischargeReactivePower_L3: try JsonPrimitives.optional(json, "evMaximumDischargeReactivePower_L3").map { try JsonPrimitives.cast(AcDerIecCodecJson.parseJSON($0, "EVReactivePowerLimitsType.evMaximumDischargeReactivePower_L3"), "evMaximumDischargeReactivePower_L3", "EVReactivePowerLimitsType") as RationalNumberType },
        eVMinimumDischargeReactivePower: try JsonPrimitives.optional(json, "evMinimumDischargeReactivePower").map { try JsonPrimitives.cast(AcDerIecCodecJson.parseJSON($0, "EVReactivePowerLimitsType.evMinimumDischargeReactivePower"), "evMinimumDischargeReactivePower", "EVReactivePowerLimitsType") as RationalNumberType },
        eVMinimumDischargeReactivePower_L2: try JsonPrimitives.optional(json, "evMinimumDischargeReactivePower_L2").map { try JsonPrimitives.cast(AcDerIecCodecJson.parseJSON($0, "EVReactivePowerLimitsType.evMinimumDischargeReactivePower_L2"), "evMinimumDischargeReactivePower_L2", "EVReactivePowerLimitsType") as RationalNumberType },
        eVMinimumDischargeReactivePower_L3: try JsonPrimitives.optional(json, "evMinimumDischargeReactivePower_L3").map { try JsonPrimitives.cast(AcDerIecCodecJson.parseJSON($0, "EVReactivePowerLimitsType.evMinimumDischargeReactivePower_L3"), "evMinimumDischargeReactivePower_L3", "EVReactivePowerLimitsType") as RationalNumberType }
    )
}

