// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Swift back end). Do not edit by hand.
// Schema target namespace: cloud.charging.v2g.iso20.acderiec

import ExiRuntime

public class Scheduled_AC_CLReqControlModeType: Scheduled_CLReqControlModeType {
    public var eVMaximumChargePower: RationalNumberType?
    public var eVMaximumChargePower_L2: RationalNumberType?
    public var eVMaximumChargePower_L3: RationalNumberType?
    public var eVMinimumChargePower: RationalNumberType?
    public var eVMinimumChargePower_L2: RationalNumberType?
    public var eVMinimumChargePower_L3: RationalNumberType?
    public var eVPresentActivePower: RationalNumberType
    public var eVPresentActivePower_L2: RationalNumberType?
    public var eVPresentActivePower_L3: RationalNumberType?
    public var eVPresentReactivePower: RationalNumberType?
    public var eVPresentReactivePower_L2: RationalNumberType?
    public var eVPresentReactivePower_L3: RationalNumberType?

    public init(eVTargetEnergyRequest: RationalNumberType? = nil, eVMaximumEnergyRequest: RationalNumberType? = nil, eVMinimumEnergyRequest: RationalNumberType? = nil, eVMaximumChargePower: RationalNumberType? = nil, eVMaximumChargePower_L2: RationalNumberType? = nil, eVMaximumChargePower_L3: RationalNumberType? = nil, eVMinimumChargePower: RationalNumberType? = nil, eVMinimumChargePower_L2: RationalNumberType? = nil, eVMinimumChargePower_L3: RationalNumberType? = nil, eVPresentActivePower: RationalNumberType, eVPresentActivePower_L2: RationalNumberType? = nil, eVPresentActivePower_L3: RationalNumberType? = nil, eVPresentReactivePower: RationalNumberType? = nil, eVPresentReactivePower_L2: RationalNumberType? = nil, eVPresentReactivePower_L3: RationalNumberType? = nil) {
        self.eVMaximumChargePower = eVMaximumChargePower
        self.eVMaximumChargePower_L2 = eVMaximumChargePower_L2
        self.eVMaximumChargePower_L3 = eVMaximumChargePower_L3
        self.eVMinimumChargePower = eVMinimumChargePower
        self.eVMinimumChargePower_L2 = eVMinimumChargePower_L2
        self.eVMinimumChargePower_L3 = eVMinimumChargePower_L3
        self.eVPresentActivePower = eVPresentActivePower
        self.eVPresentActivePower_L2 = eVPresentActivePower_L2
        self.eVPresentActivePower_L3 = eVPresentActivePower_L3
        self.eVPresentReactivePower = eVPresentReactivePower
        self.eVPresentReactivePower_L2 = eVPresentReactivePower_L2
        self.eVPresentReactivePower_L3 = eVPresentReactivePower_L3
        super.init(eVTargetEnergyRequest: eVTargetEnergyRequest, eVMaximumEnergyRequest: eVMaximumEnergyRequest, eVMinimumEnergyRequest: eVMinimumEnergyRequest)
    }
}

internal func encodeScheduled_AC_CLReqControlModeType(_ w: BitWriter, _ msg: Scheduled_AC_CLReqControlModeType) {
    var st120 = 0
    var done120 = false
    while !done120 {
        switch st120 {
        case 0:
            if let v = msg.eVTargetEnergyRequest {
                w.writeBits(0, 4)   // EVTargetEnergyRequest
                encodeRationalNumberType(w, v)
                st120 = 1
            } else if let v = msg.eVMaximumEnergyRequest {
                w.writeBits(1, 4)   // EVMaximumEnergyRequest
                encodeRationalNumberType(w, v)
                st120 = 2
            } else if let v = msg.eVMinimumEnergyRequest {
                w.writeBits(2, 4)   // EVMinimumEnergyRequest
                encodeRationalNumberType(w, v)
                st120 = 3
            } else if let v = msg.eVMaximumChargePower {
                w.writeBits(3, 4)   // EVMaximumChargePower
                encodeRationalNumberType(w, v)
                st120 = 4
            } else if let v = msg.eVMaximumChargePower_L2 {
                w.writeBits(4, 4)   // EVMaximumChargePower_L2
                encodeRationalNumberType(w, v)
                st120 = 5
            } else if let v = msg.eVMaximumChargePower_L3 {
                w.writeBits(5, 4)   // EVMaximumChargePower_L3
                encodeRationalNumberType(w, v)
                st120 = 6
            } else if let v = msg.eVMinimumChargePower {
                w.writeBits(6, 4)   // EVMinimumChargePower
                encodeRationalNumberType(w, v)
                st120 = 7
            } else if let v = msg.eVMinimumChargePower_L2 {
                w.writeBits(7, 4)   // EVMinimumChargePower_L2
                encodeRationalNumberType(w, v)
                st120 = 8
            } else if let v = msg.eVMinimumChargePower_L3 {
                w.writeBits(8, 4)   // EVMinimumChargePower_L3
                encodeRationalNumberType(w, v)
                st120 = 9
            } else {
                w.writeBits(9, 4)   // SE(EVPresentActivePower)
                encodeRationalNumberType(w, msg.eVPresentActivePower)
                done120 = true
            }
        case 1:
            if let v = msg.eVMaximumEnergyRequest {
                w.writeBits(0, 4)   // EVMaximumEnergyRequest
                encodeRationalNumberType(w, v)
                st120 = 2
            } else if let v = msg.eVMinimumEnergyRequest {
                w.writeBits(1, 4)   // EVMinimumEnergyRequest
                encodeRationalNumberType(w, v)
                st120 = 3
            } else if let v = msg.eVMaximumChargePower {
                w.writeBits(2, 4)   // EVMaximumChargePower
                encodeRationalNumberType(w, v)
                st120 = 4
            } else if let v = msg.eVMaximumChargePower_L2 {
                w.writeBits(3, 4)   // EVMaximumChargePower_L2
                encodeRationalNumberType(w, v)
                st120 = 5
            } else if let v = msg.eVMaximumChargePower_L3 {
                w.writeBits(4, 4)   // EVMaximumChargePower_L3
                encodeRationalNumberType(w, v)
                st120 = 6
            } else if let v = msg.eVMinimumChargePower {
                w.writeBits(5, 4)   // EVMinimumChargePower
                encodeRationalNumberType(w, v)
                st120 = 7
            } else if let v = msg.eVMinimumChargePower_L2 {
                w.writeBits(6, 4)   // EVMinimumChargePower_L2
                encodeRationalNumberType(w, v)
                st120 = 8
            } else if let v = msg.eVMinimumChargePower_L3 {
                w.writeBits(7, 4)   // EVMinimumChargePower_L3
                encodeRationalNumberType(w, v)
                st120 = 9
            } else {
                w.writeBits(8, 4)   // SE(EVPresentActivePower)
                encodeRationalNumberType(w, msg.eVPresentActivePower)
                done120 = true
            }
        case 2:
            if let v = msg.eVMinimumEnergyRequest {
                w.writeBits(0, 4)   // EVMinimumEnergyRequest
                encodeRationalNumberType(w, v)
                st120 = 3
            } else if let v = msg.eVMaximumChargePower {
                w.writeBits(1, 4)   // EVMaximumChargePower
                encodeRationalNumberType(w, v)
                st120 = 4
            } else if let v = msg.eVMaximumChargePower_L2 {
                w.writeBits(2, 4)   // EVMaximumChargePower_L2
                encodeRationalNumberType(w, v)
                st120 = 5
            } else if let v = msg.eVMaximumChargePower_L3 {
                w.writeBits(3, 4)   // EVMaximumChargePower_L3
                encodeRationalNumberType(w, v)
                st120 = 6
            } else if let v = msg.eVMinimumChargePower {
                w.writeBits(4, 4)   // EVMinimumChargePower
                encodeRationalNumberType(w, v)
                st120 = 7
            } else if let v = msg.eVMinimumChargePower_L2 {
                w.writeBits(5, 4)   // EVMinimumChargePower_L2
                encodeRationalNumberType(w, v)
                st120 = 8
            } else if let v = msg.eVMinimumChargePower_L3 {
                w.writeBits(6, 4)   // EVMinimumChargePower_L3
                encodeRationalNumberType(w, v)
                st120 = 9
            } else {
                w.writeBits(7, 4)   // SE(EVPresentActivePower)
                encodeRationalNumberType(w, msg.eVPresentActivePower)
                done120 = true
            }
        case 3:
            if let v = msg.eVMaximumChargePower {
                w.writeBits(0, 3)   // EVMaximumChargePower
                encodeRationalNumberType(w, v)
                st120 = 4
            } else if let v = msg.eVMaximumChargePower_L2 {
                w.writeBits(1, 3)   // EVMaximumChargePower_L2
                encodeRationalNumberType(w, v)
                st120 = 5
            } else if let v = msg.eVMaximumChargePower_L3 {
                w.writeBits(2, 3)   // EVMaximumChargePower_L3
                encodeRationalNumberType(w, v)
                st120 = 6
            } else if let v = msg.eVMinimumChargePower {
                w.writeBits(3, 3)   // EVMinimumChargePower
                encodeRationalNumberType(w, v)
                st120 = 7
            } else if let v = msg.eVMinimumChargePower_L2 {
                w.writeBits(4, 3)   // EVMinimumChargePower_L2
                encodeRationalNumberType(w, v)
                st120 = 8
            } else if let v = msg.eVMinimumChargePower_L3 {
                w.writeBits(5, 3)   // EVMinimumChargePower_L3
                encodeRationalNumberType(w, v)
                st120 = 9
            } else {
                w.writeBits(6, 3)   // SE(EVPresentActivePower)
                encodeRationalNumberType(w, msg.eVPresentActivePower)
                done120 = true
            }
        case 4:
            if let v = msg.eVMaximumChargePower_L2 {
                w.writeBits(0, 3)   // EVMaximumChargePower_L2
                encodeRationalNumberType(w, v)
                st120 = 5
            } else if let v = msg.eVMaximumChargePower_L3 {
                w.writeBits(1, 3)   // EVMaximumChargePower_L3
                encodeRationalNumberType(w, v)
                st120 = 6
            } else if let v = msg.eVMinimumChargePower {
                w.writeBits(2, 3)   // EVMinimumChargePower
                encodeRationalNumberType(w, v)
                st120 = 7
            } else if let v = msg.eVMinimumChargePower_L2 {
                w.writeBits(3, 3)   // EVMinimumChargePower_L2
                encodeRationalNumberType(w, v)
                st120 = 8
            } else if let v = msg.eVMinimumChargePower_L3 {
                w.writeBits(4, 3)   // EVMinimumChargePower_L3
                encodeRationalNumberType(w, v)
                st120 = 9
            } else {
                w.writeBits(5, 3)   // SE(EVPresentActivePower)
                encodeRationalNumberType(w, msg.eVPresentActivePower)
                done120 = true
            }
        case 5:
            if let v = msg.eVMaximumChargePower_L3 {
                w.writeBits(0, 3)   // EVMaximumChargePower_L3
                encodeRationalNumberType(w, v)
                st120 = 6
            } else if let v = msg.eVMinimumChargePower {
                w.writeBits(1, 3)   // EVMinimumChargePower
                encodeRationalNumberType(w, v)
                st120 = 7
            } else if let v = msg.eVMinimumChargePower_L2 {
                w.writeBits(2, 3)   // EVMinimumChargePower_L2
                encodeRationalNumberType(w, v)
                st120 = 8
            } else if let v = msg.eVMinimumChargePower_L3 {
                w.writeBits(3, 3)   // EVMinimumChargePower_L3
                encodeRationalNumberType(w, v)
                st120 = 9
            } else {
                w.writeBits(4, 3)   // SE(EVPresentActivePower)
                encodeRationalNumberType(w, msg.eVPresentActivePower)
                done120 = true
            }
        case 6:
            if let v = msg.eVMinimumChargePower {
                w.writeBits(0, 3)   // EVMinimumChargePower
                encodeRationalNumberType(w, v)
                st120 = 7
            } else if let v = msg.eVMinimumChargePower_L2 {
                w.writeBits(1, 3)   // EVMinimumChargePower_L2
                encodeRationalNumberType(w, v)
                st120 = 8
            } else if let v = msg.eVMinimumChargePower_L3 {
                w.writeBits(2, 3)   // EVMinimumChargePower_L3
                encodeRationalNumberType(w, v)
                st120 = 9
            } else {
                w.writeBits(3, 3)   // SE(EVPresentActivePower)
                encodeRationalNumberType(w, msg.eVPresentActivePower)
                done120 = true
            }
        case 7:
            if let v = msg.eVMinimumChargePower_L2 {
                w.writeBits(0, 2)   // EVMinimumChargePower_L2
                encodeRationalNumberType(w, v)
                st120 = 8
            } else if let v = msg.eVMinimumChargePower_L3 {
                w.writeBits(1, 2)   // EVMinimumChargePower_L3
                encodeRationalNumberType(w, v)
                st120 = 9
            } else {
                w.writeBits(2, 2)   // SE(EVPresentActivePower)
                encodeRationalNumberType(w, msg.eVPresentActivePower)
                done120 = true
            }
        case 8:
            if let v = msg.eVMinimumChargePower_L3 {
                w.writeBits(0, 2)   // EVMinimumChargePower_L3
                encodeRationalNumberType(w, v)
                st120 = 9
            } else {
                w.writeBits(1, 2)   // SE(EVPresentActivePower)
                encodeRationalNumberType(w, msg.eVPresentActivePower)
                done120 = true
            }
        case 9:
            w.writeBits(0, 1)   // SE(EVPresentActivePower)
            encodeRationalNumberType(w, msg.eVPresentActivePower)
            done120 = true
        default:
            done120 = true
        }
    }
    var st121 = 0
    var done121 = false
    while !done121 {
        switch st121 {
        case 0:
            if let v = msg.eVPresentActivePower_L2 {
                w.writeBits(0, 3)   // EVPresentActivePower_L2
                encodeRationalNumberType(w, v)
                st121 = 1
            } else if let v = msg.eVPresentActivePower_L3 {
                w.writeBits(1, 3)   // EVPresentActivePower_L3
                encodeRationalNumberType(w, v)
                st121 = 2
            } else if let v = msg.eVPresentReactivePower {
                w.writeBits(2, 3)   // EVPresentReactivePower
                encodeRationalNumberType(w, v)
                st121 = 3
            } else if let v = msg.eVPresentReactivePower_L2 {
                w.writeBits(3, 3)   // EVPresentReactivePower_L2
                encodeRationalNumberType(w, v)
                st121 = 4
            } else if let v = msg.eVPresentReactivePower_L3 {
                w.writeBits(4, 3)   // EVPresentReactivePower_L3
                encodeRationalNumberType(w, v)
                st121 = 5
            } else {
                w.writeBits(5, 3)   // element EE
                done121 = true
            }
        case 1:
            if let v = msg.eVPresentActivePower_L3 {
                w.writeBits(0, 3)   // EVPresentActivePower_L3
                encodeRationalNumberType(w, v)
                st121 = 2
            } else if let v = msg.eVPresentReactivePower {
                w.writeBits(1, 3)   // EVPresentReactivePower
                encodeRationalNumberType(w, v)
                st121 = 3
            } else if let v = msg.eVPresentReactivePower_L2 {
                w.writeBits(2, 3)   // EVPresentReactivePower_L2
                encodeRationalNumberType(w, v)
                st121 = 4
            } else if let v = msg.eVPresentReactivePower_L3 {
                w.writeBits(3, 3)   // EVPresentReactivePower_L3
                encodeRationalNumberType(w, v)
                st121 = 5
            } else {
                w.writeBits(4, 3)   // element EE
                done121 = true
            }
        case 2:
            if let v = msg.eVPresentReactivePower {
                w.writeBits(0, 3)   // EVPresentReactivePower
                encodeRationalNumberType(w, v)
                st121 = 3
            } else if let v = msg.eVPresentReactivePower_L2 {
                w.writeBits(1, 3)   // EVPresentReactivePower_L2
                encodeRationalNumberType(w, v)
                st121 = 4
            } else if let v = msg.eVPresentReactivePower_L3 {
                w.writeBits(2, 3)   // EVPresentReactivePower_L3
                encodeRationalNumberType(w, v)
                st121 = 5
            } else {
                w.writeBits(3, 3)   // element EE
                done121 = true
            }
        case 3:
            if let v = msg.eVPresentReactivePower_L2 {
                w.writeBits(0, 2)   // EVPresentReactivePower_L2
                encodeRationalNumberType(w, v)
                st121 = 4
            } else if let v = msg.eVPresentReactivePower_L3 {
                w.writeBits(1, 2)   // EVPresentReactivePower_L3
                encodeRationalNumberType(w, v)
                st121 = 5
            } else {
                w.writeBits(2, 2)   // element EE
                done121 = true
            }
        case 4:
            if let v = msg.eVPresentReactivePower_L3 {
                w.writeBits(0, 2)   // EVPresentReactivePower_L3
                encodeRationalNumberType(w, v)
                st121 = 5
            } else {
                w.writeBits(1, 2)   // element EE
                done121 = true
            }
        case 5:
            w.writeBits(0, 1)   // element EE
            done121 = true
        default:
            done121 = true
        }
    }
}

internal func decodeScheduled_AC_CLReqControlModeType(_ r: BitReader) throws -> Scheduled_AC_CLReqControlModeType {
    var _eVTargetEnergyRequest: RationalNumberType? = nil
    var _eVMaximumEnergyRequest: RationalNumberType? = nil
    var _eVMinimumEnergyRequest: RationalNumberType? = nil
    var _eVMaximumChargePower: RationalNumberType? = nil
    var _eVMaximumChargePower_L2: RationalNumberType? = nil
    var _eVMaximumChargePower_L3: RationalNumberType? = nil
    var _eVMinimumChargePower: RationalNumberType? = nil
    var _eVMinimumChargePower_L2: RationalNumberType? = nil
    var _eVMinimumChargePower_L3: RationalNumberType? = nil
    var _eVPresentActivePower: RationalNumberType? = nil
    var st122 = 0
    var done122 = false
    while !done122 {
        switch st122 {
        case 0:
            switch try r.readBits(4) {
            case 0:   // EVTargetEnergyRequest
                _eVTargetEnergyRequest = try decodeRationalNumberType(r)
                st122 = 1
            case 1:   // EVMaximumEnergyRequest
                _eVMaximumEnergyRequest = try decodeRationalNumberType(r)
                st122 = 2
            case 2:   // EVMinimumEnergyRequest
                _eVMinimumEnergyRequest = try decodeRationalNumberType(r)
                st122 = 3
            case 3:   // EVMaximumChargePower
                _eVMaximumChargePower = try decodeRationalNumberType(r)
                st122 = 4
            case 4:   // EVMaximumChargePower_L2
                _eVMaximumChargePower_L2 = try decodeRationalNumberType(r)
                st122 = 5
            case 5:   // EVMaximumChargePower_L3
                _eVMaximumChargePower_L3 = try decodeRationalNumberType(r)
                st122 = 6
            case 6:   // EVMinimumChargePower
                _eVMinimumChargePower = try decodeRationalNumberType(r)
                st122 = 7
            case 7:   // EVMinimumChargePower_L2
                _eVMinimumChargePower_L2 = try decodeRationalNumberType(r)
                st122 = 8
            case 8:   // EVMinimumChargePower_L3
                _eVMinimumChargePower_L3 = try decodeRationalNumberType(r)
                st122 = 9
            case 9:   // SE(EVPresentActivePower)
                _eVPresentActivePower = try decodeRationalNumberType(r)
                done122 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 1:
            switch try r.readBits(4) {
            case 0:   // EVMaximumEnergyRequest
                _eVMaximumEnergyRequest = try decodeRationalNumberType(r)
                st122 = 2
            case 1:   // EVMinimumEnergyRequest
                _eVMinimumEnergyRequest = try decodeRationalNumberType(r)
                st122 = 3
            case 2:   // EVMaximumChargePower
                _eVMaximumChargePower = try decodeRationalNumberType(r)
                st122 = 4
            case 3:   // EVMaximumChargePower_L2
                _eVMaximumChargePower_L2 = try decodeRationalNumberType(r)
                st122 = 5
            case 4:   // EVMaximumChargePower_L3
                _eVMaximumChargePower_L3 = try decodeRationalNumberType(r)
                st122 = 6
            case 5:   // EVMinimumChargePower
                _eVMinimumChargePower = try decodeRationalNumberType(r)
                st122 = 7
            case 6:   // EVMinimumChargePower_L2
                _eVMinimumChargePower_L2 = try decodeRationalNumberType(r)
                st122 = 8
            case 7:   // EVMinimumChargePower_L3
                _eVMinimumChargePower_L3 = try decodeRationalNumberType(r)
                st122 = 9
            case 8:   // SE(EVPresentActivePower)
                _eVPresentActivePower = try decodeRationalNumberType(r)
                done122 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 2:
            switch try r.readBits(4) {
            case 0:   // EVMinimumEnergyRequest
                _eVMinimumEnergyRequest = try decodeRationalNumberType(r)
                st122 = 3
            case 1:   // EVMaximumChargePower
                _eVMaximumChargePower = try decodeRationalNumberType(r)
                st122 = 4
            case 2:   // EVMaximumChargePower_L2
                _eVMaximumChargePower_L2 = try decodeRationalNumberType(r)
                st122 = 5
            case 3:   // EVMaximumChargePower_L3
                _eVMaximumChargePower_L3 = try decodeRationalNumberType(r)
                st122 = 6
            case 4:   // EVMinimumChargePower
                _eVMinimumChargePower = try decodeRationalNumberType(r)
                st122 = 7
            case 5:   // EVMinimumChargePower_L2
                _eVMinimumChargePower_L2 = try decodeRationalNumberType(r)
                st122 = 8
            case 6:   // EVMinimumChargePower_L3
                _eVMinimumChargePower_L3 = try decodeRationalNumberType(r)
                st122 = 9
            case 7:   // SE(EVPresentActivePower)
                _eVPresentActivePower = try decodeRationalNumberType(r)
                done122 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 3:
            switch try r.readBits(3) {
            case 0:   // EVMaximumChargePower
                _eVMaximumChargePower = try decodeRationalNumberType(r)
                st122 = 4
            case 1:   // EVMaximumChargePower_L2
                _eVMaximumChargePower_L2 = try decodeRationalNumberType(r)
                st122 = 5
            case 2:   // EVMaximumChargePower_L3
                _eVMaximumChargePower_L3 = try decodeRationalNumberType(r)
                st122 = 6
            case 3:   // EVMinimumChargePower
                _eVMinimumChargePower = try decodeRationalNumberType(r)
                st122 = 7
            case 4:   // EVMinimumChargePower_L2
                _eVMinimumChargePower_L2 = try decodeRationalNumberType(r)
                st122 = 8
            case 5:   // EVMinimumChargePower_L3
                _eVMinimumChargePower_L3 = try decodeRationalNumberType(r)
                st122 = 9
            case 6:   // SE(EVPresentActivePower)
                _eVPresentActivePower = try decodeRationalNumberType(r)
                done122 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 4:
            switch try r.readBits(3) {
            case 0:   // EVMaximumChargePower_L2
                _eVMaximumChargePower_L2 = try decodeRationalNumberType(r)
                st122 = 5
            case 1:   // EVMaximumChargePower_L3
                _eVMaximumChargePower_L3 = try decodeRationalNumberType(r)
                st122 = 6
            case 2:   // EVMinimumChargePower
                _eVMinimumChargePower = try decodeRationalNumberType(r)
                st122 = 7
            case 3:   // EVMinimumChargePower_L2
                _eVMinimumChargePower_L2 = try decodeRationalNumberType(r)
                st122 = 8
            case 4:   // EVMinimumChargePower_L3
                _eVMinimumChargePower_L3 = try decodeRationalNumberType(r)
                st122 = 9
            case 5:   // SE(EVPresentActivePower)
                _eVPresentActivePower = try decodeRationalNumberType(r)
                done122 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 5:
            switch try r.readBits(3) {
            case 0:   // EVMaximumChargePower_L3
                _eVMaximumChargePower_L3 = try decodeRationalNumberType(r)
                st122 = 6
            case 1:   // EVMinimumChargePower
                _eVMinimumChargePower = try decodeRationalNumberType(r)
                st122 = 7
            case 2:   // EVMinimumChargePower_L2
                _eVMinimumChargePower_L2 = try decodeRationalNumberType(r)
                st122 = 8
            case 3:   // EVMinimumChargePower_L3
                _eVMinimumChargePower_L3 = try decodeRationalNumberType(r)
                st122 = 9
            case 4:   // SE(EVPresentActivePower)
                _eVPresentActivePower = try decodeRationalNumberType(r)
                done122 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 6:
            switch try r.readBits(3) {
            case 0:   // EVMinimumChargePower
                _eVMinimumChargePower = try decodeRationalNumberType(r)
                st122 = 7
            case 1:   // EVMinimumChargePower_L2
                _eVMinimumChargePower_L2 = try decodeRationalNumberType(r)
                st122 = 8
            case 2:   // EVMinimumChargePower_L3
                _eVMinimumChargePower_L3 = try decodeRationalNumberType(r)
                st122 = 9
            case 3:   // SE(EVPresentActivePower)
                _eVPresentActivePower = try decodeRationalNumberType(r)
                done122 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 7:
            switch try r.readBits(2) {
            case 0:   // EVMinimumChargePower_L2
                _eVMinimumChargePower_L2 = try decodeRationalNumberType(r)
                st122 = 8
            case 1:   // EVMinimumChargePower_L3
                _eVMinimumChargePower_L3 = try decodeRationalNumberType(r)
                st122 = 9
            case 2:   // SE(EVPresentActivePower)
                _eVPresentActivePower = try decodeRationalNumberType(r)
                done122 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 8:
            switch try r.readBits(2) {
            case 0:   // EVMinimumChargePower_L3
                _eVMinimumChargePower_L3 = try decodeRationalNumberType(r)
                st122 = 9
            case 1:   // SE(EVPresentActivePower)
                _eVPresentActivePower = try decodeRationalNumberType(r)
                done122 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 9:
            switch try r.readBits(1) {
            case 0:   // SE(EVPresentActivePower)
                _eVPresentActivePower = try decodeRationalNumberType(r)
                done122 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        default:
            done122 = true
        }
    }
    guard let _eVPresentActivePower else {
        throw ExiError.invalidEventCode("EVPresentActivePower is required but the element ended")
    }
    var _eVPresentActivePower_L2: RationalNumberType? = nil
    var _eVPresentActivePower_L3: RationalNumberType? = nil
    var _eVPresentReactivePower: RationalNumberType? = nil
    var _eVPresentReactivePower_L2: RationalNumberType? = nil
    var _eVPresentReactivePower_L3: RationalNumberType? = nil
    var st123 = 0
    var done123 = false
    while !done123 {
        switch st123 {
        case 0:
            switch try r.readBits(3) {
            case 0:   // EVPresentActivePower_L2
                _eVPresentActivePower_L2 = try decodeRationalNumberType(r)
                st123 = 1
            case 1:   // EVPresentActivePower_L3
                _eVPresentActivePower_L3 = try decodeRationalNumberType(r)
                st123 = 2
            case 2:   // EVPresentReactivePower
                _eVPresentReactivePower = try decodeRationalNumberType(r)
                st123 = 3
            case 3:   // EVPresentReactivePower_L2
                _eVPresentReactivePower_L2 = try decodeRationalNumberType(r)
                st123 = 4
            case 4:   // EVPresentReactivePower_L3
                _eVPresentReactivePower_L3 = try decodeRationalNumberType(r)
                st123 = 5
            case 5:   // element EE
                done123 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 1:
            switch try r.readBits(3) {
            case 0:   // EVPresentActivePower_L3
                _eVPresentActivePower_L3 = try decodeRationalNumberType(r)
                st123 = 2
            case 1:   // EVPresentReactivePower
                _eVPresentReactivePower = try decodeRationalNumberType(r)
                st123 = 3
            case 2:   // EVPresentReactivePower_L2
                _eVPresentReactivePower_L2 = try decodeRationalNumberType(r)
                st123 = 4
            case 3:   // EVPresentReactivePower_L3
                _eVPresentReactivePower_L3 = try decodeRationalNumberType(r)
                st123 = 5
            case 4:   // element EE
                done123 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 2:
            switch try r.readBits(3) {
            case 0:   // EVPresentReactivePower
                _eVPresentReactivePower = try decodeRationalNumberType(r)
                st123 = 3
            case 1:   // EVPresentReactivePower_L2
                _eVPresentReactivePower_L2 = try decodeRationalNumberType(r)
                st123 = 4
            case 2:   // EVPresentReactivePower_L3
                _eVPresentReactivePower_L3 = try decodeRationalNumberType(r)
                st123 = 5
            case 3:   // element EE
                done123 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 3:
            switch try r.readBits(2) {
            case 0:   // EVPresentReactivePower_L2
                _eVPresentReactivePower_L2 = try decodeRationalNumberType(r)
                st123 = 4
            case 1:   // EVPresentReactivePower_L3
                _eVPresentReactivePower_L3 = try decodeRationalNumberType(r)
                st123 = 5
            case 2:   // element EE
                done123 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 4:
            switch try r.readBits(2) {
            case 0:   // EVPresentReactivePower_L3
                _eVPresentReactivePower_L3 = try decodeRationalNumberType(r)
                st123 = 5
            case 1:   // element EE
                done123 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 5:
            switch try r.readBits(1) {
            case 0:   // element EE
                done123 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        default:
            done123 = true
        }
    }
    return Scheduled_AC_CLReqControlModeType(eVTargetEnergyRequest: _eVTargetEnergyRequest, eVMaximumEnergyRequest: _eVMaximumEnergyRequest, eVMinimumEnergyRequest: _eVMinimumEnergyRequest, eVMaximumChargePower: _eVMaximumChargePower, eVMaximumChargePower_L2: _eVMaximumChargePower_L2, eVMaximumChargePower_L3: _eVMaximumChargePower_L3, eVMinimumChargePower: _eVMinimumChargePower, eVMinimumChargePower_L2: _eVMinimumChargePower_L2, eVMinimumChargePower_L3: _eVMinimumChargePower_L3, eVPresentActivePower: _eVPresentActivePower, eVPresentActivePower_L2: _eVPresentActivePower_L2, eVPresentActivePower_L3: _eVPresentActivePower_L3, eVPresentReactivePower: _eVPresentReactivePower, eVPresentReactivePower_L2: _eVPresentReactivePower_L2, eVPresentReactivePower_L3: _eVPresentReactivePower_L3)
}
