// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Swift back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import ExiRuntime

internal func toJSONActivePowerSupportCLResType(_ value: ActivePowerSupportCLResType) throws -> JsonObject {

    let json = JsonObject()

    json["@type"] = JsonValue.of("ActivePowerSupportCLResType")

    if let v = value.frequencyDroop {
        json["frequencyDroop"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.voltWatt {
        json["voltWatt"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.constantWatt {
        json["constantWatt"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.limitMaxDischargePower {
        json["limitMaxDischargePower"] = try AcDerSaeCodecJson.toJSON(v)
    }

    return json
}

internal func parseJSONActivePowerSupportCLResType(_ json: JsonObject) throws -> ActivePowerSupportCLResType {

    return ActivePowerSupportCLResType(
        frequencyDroop: try JsonPrimitives.optional(json, "frequencyDroop").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "ActivePowerSupportCLResType.frequencyDroop"), "frequencyDroop", "ActivePowerSupportCLResType") as FrequencyDroopType },
        voltWatt: try JsonPrimitives.optional(json, "voltWatt").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "ActivePowerSupportCLResType.voltWatt"), "voltWatt", "ActivePowerSupportCLResType") as VoltWattType },
        constantWatt: try JsonPrimitives.optional(json, "constantWatt").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "ActivePowerSupportCLResType.constantWatt"), "constantWatt", "ActivePowerSupportCLResType") as ConstantWattType },
        limitMaxDischargePower: try JsonPrimitives.optional(json, "limitMaxDischargePower").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "ActivePowerSupportCLResType.limitMaxDischargePower"), "limitMaxDischargePower", "ActivePowerSupportCLResType") as LimitMaxDischargePowerType }
    )
}

