// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Swift back end). Do not edit by hand.

import ExiRuntime

internal func toJSONDER_Scheduled_AC_CLReqControlModeType(_ value: DER_Scheduled_AC_CLReqControlModeType) throws -> JsonObject {

    let json = JsonObject()

    json["@type"] = JsonValue.of("DER_Scheduled_AC_CLReqControlModeType")

    if let v = value.eVTargetEnergyRequest {
        json["evTargetEnergyRequest"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.eVMaximumEnergyRequest {
        json["evMaximumEnergyRequest"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.eVMinimumEnergyRequest {
        json["evMinimumEnergyRequest"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.eVMaximumChargePower {
        json["evMaximumChargePower"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.eVMaximumChargePower_L2 {
        json["evMaximumChargePower_L2"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.eVMaximumChargePower_L3 {
        json["evMaximumChargePower_L3"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.eVMinimumChargePower {
        json["evMinimumChargePower"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.eVMinimumChargePower_L2 {
        json["evMinimumChargePower_L2"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.eVMinimumChargePower_L3 {
        json["evMinimumChargePower_L3"] = try AcDerSaeCodecJson.toJSON(v)
    }

    json["evPresentActivePower"] = try AcDerSaeCodecJson.toJSON(value.eVPresentActivePower)
    if let v = value.eVPresentActivePower_L2 {
        json["evPresentActivePower_L2"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.eVPresentActivePower_L3 {
        json["evPresentActivePower_L3"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.eVPresentReactivePower {
        json["evPresentReactivePower"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.eVPresentReactivePower_L2 {
        json["evPresentReactivePower_L2"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.eVPresentReactivePower_L3 {
        json["evPresentReactivePower_L3"] = try AcDerSaeCodecJson.toJSON(v)
    }

    json["evPresentVoltage"] = try AcDerSaeCodecJson.toJSON(value.eVPresentVoltage)
    json["evPresentFrequency"] = try AcDerSaeCodecJson.toJSON(value.eVPresentFrequency)
    if let v = value.eVMaximumDischargePower {
        json["evMaximumDischargePower"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.eVMaximumDischargePower_L2 {
        json["evMaximumDischargePower_L2"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.eVMaximumDischargePower_L3 {
        json["evMaximumDischargePower_L3"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.eVMinimumDischargePower {
        json["evMinimumDischargePower"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.eVMinimumDischargePower_L2 {
        json["evMinimumDischargePower_L2"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.eVMinimumDischargePower_L3 {
        json["evMinimumDischargePower_L3"] = try AcDerSaeCodecJson.toJSON(v)
    }

    json["derOperationalState"] = JsonValue.of(JsonPrimitives.fromEnumeration(value.dEROperationalState))
    json["derConnectionStatus"] = JsonValue.of(JsonPrimitives.fromEnumeration(value.dERConnectionStatus))
    if let v = value.eVApparentPower {
        json["evApparentPower"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.eVReactivePower {
        json["evReactivePower"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.eVExcitation {
        json["evExcitation"] = try AcDerSaeCodecJson.toJSON(v)
    }

    json["evUpdateTime"] = JsonValue.of(JsonPrimitives.fromUInt64(value.eVUpdateTime))
    if let v = value.eVMinimumChargingDuration {
        json["evMinimumChargingDuration"] = JsonValue.of(v)
    }

    if let v = value.eVDurationMaximumChargeRate {
        json["evDurationMaximumChargeRate"] = JsonValue.of(v)
    }

    if let v = value.eVDurationMaximumDischargeRate {
        json["evDurationMaximumDischargeRate"] = JsonValue.of(v)
    }

    json["derAlarmStatus"] = JsonValue.of(value.dERAlarmStatus)
    json["enabledModes"] = JsonValue.of(value.enabledModes)
    return json
}

internal func parseJSONDER_Scheduled_AC_CLReqControlModeType(_ json: JsonObject) throws -> DER_Scheduled_AC_CLReqControlModeType {

    return DER_Scheduled_AC_CLReqControlModeType(
        eVTargetEnergyRequest: try JsonPrimitives.optional(json, "evTargetEnergyRequest").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "DER_Scheduled_AC_CLReqControlModeType.evTargetEnergyRequest"), "evTargetEnergyRequest", "DER_Scheduled_AC_CLReqControlModeType") as RationalNumberType },
        eVMaximumEnergyRequest: try JsonPrimitives.optional(json, "evMaximumEnergyRequest").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "DER_Scheduled_AC_CLReqControlModeType.evMaximumEnergyRequest"), "evMaximumEnergyRequest", "DER_Scheduled_AC_CLReqControlModeType") as RationalNumberType },
        eVMinimumEnergyRequest: try JsonPrimitives.optional(json, "evMinimumEnergyRequest").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "DER_Scheduled_AC_CLReqControlModeType.evMinimumEnergyRequest"), "evMinimumEnergyRequest", "DER_Scheduled_AC_CLReqControlModeType") as RationalNumberType },
        eVMaximumChargePower: try JsonPrimitives.optional(json, "evMaximumChargePower").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "DER_Scheduled_AC_CLReqControlModeType.evMaximumChargePower"), "evMaximumChargePower", "DER_Scheduled_AC_CLReqControlModeType") as RationalNumberType },
        eVMaximumChargePower_L2: try JsonPrimitives.optional(json, "evMaximumChargePower_L2").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "DER_Scheduled_AC_CLReqControlModeType.evMaximumChargePower_L2"), "evMaximumChargePower_L2", "DER_Scheduled_AC_CLReqControlModeType") as RationalNumberType },
        eVMaximumChargePower_L3: try JsonPrimitives.optional(json, "evMaximumChargePower_L3").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "DER_Scheduled_AC_CLReqControlModeType.evMaximumChargePower_L3"), "evMaximumChargePower_L3", "DER_Scheduled_AC_CLReqControlModeType") as RationalNumberType },
        eVMinimumChargePower: try JsonPrimitives.optional(json, "evMinimumChargePower").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "DER_Scheduled_AC_CLReqControlModeType.evMinimumChargePower"), "evMinimumChargePower", "DER_Scheduled_AC_CLReqControlModeType") as RationalNumberType },
        eVMinimumChargePower_L2: try JsonPrimitives.optional(json, "evMinimumChargePower_L2").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "DER_Scheduled_AC_CLReqControlModeType.evMinimumChargePower_L2"), "evMinimumChargePower_L2", "DER_Scheduled_AC_CLReqControlModeType") as RationalNumberType },
        eVMinimumChargePower_L3: try JsonPrimitives.optional(json, "evMinimumChargePower_L3").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "DER_Scheduled_AC_CLReqControlModeType.evMinimumChargePower_L3"), "evMinimumChargePower_L3", "DER_Scheduled_AC_CLReqControlModeType") as RationalNumberType },
        eVPresentActivePower: try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON(try JsonPrimitives.required(json, "evPresentActivePower", "DER_Scheduled_AC_CLReqControlModeType"), "DER_Scheduled_AC_CLReqControlModeType.evPresentActivePower"), "evPresentActivePower", "DER_Scheduled_AC_CLReqControlModeType") as RationalNumberType,
        eVPresentActivePower_L2: try JsonPrimitives.optional(json, "evPresentActivePower_L2").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "DER_Scheduled_AC_CLReqControlModeType.evPresentActivePower_L2"), "evPresentActivePower_L2", "DER_Scheduled_AC_CLReqControlModeType") as RationalNumberType },
        eVPresentActivePower_L3: try JsonPrimitives.optional(json, "evPresentActivePower_L3").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "DER_Scheduled_AC_CLReqControlModeType.evPresentActivePower_L3"), "evPresentActivePower_L3", "DER_Scheduled_AC_CLReqControlModeType") as RationalNumberType },
        eVPresentReactivePower: try JsonPrimitives.optional(json, "evPresentReactivePower").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "DER_Scheduled_AC_CLReqControlModeType.evPresentReactivePower"), "evPresentReactivePower", "DER_Scheduled_AC_CLReqControlModeType") as RationalNumberType },
        eVPresentReactivePower_L2: try JsonPrimitives.optional(json, "evPresentReactivePower_L2").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "DER_Scheduled_AC_CLReqControlModeType.evPresentReactivePower_L2"), "evPresentReactivePower_L2", "DER_Scheduled_AC_CLReqControlModeType") as RationalNumberType },
        eVPresentReactivePower_L3: try JsonPrimitives.optional(json, "evPresentReactivePower_L3").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "DER_Scheduled_AC_CLReqControlModeType.evPresentReactivePower_L3"), "evPresentReactivePower_L3", "DER_Scheduled_AC_CLReqControlModeType") as RationalNumberType },
        eVPresentVoltage: try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON(try JsonPrimitives.required(json, "evPresentVoltage", "DER_Scheduled_AC_CLReqControlModeType"), "DER_Scheduled_AC_CLReqControlModeType.evPresentVoltage"), "evPresentVoltage", "DER_Scheduled_AC_CLReqControlModeType") as RationalNumberType,
        eVPresentFrequency: try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON(try JsonPrimitives.required(json, "evPresentFrequency", "DER_Scheduled_AC_CLReqControlModeType"), "DER_Scheduled_AC_CLReqControlModeType.evPresentFrequency"), "evPresentFrequency", "DER_Scheduled_AC_CLReqControlModeType") as RationalNumberType,
        eVMaximumDischargePower: try JsonPrimitives.optional(json, "evMaximumDischargePower").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "DER_Scheduled_AC_CLReqControlModeType.evMaximumDischargePower"), "evMaximumDischargePower", "DER_Scheduled_AC_CLReqControlModeType") as RationalNumberType },
        eVMaximumDischargePower_L2: try JsonPrimitives.optional(json, "evMaximumDischargePower_L2").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "DER_Scheduled_AC_CLReqControlModeType.evMaximumDischargePower_L2"), "evMaximumDischargePower_L2", "DER_Scheduled_AC_CLReqControlModeType") as RationalNumberType },
        eVMaximumDischargePower_L3: try JsonPrimitives.optional(json, "evMaximumDischargePower_L3").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "DER_Scheduled_AC_CLReqControlModeType.evMaximumDischargePower_L3"), "evMaximumDischargePower_L3", "DER_Scheduled_AC_CLReqControlModeType") as RationalNumberType },
        eVMinimumDischargePower: try JsonPrimitives.optional(json, "evMinimumDischargePower").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "DER_Scheduled_AC_CLReqControlModeType.evMinimumDischargePower"), "evMinimumDischargePower", "DER_Scheduled_AC_CLReqControlModeType") as RationalNumberType },
        eVMinimumDischargePower_L2: try JsonPrimitives.optional(json, "evMinimumDischargePower_L2").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "DER_Scheduled_AC_CLReqControlModeType.evMinimumDischargePower_L2"), "evMinimumDischargePower_L2", "DER_Scheduled_AC_CLReqControlModeType") as RationalNumberType },
        eVMinimumDischargePower_L3: try JsonPrimitives.optional(json, "evMinimumDischargePower_L3").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "DER_Scheduled_AC_CLReqControlModeType.evMinimumDischargePower_L3"), "evMinimumDischargePower_L3", "DER_Scheduled_AC_CLReqControlModeType") as RationalNumberType },
        dEROperationalState: try JsonPrimitives.enumeration(try JsonPrimitives.required(json, "derOperationalState", "DER_Scheduled_AC_CLReqControlModeType"), "derOperationalState", "DER_Scheduled_AC_CLReqControlModeType", DerOperationalState.self),
        dERConnectionStatus: try JsonPrimitives.enumeration(try JsonPrimitives.required(json, "derConnectionStatus", "DER_Scheduled_AC_CLReqControlModeType"), "derConnectionStatus", "DER_Scheduled_AC_CLReqControlModeType", DerConnectionStatus.self),
        eVApparentPower: try JsonPrimitives.optional(json, "evApparentPower").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "DER_Scheduled_AC_CLReqControlModeType.evApparentPower"), "evApparentPower", "DER_Scheduled_AC_CLReqControlModeType") as EVApparentPowerType },
        eVReactivePower: try JsonPrimitives.optional(json, "evReactivePower").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "DER_Scheduled_AC_CLReqControlModeType.evReactivePower"), "evReactivePower", "DER_Scheduled_AC_CLReqControlModeType") as EVReactivePowerType },
        eVExcitation: try JsonPrimitives.optional(json, "evExcitation").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "DER_Scheduled_AC_CLReqControlModeType.evExcitation"), "evExcitation", "DER_Scheduled_AC_CLReqControlModeType") as EVExcitationType },
        eVUpdateTime: try JsonPrimitives.uint64(try JsonPrimitives.required(json, "evUpdateTime", "DER_Scheduled_AC_CLReqControlModeType"), "evUpdateTime", "DER_Scheduled_AC_CLReqControlModeType"),
        eVMinimumChargingDuration: try JsonPrimitives.optional(json, "evMinimumChargingDuration").map { try JsonPrimitives.uint32($0, "evMinimumChargingDuration", "DER_Scheduled_AC_CLReqControlModeType") },
        eVDurationMaximumChargeRate: try JsonPrimitives.optional(json, "evDurationMaximumChargeRate").map { try JsonPrimitives.uint32($0, "evDurationMaximumChargeRate", "DER_Scheduled_AC_CLReqControlModeType") },
        eVDurationMaximumDischargeRate: try JsonPrimitives.optional(json, "evDurationMaximumDischargeRate").map { try JsonPrimitives.uint32($0, "evDurationMaximumDischargeRate", "DER_Scheduled_AC_CLReqControlModeType") },
        dERAlarmStatus: try JsonPrimitives.uint32(try JsonPrimitives.required(json, "derAlarmStatus", "DER_Scheduled_AC_CLReqControlModeType"), "derAlarmStatus", "DER_Scheduled_AC_CLReqControlModeType"),
        enabledModes: try JsonPrimitives.uint32(try JsonPrimitives.required(json, "enabledModes", "DER_Scheduled_AC_CLReqControlModeType"), "enabledModes", "DER_Scheduled_AC_CLReqControlModeType")
    )
}

