// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Swift back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import ExiRuntime

internal func toJSONEnterServiceCLResType(_ value: EnterServiceCLResType) throws -> JsonObject {

    let json = JsonObject()

    json["@type"] = JsonValue.of("EnterServiceCLResType")

    json["permitService"] = JsonValue.of(value.permitService)
    if let v = value.enterServiceVoltageHigh {
        json["enterServiceVoltageHigh"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.enterServiceVoltageLow {
        json["enterServiceVoltageLow"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.enterServiceFrequencyHigh {
        json["enterServiceFrequencyHigh"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.enterServiceFrequencyLow {
        json["enterServiceFrequencyLow"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.enterServiceDelay {
        json["enterServiceDelay"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.enterServiceRandomizedDelay {
        json["enterServiceRandomizedDelay"] = try AcDerSaeCodecJson.toJSON(v)
    }

    if let v = value.enterServiceRampTime {
        json["enterServiceRampTime"] = try AcDerSaeCodecJson.toJSON(v)
    }

    return json
}

internal func parseJSONEnterServiceCLResType(_ json: JsonObject) throws -> EnterServiceCLResType {

    return EnterServiceCLResType(
        permitService: try JsonPrimitives.bool(try JsonPrimitives.required(json, "permitService", "EnterServiceCLResType"), "permitService", "EnterServiceCLResType"),
        enterServiceVoltageHigh: try JsonPrimitives.optional(json, "enterServiceVoltageHigh").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "EnterServiceCLResType.enterServiceVoltageHigh"), "enterServiceVoltageHigh", "EnterServiceCLResType") as RationalNumberType },
        enterServiceVoltageLow: try JsonPrimitives.optional(json, "enterServiceVoltageLow").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "EnterServiceCLResType.enterServiceVoltageLow"), "enterServiceVoltageLow", "EnterServiceCLResType") as RationalNumberType },
        enterServiceFrequencyHigh: try JsonPrimitives.optional(json, "enterServiceFrequencyHigh").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "EnterServiceCLResType.enterServiceFrequencyHigh"), "enterServiceFrequencyHigh", "EnterServiceCLResType") as RationalNumberType },
        enterServiceFrequencyLow: try JsonPrimitives.optional(json, "enterServiceFrequencyLow").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "EnterServiceCLResType.enterServiceFrequencyLow"), "enterServiceFrequencyLow", "EnterServiceCLResType") as RationalNumberType },
        enterServiceDelay: try JsonPrimitives.optional(json, "enterServiceDelay").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "EnterServiceCLResType.enterServiceDelay"), "enterServiceDelay", "EnterServiceCLResType") as RationalNumberType },
        enterServiceRandomizedDelay: try JsonPrimitives.optional(json, "enterServiceRandomizedDelay").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "EnterServiceCLResType.enterServiceRandomizedDelay"), "enterServiceRandomizedDelay", "EnterServiceCLResType") as RationalNumberType },
        enterServiceRampTime: try JsonPrimitives.optional(json, "enterServiceRampTime").map { try JsonPrimitives.cast(AcDerSaeCodecJson.parseJSON($0, "EnterServiceCLResType.enterServiceRampTime"), "enterServiceRampTime", "EnterServiceCLResType") as RationalNumberType }
    )
}

