// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Kotlin back end). Do not edit by hand.

package cloud.charging.v2g.iso20.acderiec

import cloud.charging.v2g.exi.BitReader
import cloud.charging.v2g.exi.BitWriter
import cloud.charging.v2g.exi.ExiPrimitives

class BPT_Dynamic_AC_CLResControlModeType(
    override val departureTime: UInt?,
    override val minimumSOC: Byte?,
    override val targetSOC: Byte?,
    override val ackMaxDelay: UShort?,
    override val eVSETargetActivePower: RationalNumberType,
    override val eVSETargetActivePower_L2: RationalNumberType?,
    override val eVSETargetActivePower_L3: RationalNumberType?,
    override val eVSETargetReactivePower: RationalNumberType?,
    override val eVSETargetReactivePower_L2: RationalNumberType?,
    override val eVSETargetReactivePower_L3: RationalNumberType?,
    override val eVSEPresentActivePower: RationalNumberType?,
    override val eVSEPresentActivePower_L2: RationalNumberType?,
    override val eVSEPresentActivePower_L3: RationalNumberType?
) : Dynamic_AC_CLResControlModeType(departureTime, minimumSOC, targetSOC, ackMaxDelay, eVSETargetActivePower, eVSETargetActivePower_L2, eVSETargetActivePower_L3, eVSETargetReactivePower, eVSETargetReactivePower_L2, eVSETargetReactivePower_L3, eVSEPresentActivePower, eVSEPresentActivePower_L2, eVSEPresentActivePower_L3)

internal fun encodeBPT_Dynamic_AC_CLResControlModeType(w: BitWriter, msg: BPT_Dynamic_AC_CLResControlModeType) {
    var st160 = 0
    var done160 = false
    while (!done160) {
        when (st160) {
            0 -> {
                if (msg.departureTime != null) {
                    w.writeBits(0u, 3)   // DepartureTime
                    w.writeBits(0u, 1)   // value-start
                    ExiPrimitives.writeUnsignedInteger(w, msg.departureTime!!.toULong())
                    w.writeBits(0u, 1)   // child EE
                    st160 = 1
                } else if (msg.minimumSOC != null) {
                    w.writeBits(1u, 3)   // MinimumSOC
                    w.writeBits(0u, 1)   // value-start
                    w.writeBits(msg.minimumSOC!!.toLong().toUInt(), 7)
                    w.writeBits(0u, 1)   // child EE
                    st160 = 2
                } else if (msg.targetSOC != null) {
                    w.writeBits(2u, 3)   // TargetSOC
                    w.writeBits(0u, 1)   // value-start
                    w.writeBits(msg.targetSOC!!.toLong().toUInt(), 7)
                    w.writeBits(0u, 1)   // child EE
                    st160 = 3
                } else if (msg.ackMaxDelay != null) {
                    w.writeBits(3u, 3)   // AckMaxDelay
                    w.writeBits(0u, 1)   // value-start
                    ExiPrimitives.writeUnsignedInteger(w, msg.ackMaxDelay!!.toULong())
                    w.writeBits(0u, 1)   // child EE
                    st160 = 4
                } else {
                    w.writeBits(4u, 3)   // SE(EVSETargetActivePower)
                    encodeRationalNumberType(w, msg.eVSETargetActivePower)
                    done160 = true
                }
            }
            1 -> {
                if (msg.minimumSOC != null) {
                    w.writeBits(0u, 3)   // MinimumSOC
                    w.writeBits(0u, 1)   // value-start
                    w.writeBits(msg.minimumSOC!!.toLong().toUInt(), 7)
                    w.writeBits(0u, 1)   // child EE
                    st160 = 2
                } else if (msg.targetSOC != null) {
                    w.writeBits(1u, 3)   // TargetSOC
                    w.writeBits(0u, 1)   // value-start
                    w.writeBits(msg.targetSOC!!.toLong().toUInt(), 7)
                    w.writeBits(0u, 1)   // child EE
                    st160 = 3
                } else if (msg.ackMaxDelay != null) {
                    w.writeBits(2u, 3)   // AckMaxDelay
                    w.writeBits(0u, 1)   // value-start
                    ExiPrimitives.writeUnsignedInteger(w, msg.ackMaxDelay!!.toULong())
                    w.writeBits(0u, 1)   // child EE
                    st160 = 4
                } else {
                    w.writeBits(3u, 3)   // SE(EVSETargetActivePower)
                    encodeRationalNumberType(w, msg.eVSETargetActivePower)
                    done160 = true
                }
            }
            2 -> {
                if (msg.targetSOC != null) {
                    w.writeBits(0u, 2)   // TargetSOC
                    w.writeBits(0u, 1)   // value-start
                    w.writeBits(msg.targetSOC!!.toLong().toUInt(), 7)
                    w.writeBits(0u, 1)   // child EE
                    st160 = 3
                } else if (msg.ackMaxDelay != null) {
                    w.writeBits(1u, 2)   // AckMaxDelay
                    w.writeBits(0u, 1)   // value-start
                    ExiPrimitives.writeUnsignedInteger(w, msg.ackMaxDelay!!.toULong())
                    w.writeBits(0u, 1)   // child EE
                    st160 = 4
                } else {
                    w.writeBits(2u, 2)   // SE(EVSETargetActivePower)
                    encodeRationalNumberType(w, msg.eVSETargetActivePower)
                    done160 = true
                }
            }
            3 -> {
                if (msg.ackMaxDelay != null) {
                    w.writeBits(0u, 2)   // AckMaxDelay
                    w.writeBits(0u, 1)   // value-start
                    ExiPrimitives.writeUnsignedInteger(w, msg.ackMaxDelay!!.toULong())
                    w.writeBits(0u, 1)   // child EE
                    st160 = 4
                } else {
                    w.writeBits(1u, 2)   // SE(EVSETargetActivePower)
                    encodeRationalNumberType(w, msg.eVSETargetActivePower)
                    done160 = true
                }
            }
            4 -> {
                w.writeBits(0u, 1)   // SE(EVSETargetActivePower)
                encodeRationalNumberType(w, msg.eVSETargetActivePower)
                done160 = true
            }
        }
    }
    var st161 = 0
    var done161 = false
    while (!done161) {
        when (st161) {
            0 -> {
                if (msg.eVSETargetActivePower_L2 != null) {
                    w.writeBits(0u, 4)   // EVSETargetActivePower_L2
                    encodeRationalNumberType(w, msg.eVSETargetActivePower_L2!!)
                    st161 = 1
                } else if (msg.eVSETargetActivePower_L3 != null) {
                    w.writeBits(1u, 4)   // EVSETargetActivePower_L3
                    encodeRationalNumberType(w, msg.eVSETargetActivePower_L3!!)
                    st161 = 2
                } else if (msg.eVSETargetReactivePower != null) {
                    w.writeBits(2u, 4)   // EVSETargetReactivePower
                    encodeRationalNumberType(w, msg.eVSETargetReactivePower!!)
                    st161 = 3
                } else if (msg.eVSETargetReactivePower_L2 != null) {
                    w.writeBits(3u, 4)   // EVSETargetReactivePower_L2
                    encodeRationalNumberType(w, msg.eVSETargetReactivePower_L2!!)
                    st161 = 4
                } else if (msg.eVSETargetReactivePower_L3 != null) {
                    w.writeBits(4u, 4)   // EVSETargetReactivePower_L3
                    encodeRationalNumberType(w, msg.eVSETargetReactivePower_L3!!)
                    st161 = 5
                } else if (msg.eVSEPresentActivePower != null) {
                    w.writeBits(5u, 4)   // EVSEPresentActivePower
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower!!)
                    st161 = 6
                } else if (msg.eVSEPresentActivePower_L2 != null) {
                    w.writeBits(6u, 4)   // EVSEPresentActivePower_L2
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower_L2!!)
                    st161 = 7
                } else if (msg.eVSEPresentActivePower_L3 != null) {
                    w.writeBits(7u, 4)   // EVSEPresentActivePower_L3
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower_L3!!)
                    st161 = 8
                } else {
                    w.writeBits(8u, 4)   // element EE
                    done161 = true
                }
            }
            1 -> {
                if (msg.eVSETargetActivePower_L3 != null) {
                    w.writeBits(0u, 4)   // EVSETargetActivePower_L3
                    encodeRationalNumberType(w, msg.eVSETargetActivePower_L3!!)
                    st161 = 2
                } else if (msg.eVSETargetReactivePower != null) {
                    w.writeBits(1u, 4)   // EVSETargetReactivePower
                    encodeRationalNumberType(w, msg.eVSETargetReactivePower!!)
                    st161 = 3
                } else if (msg.eVSETargetReactivePower_L2 != null) {
                    w.writeBits(2u, 4)   // EVSETargetReactivePower_L2
                    encodeRationalNumberType(w, msg.eVSETargetReactivePower_L2!!)
                    st161 = 4
                } else if (msg.eVSETargetReactivePower_L3 != null) {
                    w.writeBits(3u, 4)   // EVSETargetReactivePower_L3
                    encodeRationalNumberType(w, msg.eVSETargetReactivePower_L3!!)
                    st161 = 5
                } else if (msg.eVSEPresentActivePower != null) {
                    w.writeBits(4u, 4)   // EVSEPresentActivePower
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower!!)
                    st161 = 6
                } else if (msg.eVSEPresentActivePower_L2 != null) {
                    w.writeBits(5u, 4)   // EVSEPresentActivePower_L2
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower_L2!!)
                    st161 = 7
                } else if (msg.eVSEPresentActivePower_L3 != null) {
                    w.writeBits(6u, 4)   // EVSEPresentActivePower_L3
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower_L3!!)
                    st161 = 8
                } else {
                    w.writeBits(7u, 4)   // element EE
                    done161 = true
                }
            }
            2 -> {
                if (msg.eVSETargetReactivePower != null) {
                    w.writeBits(0u, 3)   // EVSETargetReactivePower
                    encodeRationalNumberType(w, msg.eVSETargetReactivePower!!)
                    st161 = 3
                } else if (msg.eVSETargetReactivePower_L2 != null) {
                    w.writeBits(1u, 3)   // EVSETargetReactivePower_L2
                    encodeRationalNumberType(w, msg.eVSETargetReactivePower_L2!!)
                    st161 = 4
                } else if (msg.eVSETargetReactivePower_L3 != null) {
                    w.writeBits(2u, 3)   // EVSETargetReactivePower_L3
                    encodeRationalNumberType(w, msg.eVSETargetReactivePower_L3!!)
                    st161 = 5
                } else if (msg.eVSEPresentActivePower != null) {
                    w.writeBits(3u, 3)   // EVSEPresentActivePower
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower!!)
                    st161 = 6
                } else if (msg.eVSEPresentActivePower_L2 != null) {
                    w.writeBits(4u, 3)   // EVSEPresentActivePower_L2
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower_L2!!)
                    st161 = 7
                } else if (msg.eVSEPresentActivePower_L3 != null) {
                    w.writeBits(5u, 3)   // EVSEPresentActivePower_L3
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower_L3!!)
                    st161 = 8
                } else {
                    w.writeBits(6u, 3)   // element EE
                    done161 = true
                }
            }
            3 -> {
                if (msg.eVSETargetReactivePower_L2 != null) {
                    w.writeBits(0u, 3)   // EVSETargetReactivePower_L2
                    encodeRationalNumberType(w, msg.eVSETargetReactivePower_L2!!)
                    st161 = 4
                } else if (msg.eVSETargetReactivePower_L3 != null) {
                    w.writeBits(1u, 3)   // EVSETargetReactivePower_L3
                    encodeRationalNumberType(w, msg.eVSETargetReactivePower_L3!!)
                    st161 = 5
                } else if (msg.eVSEPresentActivePower != null) {
                    w.writeBits(2u, 3)   // EVSEPresentActivePower
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower!!)
                    st161 = 6
                } else if (msg.eVSEPresentActivePower_L2 != null) {
                    w.writeBits(3u, 3)   // EVSEPresentActivePower_L2
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower_L2!!)
                    st161 = 7
                } else if (msg.eVSEPresentActivePower_L3 != null) {
                    w.writeBits(4u, 3)   // EVSEPresentActivePower_L3
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower_L3!!)
                    st161 = 8
                } else {
                    w.writeBits(5u, 3)   // element EE
                    done161 = true
                }
            }
            4 -> {
                if (msg.eVSETargetReactivePower_L3 != null) {
                    w.writeBits(0u, 3)   // EVSETargetReactivePower_L3
                    encodeRationalNumberType(w, msg.eVSETargetReactivePower_L3!!)
                    st161 = 5
                } else if (msg.eVSEPresentActivePower != null) {
                    w.writeBits(1u, 3)   // EVSEPresentActivePower
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower!!)
                    st161 = 6
                } else if (msg.eVSEPresentActivePower_L2 != null) {
                    w.writeBits(2u, 3)   // EVSEPresentActivePower_L2
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower_L2!!)
                    st161 = 7
                } else if (msg.eVSEPresentActivePower_L3 != null) {
                    w.writeBits(3u, 3)   // EVSEPresentActivePower_L3
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower_L3!!)
                    st161 = 8
                } else {
                    w.writeBits(4u, 3)   // element EE
                    done161 = true
                }
            }
            5 -> {
                if (msg.eVSEPresentActivePower != null) {
                    w.writeBits(0u, 3)   // EVSEPresentActivePower
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower!!)
                    st161 = 6
                } else if (msg.eVSEPresentActivePower_L2 != null) {
                    w.writeBits(1u, 3)   // EVSEPresentActivePower_L2
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower_L2!!)
                    st161 = 7
                } else if (msg.eVSEPresentActivePower_L3 != null) {
                    w.writeBits(2u, 3)   // EVSEPresentActivePower_L3
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower_L3!!)
                    st161 = 8
                } else {
                    w.writeBits(3u, 3)   // element EE
                    done161 = true
                }
            }
            6 -> {
                if (msg.eVSEPresentActivePower_L2 != null) {
                    w.writeBits(0u, 2)   // EVSEPresentActivePower_L2
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower_L2!!)
                    st161 = 7
                } else if (msg.eVSEPresentActivePower_L3 != null) {
                    w.writeBits(1u, 2)   // EVSEPresentActivePower_L3
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower_L3!!)
                    st161 = 8
                } else {
                    w.writeBits(2u, 2)   // element EE
                    done161 = true
                }
            }
            7 -> {
                if (msg.eVSEPresentActivePower_L3 != null) {
                    w.writeBits(0u, 2)   // EVSEPresentActivePower_L3
                    encodeRationalNumberType(w, msg.eVSEPresentActivePower_L3!!)
                    st161 = 8
                } else {
                    w.writeBits(1u, 2)   // element EE
                    done161 = true
                }
            }
            8 -> {
                w.writeBits(0u, 1)   // element EE
                done161 = true
            }
        }
    }
}

internal fun decodeBPT_Dynamic_AC_CLResControlModeType(r: BitReader): BPT_Dynamic_AC_CLResControlModeType {
    var _departureTime: UInt? = null
    var _minimumSOC: Byte? = null
    var _targetSOC: Byte? = null
    var _ackMaxDelay: UShort? = null
    var _eVSETargetActivePower: RationalNumberType? = null
    var st162 = 0
    var done162 = false
    while (!done162) {
        when (st162) {
            0 -> {
                when (r.readBits(3)) {
                    0u -> {
                        r.readBits(1)   // value-start
                        _departureTime = ExiPrimitives.readUnsignedInteger(r).toUInt()
                        r.readBits(1)   // child EE
                        st162 = 1
                    }
                    1u -> {
                        r.readBits(1)   // value-start
                        _minimumSOC = r.readBits(7).toByte()
                        r.readBits(1)   // child EE
                        st162 = 2
                    }
                    2u -> {
                        r.readBits(1)   // value-start
                        _targetSOC = r.readBits(7).toByte()
                        r.readBits(1)   // child EE
                        st162 = 3
                    }
                    3u -> {
                        r.readBits(1)   // value-start
                        _ackMaxDelay = ExiPrimitives.readUnsignedInteger(r).toUShort()
                        r.readBits(1)   // child EE
                        st162 = 4
                    }
                    4u -> {   // SE(EVSETargetActivePower)
                        _eVSETargetActivePower = decodeRationalNumberType(r)
                        done162 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            1 -> {
                when (r.readBits(3)) {
                    0u -> {
                        r.readBits(1)   // value-start
                        _minimumSOC = r.readBits(7).toByte()
                        r.readBits(1)   // child EE
                        st162 = 2
                    }
                    1u -> {
                        r.readBits(1)   // value-start
                        _targetSOC = r.readBits(7).toByte()
                        r.readBits(1)   // child EE
                        st162 = 3
                    }
                    2u -> {
                        r.readBits(1)   // value-start
                        _ackMaxDelay = ExiPrimitives.readUnsignedInteger(r).toUShort()
                        r.readBits(1)   // child EE
                        st162 = 4
                    }
                    3u -> {   // SE(EVSETargetActivePower)
                        _eVSETargetActivePower = decodeRationalNumberType(r)
                        done162 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            2 -> {
                when (r.readBits(2)) {
                    0u -> {
                        r.readBits(1)   // value-start
                        _targetSOC = r.readBits(7).toByte()
                        r.readBits(1)   // child EE
                        st162 = 3
                    }
                    1u -> {
                        r.readBits(1)   // value-start
                        _ackMaxDelay = ExiPrimitives.readUnsignedInteger(r).toUShort()
                        r.readBits(1)   // child EE
                        st162 = 4
                    }
                    2u -> {   // SE(EVSETargetActivePower)
                        _eVSETargetActivePower = decodeRationalNumberType(r)
                        done162 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            3 -> {
                when (r.readBits(2)) {
                    0u -> {
                        r.readBits(1)   // value-start
                        _ackMaxDelay = ExiPrimitives.readUnsignedInteger(r).toUShort()
                        r.readBits(1)   // child EE
                        st162 = 4
                    }
                    1u -> {   // SE(EVSETargetActivePower)
                        _eVSETargetActivePower = decodeRationalNumberType(r)
                        done162 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            4 -> {
                when (r.readBits(1)) {
                    0u -> {   // SE(EVSETargetActivePower)
                        _eVSETargetActivePower = decodeRationalNumberType(r)
                        done162 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
        }
    }
    var _eVSETargetActivePower_L2: RationalNumberType? = null
    var _eVSETargetActivePower_L3: RationalNumberType? = null
    var _eVSETargetReactivePower: RationalNumberType? = null
    var _eVSETargetReactivePower_L2: RationalNumberType? = null
    var _eVSETargetReactivePower_L3: RationalNumberType? = null
    var _eVSEPresentActivePower: RationalNumberType? = null
    var _eVSEPresentActivePower_L2: RationalNumberType? = null
    var _eVSEPresentActivePower_L3: RationalNumberType? = null
    var st163 = 0
    var done163 = false
    while (!done163) {
        when (st163) {
            0 -> {
                when (r.readBits(4)) {
                    0u -> {
                        _eVSETargetActivePower_L2 = decodeRationalNumberType(r)
                        st163 = 1
                    }
                    1u -> {
                        _eVSETargetActivePower_L3 = decodeRationalNumberType(r)
                        st163 = 2
                    }
                    2u -> {
                        _eVSETargetReactivePower = decodeRationalNumberType(r)
                        st163 = 3
                    }
                    3u -> {
                        _eVSETargetReactivePower_L2 = decodeRationalNumberType(r)
                        st163 = 4
                    }
                    4u -> {
                        _eVSETargetReactivePower_L3 = decodeRationalNumberType(r)
                        st163 = 5
                    }
                    5u -> {
                        _eVSEPresentActivePower = decodeRationalNumberType(r)
                        st163 = 6
                    }
                    6u -> {
                        _eVSEPresentActivePower_L2 = decodeRationalNumberType(r)
                        st163 = 7
                    }
                    7u -> {
                        _eVSEPresentActivePower_L3 = decodeRationalNumberType(r)
                        st163 = 8
                    }
                    8u -> done163 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            1 -> {
                when (r.readBits(4)) {
                    0u -> {
                        _eVSETargetActivePower_L3 = decodeRationalNumberType(r)
                        st163 = 2
                    }
                    1u -> {
                        _eVSETargetReactivePower = decodeRationalNumberType(r)
                        st163 = 3
                    }
                    2u -> {
                        _eVSETargetReactivePower_L2 = decodeRationalNumberType(r)
                        st163 = 4
                    }
                    3u -> {
                        _eVSETargetReactivePower_L3 = decodeRationalNumberType(r)
                        st163 = 5
                    }
                    4u -> {
                        _eVSEPresentActivePower = decodeRationalNumberType(r)
                        st163 = 6
                    }
                    5u -> {
                        _eVSEPresentActivePower_L2 = decodeRationalNumberType(r)
                        st163 = 7
                    }
                    6u -> {
                        _eVSEPresentActivePower_L3 = decodeRationalNumberType(r)
                        st163 = 8
                    }
                    7u -> done163 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            2 -> {
                when (r.readBits(3)) {
                    0u -> {
                        _eVSETargetReactivePower = decodeRationalNumberType(r)
                        st163 = 3
                    }
                    1u -> {
                        _eVSETargetReactivePower_L2 = decodeRationalNumberType(r)
                        st163 = 4
                    }
                    2u -> {
                        _eVSETargetReactivePower_L3 = decodeRationalNumberType(r)
                        st163 = 5
                    }
                    3u -> {
                        _eVSEPresentActivePower = decodeRationalNumberType(r)
                        st163 = 6
                    }
                    4u -> {
                        _eVSEPresentActivePower_L2 = decodeRationalNumberType(r)
                        st163 = 7
                    }
                    5u -> {
                        _eVSEPresentActivePower_L3 = decodeRationalNumberType(r)
                        st163 = 8
                    }
                    6u -> done163 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            3 -> {
                when (r.readBits(3)) {
                    0u -> {
                        _eVSETargetReactivePower_L2 = decodeRationalNumberType(r)
                        st163 = 4
                    }
                    1u -> {
                        _eVSETargetReactivePower_L3 = decodeRationalNumberType(r)
                        st163 = 5
                    }
                    2u -> {
                        _eVSEPresentActivePower = decodeRationalNumberType(r)
                        st163 = 6
                    }
                    3u -> {
                        _eVSEPresentActivePower_L2 = decodeRationalNumberType(r)
                        st163 = 7
                    }
                    4u -> {
                        _eVSEPresentActivePower_L3 = decodeRationalNumberType(r)
                        st163 = 8
                    }
                    5u -> done163 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            4 -> {
                when (r.readBits(3)) {
                    0u -> {
                        _eVSETargetReactivePower_L3 = decodeRationalNumberType(r)
                        st163 = 5
                    }
                    1u -> {
                        _eVSEPresentActivePower = decodeRationalNumberType(r)
                        st163 = 6
                    }
                    2u -> {
                        _eVSEPresentActivePower_L2 = decodeRationalNumberType(r)
                        st163 = 7
                    }
                    3u -> {
                        _eVSEPresentActivePower_L3 = decodeRationalNumberType(r)
                        st163 = 8
                    }
                    4u -> done163 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            5 -> {
                when (r.readBits(3)) {
                    0u -> {
                        _eVSEPresentActivePower = decodeRationalNumberType(r)
                        st163 = 6
                    }
                    1u -> {
                        _eVSEPresentActivePower_L2 = decodeRationalNumberType(r)
                        st163 = 7
                    }
                    2u -> {
                        _eVSEPresentActivePower_L3 = decodeRationalNumberType(r)
                        st163 = 8
                    }
                    3u -> done163 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            6 -> {
                when (r.readBits(2)) {
                    0u -> {
                        _eVSEPresentActivePower_L2 = decodeRationalNumberType(r)
                        st163 = 7
                    }
                    1u -> {
                        _eVSEPresentActivePower_L3 = decodeRationalNumberType(r)
                        st163 = 8
                    }
                    2u -> done163 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            7 -> {
                when (r.readBits(2)) {
                    0u -> {
                        _eVSEPresentActivePower_L3 = decodeRationalNumberType(r)
                        st163 = 8
                    }
                    1u -> done163 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            8 -> {
                when (r.readBits(1)) {
                    0u -> done163 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
        }
    }
    return BPT_Dynamic_AC_CLResControlModeType(_departureTime, _minimumSOC, _targetSOC, _ackMaxDelay, _eVSETargetActivePower!!, _eVSETargetActivePower_L2, _eVSETargetActivePower_L3, _eVSETargetReactivePower, _eVSETargetReactivePower_L2, _eVSETargetReactivePower_L3, _eVSEPresentActivePower, _eVSEPresentActivePower_L2, _eVSEPresentActivePower_L3)
}
