// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Kotlin back end). Do not edit by hand.

package cloud.charging.v2g.iso20.acderiec

import cloud.charging.v2g.exi.BitReader
import cloud.charging.v2g.exi.BitWriter

data class DERCurveType(
    val xUnit: CurveDataPointsUnit,
    val yUnit: CurveDataPointsUnit,
    val curveDataPoints: CurveDataPointsListType,
    val minCosPhi: RationalNumberType?,
    val lockValueUnit: LockValueUnit?,
    val lockInValue: RationalNumberType?,
    val lockOutValue: RationalNumberType?,
    val pT1ResponseReactivePower: Boolean,
    val stepResponseTimeConstantReactivePower: RationalNumberType,
    val intentionalDelay: RationalNumberType?
)

internal fun encodeDERCurveType(w: BitWriter, msg: DERCurveType) {
    w.writeBits(0u, 1)   // SE
    w.writeBits(0u, 1)   // value-start
    w.writeBits(msg.xUnit.ordinal.toUInt(), 3)
    w.writeBits(0u, 1)   // child EE
    w.writeBits(0u, 1)   // SE
    w.writeBits(0u, 1)   // value-start
    w.writeBits(msg.yUnit.ordinal.toUInt(), 3)
    w.writeBits(0u, 1)   // child EE
    w.writeBits(0u, 1)   // SE
    encodeCurveDataPointsListType(w, msg.curveDataPoints)
    var st66 = 0
    var done66 = false
    while (!done66) {
        when (st66) {
            0 -> {
                if (msg.minCosPhi != null) {
                    w.writeBits(0u, 3)   // MinCosPhi
                    encodeRationalNumberType(w, msg.minCosPhi!!)
                    st66 = 1
                } else if (msg.lockValueUnit != null) {
                    w.writeBits(1u, 3)   // LockValueUnit
                    w.writeBits(0u, 1)   // value-start
                    w.writeBits(msg.lockValueUnit!!.ordinal.toUInt(), 3)
                    w.writeBits(0u, 1)   // child EE
                    st66 = 2
                } else if (msg.lockInValue != null) {
                    w.writeBits(2u, 3)   // LockInValue
                    encodeRationalNumberType(w, msg.lockInValue!!)
                    st66 = 3
                } else if (msg.lockOutValue != null) {
                    w.writeBits(3u, 3)   // LockOutValue
                    encodeRationalNumberType(w, msg.lockOutValue!!)
                    st66 = 4
                } else {
                    w.writeBits(4u, 3)   // SE(PT1ResponseReactivePower)
                    w.writeBits(0u, 1)   // value-start
                    w.writeBits(if (msg.pT1ResponseReactivePower) 1u else 0u, 1)
                    w.writeBits(0u, 1)   // child EE
                    done66 = true
                }
            }
            1 -> {
                if (msg.lockValueUnit != null) {
                    w.writeBits(0u, 3)   // LockValueUnit
                    w.writeBits(0u, 1)   // value-start
                    w.writeBits(msg.lockValueUnit!!.ordinal.toUInt(), 3)
                    w.writeBits(0u, 1)   // child EE
                    st66 = 2
                } else if (msg.lockInValue != null) {
                    w.writeBits(1u, 3)   // LockInValue
                    encodeRationalNumberType(w, msg.lockInValue!!)
                    st66 = 3
                } else if (msg.lockOutValue != null) {
                    w.writeBits(2u, 3)   // LockOutValue
                    encodeRationalNumberType(w, msg.lockOutValue!!)
                    st66 = 4
                } else {
                    w.writeBits(3u, 3)   // SE(PT1ResponseReactivePower)
                    w.writeBits(0u, 1)   // value-start
                    w.writeBits(if (msg.pT1ResponseReactivePower) 1u else 0u, 1)
                    w.writeBits(0u, 1)   // child EE
                    done66 = true
                }
            }
            2 -> {
                if (msg.lockInValue != null) {
                    w.writeBits(0u, 2)   // LockInValue
                    encodeRationalNumberType(w, msg.lockInValue!!)
                    st66 = 3
                } else if (msg.lockOutValue != null) {
                    w.writeBits(1u, 2)   // LockOutValue
                    encodeRationalNumberType(w, msg.lockOutValue!!)
                    st66 = 4
                } else {
                    w.writeBits(2u, 2)   // SE(PT1ResponseReactivePower)
                    w.writeBits(0u, 1)   // value-start
                    w.writeBits(if (msg.pT1ResponseReactivePower) 1u else 0u, 1)
                    w.writeBits(0u, 1)   // child EE
                    done66 = true
                }
            }
            3 -> {
                if (msg.lockOutValue != null) {
                    w.writeBits(0u, 2)   // LockOutValue
                    encodeRationalNumberType(w, msg.lockOutValue!!)
                    st66 = 4
                } else {
                    w.writeBits(1u, 2)   // SE(PT1ResponseReactivePower)
                    w.writeBits(0u, 1)   // value-start
                    w.writeBits(if (msg.pT1ResponseReactivePower) 1u else 0u, 1)
                    w.writeBits(0u, 1)   // child EE
                    done66 = true
                }
            }
            4 -> {
                w.writeBits(0u, 1)   // SE(PT1ResponseReactivePower)
                w.writeBits(0u, 1)   // value-start
                w.writeBits(if (msg.pT1ResponseReactivePower) 1u else 0u, 1)
                w.writeBits(0u, 1)   // child EE
                done66 = true
            }
        }
    }
    w.writeBits(0u, 1)   // SE
    encodeRationalNumberType(w, msg.stepResponseTimeConstantReactivePower)
    var st67 = 0
    var done67 = false
    while (!done67) {
        when (st67) {
            0 -> {
                if (msg.intentionalDelay != null) {
                    w.writeBits(0u, 2)   // IntentionalDelay
                    encodeRationalNumberType(w, msg.intentionalDelay!!)
                    st67 = 1
                } else {
                    w.writeBits(1u, 2)   // element EE
                    done67 = true
                }
            }
            1 -> {
                w.writeBits(0u, 1)   // element EE
                done67 = true
            }
        }
    }
}

internal fun decodeDERCurveType(r: BitReader): DERCurveType {
    r.readBits(1)   // SE
    r.readBits(1)   // value-start
    val _xUnit = CurveDataPointsUnit.entries[r.readBits(3).toInt()]
    r.readBits(1)   // child EE
    r.readBits(1)   // SE
    r.readBits(1)   // value-start
    val _yUnit = CurveDataPointsUnit.entries[r.readBits(3).toInt()]
    r.readBits(1)   // child EE
    r.readBits(1)   // SE
    val _curveDataPoints = decodeCurveDataPointsListType(r)
    var _minCosPhi: RationalNumberType? = null
    var _lockValueUnit: LockValueUnit? = null
    var _lockInValue: RationalNumberType? = null
    var _lockOutValue: RationalNumberType? = null
    var _pT1ResponseReactivePower: Boolean? = null
    var st68 = 0
    var done68 = false
    while (!done68) {
        when (st68) {
            0 -> {
                when (r.readBits(3)) {
                    0u -> {
                        _minCosPhi = decodeRationalNumberType(r)
                        st68 = 1
                    }
                    1u -> {
                        r.readBits(1)   // value-start
                        _lockValueUnit = LockValueUnit.entries[r.readBits(3).toInt()]
                        r.readBits(1)   // child EE
                        st68 = 2
                    }
                    2u -> {
                        _lockInValue = decodeRationalNumberType(r)
                        st68 = 3
                    }
                    3u -> {
                        _lockOutValue = decodeRationalNumberType(r)
                        st68 = 4
                    }
                    4u -> {   // SE(PT1ResponseReactivePower)
                        r.readBits(1)   // value-start
                        _pT1ResponseReactivePower = r.readBits(1).toInt() != 0
                        r.readBits(1)   // child EE
                        done68 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            1 -> {
                when (r.readBits(3)) {
                    0u -> {
                        r.readBits(1)   // value-start
                        _lockValueUnit = LockValueUnit.entries[r.readBits(3).toInt()]
                        r.readBits(1)   // child EE
                        st68 = 2
                    }
                    1u -> {
                        _lockInValue = decodeRationalNumberType(r)
                        st68 = 3
                    }
                    2u -> {
                        _lockOutValue = decodeRationalNumberType(r)
                        st68 = 4
                    }
                    3u -> {   // SE(PT1ResponseReactivePower)
                        r.readBits(1)   // value-start
                        _pT1ResponseReactivePower = r.readBits(1).toInt() != 0
                        r.readBits(1)   // child EE
                        done68 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            2 -> {
                when (r.readBits(2)) {
                    0u -> {
                        _lockInValue = decodeRationalNumberType(r)
                        st68 = 3
                    }
                    1u -> {
                        _lockOutValue = decodeRationalNumberType(r)
                        st68 = 4
                    }
                    2u -> {   // SE(PT1ResponseReactivePower)
                        r.readBits(1)   // value-start
                        _pT1ResponseReactivePower = r.readBits(1).toInt() != 0
                        r.readBits(1)   // child EE
                        done68 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            3 -> {
                when (r.readBits(2)) {
                    0u -> {
                        _lockOutValue = decodeRationalNumberType(r)
                        st68 = 4
                    }
                    1u -> {   // SE(PT1ResponseReactivePower)
                        r.readBits(1)   // value-start
                        _pT1ResponseReactivePower = r.readBits(1).toInt() != 0
                        r.readBits(1)   // child EE
                        done68 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            4 -> {
                when (r.readBits(1)) {
                    0u -> {   // SE(PT1ResponseReactivePower)
                        r.readBits(1)   // value-start
                        _pT1ResponseReactivePower = r.readBits(1).toInt() != 0
                        r.readBits(1)   // child EE
                        done68 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
        }
    }
    r.readBits(1)   // SE
    val _stepResponseTimeConstantReactivePower = decodeRationalNumberType(r)
    var _intentionalDelay: RationalNumberType? = null
    var st69 = 0
    var done69 = false
    while (!done69) {
        when (st69) {
            0 -> {
                when (r.readBits(2)) {
                    0u -> {
                        _intentionalDelay = decodeRationalNumberType(r)
                        st69 = 1
                    }
                    1u -> done69 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            1 -> {
                when (r.readBits(1)) {
                    0u -> done69 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
        }
    }
    return DERCurveType(_xUnit, _yUnit, _curveDataPoints, _minCosPhi, _lockValueUnit, _lockInValue, _lockOutValue, _pT1ResponseReactivePower!!, _stepResponseTimeConstantReactivePower, _intentionalDelay)
}
