// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Kotlin back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cloud.charging.v2g.iso20.acderiec

import cloud.charging.v2g.exi.JsonArray
import cloud.charging.v2g.exi.JsonLdException
import cloud.charging.v2g.exi.JsonObject
import cloud.charging.v2g.exi.JsonPrimitives
import cloud.charging.v2g.exi.JsonValue

internal fun toJsonDSOQSetpointType(value: DSOQSetpointType): JsonObject {

    val json = JsonObject()

    json["@type"] = JsonValue.of("DSOQSetpointType")

    json["dsoqSetpointValue"] = AcDerIecCodecJson.toJson(value.dSOQSetpointValue)
    value.dSOQSetpointValue_L2?.let { json["dsoqSetpointValue_L2"] = AcDerIecCodecJson.toJson(it) }

    value.dSOQSetpointValue_L3?.let { json["dsoqSetpointValue_L3"] = AcDerIecCodecJson.toJson(it) }

    json["pt1ResponseReactivePower"] = JsonValue.of(value.pT1ResponseReactivePower)
    json["stepResponseTimeConstantReactivePower"] = AcDerIecCodecJson.toJson(value.stepResponseTimeConstantReactivePower)
    return json
}

internal fun parseJsonDSOQSetpointType(json: JsonObject): DSOQSetpointType =
    DSOQSetpointType(
        JsonPrimitives.cast<RationalNumberType>(AcDerIecCodecJson.parseJson(JsonPrimitives.required(json, "dsoqSetpointValue", "DSOQSetpointType"), "DSOQSetpointType.dsoqSetpointValue"), "dsoqSetpointValue", "DSOQSetpointType"),
        JsonPrimitives.optional(json, "dsoqSetpointValue_L2")?.let { JsonPrimitives.cast<RationalNumberType>(AcDerIecCodecJson.parseJson(it, "DSOQSetpointType.dsoqSetpointValue_L2"), "dsoqSetpointValue_L2", "DSOQSetpointType") },
        JsonPrimitives.optional(json, "dsoqSetpointValue_L3")?.let { JsonPrimitives.cast<RationalNumberType>(AcDerIecCodecJson.parseJson(it, "DSOQSetpointType.dsoqSetpointValue_L3"), "dsoqSetpointValue_L3", "DSOQSetpointType") },
        JsonPrimitives.bool(JsonPrimitives.required(json, "pt1ResponseReactivePower", "DSOQSetpointType"), "pt1ResponseReactivePower", "DSOQSetpointType"),
        JsonPrimitives.cast<RationalNumberType>(AcDerIecCodecJson.parseJson(JsonPrimitives.required(json, "stepResponseTimeConstantReactivePower", "DSOQSetpointType"), "DSOQSetpointType.stepResponseTimeConstantReactivePower"), "stepResponseTimeConstantReactivePower", "DSOQSetpointType")
    )

