// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Kotlin back end). Do not edit by hand.

package cloud.charging.v2g.iso20.acderiec

import cloud.charging.v2g.exi.BitReader
import cloud.charging.v2g.exi.BitWriter

data class EVReactivePowerLimitsType(
    val eVMaximumChargeReactivePower: RationalNumberType,
    val eVMaximumChargeReactivePower_L2: RationalNumberType?,
    val eVMaximumChargeReactivePower_L3: RationalNumberType?,
    val eVMinimumChargeReactivePower: RationalNumberType?,
    val eVMinimumChargeReactivePower_L2: RationalNumberType?,
    val eVMinimumChargeReactivePower_L3: RationalNumberType?,
    val eVMaximumDischargeReactivePower: RationalNumberType,
    val eVMaximumDischargeReactivePower_L2: RationalNumberType?,
    val eVMaximumDischargeReactivePower_L3: RationalNumberType?,
    val eVMinimumDischargeReactivePower: RationalNumberType?,
    val eVMinimumDischargeReactivePower_L2: RationalNumberType?,
    val eVMinimumDischargeReactivePower_L3: RationalNumberType?
)

internal fun encodeEVReactivePowerLimitsType(w: BitWriter, msg: EVReactivePowerLimitsType) {
    w.writeBits(0u, 1)   // SE
    encodeRationalNumberType(w, msg.eVMaximumChargeReactivePower)
    var st80 = 0
    var done80 = false
    while (!done80) {
        when (st80) {
            0 -> {
                if (msg.eVMaximumChargeReactivePower_L2 != null) {
                    w.writeBits(0u, 3)   // EVMaximumChargeReactivePower_L2
                    encodeRationalNumberType(w, msg.eVMaximumChargeReactivePower_L2!!)
                    st80 = 1
                } else if (msg.eVMaximumChargeReactivePower_L3 != null) {
                    w.writeBits(1u, 3)   // EVMaximumChargeReactivePower_L3
                    encodeRationalNumberType(w, msg.eVMaximumChargeReactivePower_L3!!)
                    st80 = 2
                } else if (msg.eVMinimumChargeReactivePower != null) {
                    w.writeBits(2u, 3)   // EVMinimumChargeReactivePower
                    encodeRationalNumberType(w, msg.eVMinimumChargeReactivePower!!)
                    st80 = 3
                } else if (msg.eVMinimumChargeReactivePower_L2 != null) {
                    w.writeBits(3u, 3)   // EVMinimumChargeReactivePower_L2
                    encodeRationalNumberType(w, msg.eVMinimumChargeReactivePower_L2!!)
                    st80 = 4
                } else if (msg.eVMinimumChargeReactivePower_L3 != null) {
                    w.writeBits(4u, 3)   // EVMinimumChargeReactivePower_L3
                    encodeRationalNumberType(w, msg.eVMinimumChargeReactivePower_L3!!)
                    st80 = 5
                } else {
                    w.writeBits(5u, 3)   // SE(EVMaximumDischargeReactivePower)
                    encodeRationalNumberType(w, msg.eVMaximumDischargeReactivePower)
                    done80 = true
                }
            }
            1 -> {
                if (msg.eVMaximumChargeReactivePower_L3 != null) {
                    w.writeBits(0u, 3)   // EVMaximumChargeReactivePower_L3
                    encodeRationalNumberType(w, msg.eVMaximumChargeReactivePower_L3!!)
                    st80 = 2
                } else if (msg.eVMinimumChargeReactivePower != null) {
                    w.writeBits(1u, 3)   // EVMinimumChargeReactivePower
                    encodeRationalNumberType(w, msg.eVMinimumChargeReactivePower!!)
                    st80 = 3
                } else if (msg.eVMinimumChargeReactivePower_L2 != null) {
                    w.writeBits(2u, 3)   // EVMinimumChargeReactivePower_L2
                    encodeRationalNumberType(w, msg.eVMinimumChargeReactivePower_L2!!)
                    st80 = 4
                } else if (msg.eVMinimumChargeReactivePower_L3 != null) {
                    w.writeBits(3u, 3)   // EVMinimumChargeReactivePower_L3
                    encodeRationalNumberType(w, msg.eVMinimumChargeReactivePower_L3!!)
                    st80 = 5
                } else {
                    w.writeBits(4u, 3)   // SE(EVMaximumDischargeReactivePower)
                    encodeRationalNumberType(w, msg.eVMaximumDischargeReactivePower)
                    done80 = true
                }
            }
            2 -> {
                if (msg.eVMinimumChargeReactivePower != null) {
                    w.writeBits(0u, 3)   // EVMinimumChargeReactivePower
                    encodeRationalNumberType(w, msg.eVMinimumChargeReactivePower!!)
                    st80 = 3
                } else if (msg.eVMinimumChargeReactivePower_L2 != null) {
                    w.writeBits(1u, 3)   // EVMinimumChargeReactivePower_L2
                    encodeRationalNumberType(w, msg.eVMinimumChargeReactivePower_L2!!)
                    st80 = 4
                } else if (msg.eVMinimumChargeReactivePower_L3 != null) {
                    w.writeBits(2u, 3)   // EVMinimumChargeReactivePower_L3
                    encodeRationalNumberType(w, msg.eVMinimumChargeReactivePower_L3!!)
                    st80 = 5
                } else {
                    w.writeBits(3u, 3)   // SE(EVMaximumDischargeReactivePower)
                    encodeRationalNumberType(w, msg.eVMaximumDischargeReactivePower)
                    done80 = true
                }
            }
            3 -> {
                if (msg.eVMinimumChargeReactivePower_L2 != null) {
                    w.writeBits(0u, 2)   // EVMinimumChargeReactivePower_L2
                    encodeRationalNumberType(w, msg.eVMinimumChargeReactivePower_L2!!)
                    st80 = 4
                } else if (msg.eVMinimumChargeReactivePower_L3 != null) {
                    w.writeBits(1u, 2)   // EVMinimumChargeReactivePower_L3
                    encodeRationalNumberType(w, msg.eVMinimumChargeReactivePower_L3!!)
                    st80 = 5
                } else {
                    w.writeBits(2u, 2)   // SE(EVMaximumDischargeReactivePower)
                    encodeRationalNumberType(w, msg.eVMaximumDischargeReactivePower)
                    done80 = true
                }
            }
            4 -> {
                if (msg.eVMinimumChargeReactivePower_L3 != null) {
                    w.writeBits(0u, 2)   // EVMinimumChargeReactivePower_L3
                    encodeRationalNumberType(w, msg.eVMinimumChargeReactivePower_L3!!)
                    st80 = 5
                } else {
                    w.writeBits(1u, 2)   // SE(EVMaximumDischargeReactivePower)
                    encodeRationalNumberType(w, msg.eVMaximumDischargeReactivePower)
                    done80 = true
                }
            }
            5 -> {
                w.writeBits(0u, 1)   // SE(EVMaximumDischargeReactivePower)
                encodeRationalNumberType(w, msg.eVMaximumDischargeReactivePower)
                done80 = true
            }
        }
    }
    var st81 = 0
    var done81 = false
    while (!done81) {
        when (st81) {
            0 -> {
                if (msg.eVMaximumDischargeReactivePower_L2 != null) {
                    w.writeBits(0u, 3)   // EVMaximumDischargeReactivePower_L2
                    encodeRationalNumberType(w, msg.eVMaximumDischargeReactivePower_L2!!)
                    st81 = 1
                } else if (msg.eVMaximumDischargeReactivePower_L3 != null) {
                    w.writeBits(1u, 3)   // EVMaximumDischargeReactivePower_L3
                    encodeRationalNumberType(w, msg.eVMaximumDischargeReactivePower_L3!!)
                    st81 = 2
                } else if (msg.eVMinimumDischargeReactivePower != null) {
                    w.writeBits(2u, 3)   // EVMinimumDischargeReactivePower
                    encodeRationalNumberType(w, msg.eVMinimumDischargeReactivePower!!)
                    st81 = 3
                } else if (msg.eVMinimumDischargeReactivePower_L2 != null) {
                    w.writeBits(3u, 3)   // EVMinimumDischargeReactivePower_L2
                    encodeRationalNumberType(w, msg.eVMinimumDischargeReactivePower_L2!!)
                    st81 = 4
                } else if (msg.eVMinimumDischargeReactivePower_L3 != null) {
                    w.writeBits(4u, 3)   // EVMinimumDischargeReactivePower_L3
                    encodeRationalNumberType(w, msg.eVMinimumDischargeReactivePower_L3!!)
                    st81 = 5
                } else {
                    w.writeBits(5u, 3)   // element EE
                    done81 = true
                }
            }
            1 -> {
                if (msg.eVMaximumDischargeReactivePower_L3 != null) {
                    w.writeBits(0u, 3)   // EVMaximumDischargeReactivePower_L3
                    encodeRationalNumberType(w, msg.eVMaximumDischargeReactivePower_L3!!)
                    st81 = 2
                } else if (msg.eVMinimumDischargeReactivePower != null) {
                    w.writeBits(1u, 3)   // EVMinimumDischargeReactivePower
                    encodeRationalNumberType(w, msg.eVMinimumDischargeReactivePower!!)
                    st81 = 3
                } else if (msg.eVMinimumDischargeReactivePower_L2 != null) {
                    w.writeBits(2u, 3)   // EVMinimumDischargeReactivePower_L2
                    encodeRationalNumberType(w, msg.eVMinimumDischargeReactivePower_L2!!)
                    st81 = 4
                } else if (msg.eVMinimumDischargeReactivePower_L3 != null) {
                    w.writeBits(3u, 3)   // EVMinimumDischargeReactivePower_L3
                    encodeRationalNumberType(w, msg.eVMinimumDischargeReactivePower_L3!!)
                    st81 = 5
                } else {
                    w.writeBits(4u, 3)   // element EE
                    done81 = true
                }
            }
            2 -> {
                if (msg.eVMinimumDischargeReactivePower != null) {
                    w.writeBits(0u, 3)   // EVMinimumDischargeReactivePower
                    encodeRationalNumberType(w, msg.eVMinimumDischargeReactivePower!!)
                    st81 = 3
                } else if (msg.eVMinimumDischargeReactivePower_L2 != null) {
                    w.writeBits(1u, 3)   // EVMinimumDischargeReactivePower_L2
                    encodeRationalNumberType(w, msg.eVMinimumDischargeReactivePower_L2!!)
                    st81 = 4
                } else if (msg.eVMinimumDischargeReactivePower_L3 != null) {
                    w.writeBits(2u, 3)   // EVMinimumDischargeReactivePower_L3
                    encodeRationalNumberType(w, msg.eVMinimumDischargeReactivePower_L3!!)
                    st81 = 5
                } else {
                    w.writeBits(3u, 3)   // element EE
                    done81 = true
                }
            }
            3 -> {
                if (msg.eVMinimumDischargeReactivePower_L2 != null) {
                    w.writeBits(0u, 2)   // EVMinimumDischargeReactivePower_L2
                    encodeRationalNumberType(w, msg.eVMinimumDischargeReactivePower_L2!!)
                    st81 = 4
                } else if (msg.eVMinimumDischargeReactivePower_L3 != null) {
                    w.writeBits(1u, 2)   // EVMinimumDischargeReactivePower_L3
                    encodeRationalNumberType(w, msg.eVMinimumDischargeReactivePower_L3!!)
                    st81 = 5
                } else {
                    w.writeBits(2u, 2)   // element EE
                    done81 = true
                }
            }
            4 -> {
                if (msg.eVMinimumDischargeReactivePower_L3 != null) {
                    w.writeBits(0u, 2)   // EVMinimumDischargeReactivePower_L3
                    encodeRationalNumberType(w, msg.eVMinimumDischargeReactivePower_L3!!)
                    st81 = 5
                } else {
                    w.writeBits(1u, 2)   // element EE
                    done81 = true
                }
            }
            5 -> {
                w.writeBits(0u, 1)   // element EE
                done81 = true
            }
        }
    }
}

internal fun decodeEVReactivePowerLimitsType(r: BitReader): EVReactivePowerLimitsType {
    r.readBits(1)   // SE
    val _eVMaximumChargeReactivePower = decodeRationalNumberType(r)
    var _eVMaximumChargeReactivePower_L2: RationalNumberType? = null
    var _eVMaximumChargeReactivePower_L3: RationalNumberType? = null
    var _eVMinimumChargeReactivePower: RationalNumberType? = null
    var _eVMinimumChargeReactivePower_L2: RationalNumberType? = null
    var _eVMinimumChargeReactivePower_L3: RationalNumberType? = null
    var _eVMaximumDischargeReactivePower: RationalNumberType? = null
    var st82 = 0
    var done82 = false
    while (!done82) {
        when (st82) {
            0 -> {
                when (r.readBits(3)) {
                    0u -> {
                        _eVMaximumChargeReactivePower_L2 = decodeRationalNumberType(r)
                        st82 = 1
                    }
                    1u -> {
                        _eVMaximumChargeReactivePower_L3 = decodeRationalNumberType(r)
                        st82 = 2
                    }
                    2u -> {
                        _eVMinimumChargeReactivePower = decodeRationalNumberType(r)
                        st82 = 3
                    }
                    3u -> {
                        _eVMinimumChargeReactivePower_L2 = decodeRationalNumberType(r)
                        st82 = 4
                    }
                    4u -> {
                        _eVMinimumChargeReactivePower_L3 = decodeRationalNumberType(r)
                        st82 = 5
                    }
                    5u -> {   // SE(EVMaximumDischargeReactivePower)
                        _eVMaximumDischargeReactivePower = decodeRationalNumberType(r)
                        done82 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            1 -> {
                when (r.readBits(3)) {
                    0u -> {
                        _eVMaximumChargeReactivePower_L3 = decodeRationalNumberType(r)
                        st82 = 2
                    }
                    1u -> {
                        _eVMinimumChargeReactivePower = decodeRationalNumberType(r)
                        st82 = 3
                    }
                    2u -> {
                        _eVMinimumChargeReactivePower_L2 = decodeRationalNumberType(r)
                        st82 = 4
                    }
                    3u -> {
                        _eVMinimumChargeReactivePower_L3 = decodeRationalNumberType(r)
                        st82 = 5
                    }
                    4u -> {   // SE(EVMaximumDischargeReactivePower)
                        _eVMaximumDischargeReactivePower = decodeRationalNumberType(r)
                        done82 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            2 -> {
                when (r.readBits(3)) {
                    0u -> {
                        _eVMinimumChargeReactivePower = decodeRationalNumberType(r)
                        st82 = 3
                    }
                    1u -> {
                        _eVMinimumChargeReactivePower_L2 = decodeRationalNumberType(r)
                        st82 = 4
                    }
                    2u -> {
                        _eVMinimumChargeReactivePower_L3 = decodeRationalNumberType(r)
                        st82 = 5
                    }
                    3u -> {   // SE(EVMaximumDischargeReactivePower)
                        _eVMaximumDischargeReactivePower = decodeRationalNumberType(r)
                        done82 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            3 -> {
                when (r.readBits(2)) {
                    0u -> {
                        _eVMinimumChargeReactivePower_L2 = decodeRationalNumberType(r)
                        st82 = 4
                    }
                    1u -> {
                        _eVMinimumChargeReactivePower_L3 = decodeRationalNumberType(r)
                        st82 = 5
                    }
                    2u -> {   // SE(EVMaximumDischargeReactivePower)
                        _eVMaximumDischargeReactivePower = decodeRationalNumberType(r)
                        done82 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            4 -> {
                when (r.readBits(2)) {
                    0u -> {
                        _eVMinimumChargeReactivePower_L3 = decodeRationalNumberType(r)
                        st82 = 5
                    }
                    1u -> {   // SE(EVMaximumDischargeReactivePower)
                        _eVMaximumDischargeReactivePower = decodeRationalNumberType(r)
                        done82 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            5 -> {
                when (r.readBits(1)) {
                    0u -> {   // SE(EVMaximumDischargeReactivePower)
                        _eVMaximumDischargeReactivePower = decodeRationalNumberType(r)
                        done82 = true
                    }
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
        }
    }
    var _eVMaximumDischargeReactivePower_L2: RationalNumberType? = null
    var _eVMaximumDischargeReactivePower_L3: RationalNumberType? = null
    var _eVMinimumDischargeReactivePower: RationalNumberType? = null
    var _eVMinimumDischargeReactivePower_L2: RationalNumberType? = null
    var _eVMinimumDischargeReactivePower_L3: RationalNumberType? = null
    var st83 = 0
    var done83 = false
    while (!done83) {
        when (st83) {
            0 -> {
                when (r.readBits(3)) {
                    0u -> {
                        _eVMaximumDischargeReactivePower_L2 = decodeRationalNumberType(r)
                        st83 = 1
                    }
                    1u -> {
                        _eVMaximumDischargeReactivePower_L3 = decodeRationalNumberType(r)
                        st83 = 2
                    }
                    2u -> {
                        _eVMinimumDischargeReactivePower = decodeRationalNumberType(r)
                        st83 = 3
                    }
                    3u -> {
                        _eVMinimumDischargeReactivePower_L2 = decodeRationalNumberType(r)
                        st83 = 4
                    }
                    4u -> {
                        _eVMinimumDischargeReactivePower_L3 = decodeRationalNumberType(r)
                        st83 = 5
                    }
                    5u -> done83 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            1 -> {
                when (r.readBits(3)) {
                    0u -> {
                        _eVMaximumDischargeReactivePower_L3 = decodeRationalNumberType(r)
                        st83 = 2
                    }
                    1u -> {
                        _eVMinimumDischargeReactivePower = decodeRationalNumberType(r)
                        st83 = 3
                    }
                    2u -> {
                        _eVMinimumDischargeReactivePower_L2 = decodeRationalNumberType(r)
                        st83 = 4
                    }
                    3u -> {
                        _eVMinimumDischargeReactivePower_L3 = decodeRationalNumberType(r)
                        st83 = 5
                    }
                    4u -> done83 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            2 -> {
                when (r.readBits(3)) {
                    0u -> {
                        _eVMinimumDischargeReactivePower = decodeRationalNumberType(r)
                        st83 = 3
                    }
                    1u -> {
                        _eVMinimumDischargeReactivePower_L2 = decodeRationalNumberType(r)
                        st83 = 4
                    }
                    2u -> {
                        _eVMinimumDischargeReactivePower_L3 = decodeRationalNumberType(r)
                        st83 = 5
                    }
                    3u -> done83 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            3 -> {
                when (r.readBits(2)) {
                    0u -> {
                        _eVMinimumDischargeReactivePower_L2 = decodeRationalNumberType(r)
                        st83 = 4
                    }
                    1u -> {
                        _eVMinimumDischargeReactivePower_L3 = decodeRationalNumberType(r)
                        st83 = 5
                    }
                    2u -> done83 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            4 -> {
                when (r.readBits(2)) {
                    0u -> {
                        _eVMinimumDischargeReactivePower_L3 = decodeRationalNumberType(r)
                        st83 = 5
                    }
                    1u -> done83 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
            5 -> {
                when (r.readBits(1)) {
                    0u -> done83 = true   // element EE
                    else -> throw IllegalArgumentException("invalid optional-run event code")
                }
            }
        }
    }
    return EVReactivePowerLimitsType(_eVMaximumChargeReactivePower, _eVMaximumChargeReactivePower_L2, _eVMaximumChargeReactivePower_L3, _eVMinimumChargeReactivePower, _eVMinimumChargeReactivePower_L2, _eVMinimumChargeReactivePower_L3, _eVMaximumDischargeReactivePower!!, _eVMaximumDischargeReactivePower_L2, _eVMaximumDischargeReactivePower_L3, _eVMinimumDischargeReactivePower, _eVMinimumDischargeReactivePower_L2, _eVMinimumDischargeReactivePower_L3)
}
