// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Swift back end). Do not edit by hand.
// Schema target namespace: cloud.charging.v2g.iso20.ac

import ExiRuntime

public final class AC_CPDResEnergyTransferMode {
    public var eVSEMaximumChargePower: RationalNumberType
    public var eVSEMaximumChargePower_L2: RationalNumberType?
    public var eVSEMaximumChargePower_L3: RationalNumberType?
    public var eVSEMinimumChargePower: RationalNumberType
    public var eVSEMinimumChargePower_L2: RationalNumberType?
    public var eVSEMinimumChargePower_L3: RationalNumberType?
    public var eVSENominalFrequency: RationalNumberType
    public var maximumPowerAsymmetry: RationalNumberType?
    public var eVSEPowerRampLimitation: RationalNumberType?
    public var eVSEPresentActivePower: RationalNumberType?
    public var eVSEPresentActivePower_L2: RationalNumberType?
    public var eVSEPresentActivePower_L3: RationalNumberType?

    public init(eVSEMaximumChargePower: RationalNumberType, eVSEMaximumChargePower_L2: RationalNumberType? = nil, eVSEMaximumChargePower_L3: RationalNumberType? = nil, eVSEMinimumChargePower: RationalNumberType, eVSEMinimumChargePower_L2: RationalNumberType? = nil, eVSEMinimumChargePower_L3: RationalNumberType? = nil, eVSENominalFrequency: RationalNumberType, maximumPowerAsymmetry: RationalNumberType? = nil, eVSEPowerRampLimitation: RationalNumberType? = nil, eVSEPresentActivePower: RationalNumberType? = nil, eVSEPresentActivePower_L2: RationalNumberType? = nil, eVSEPresentActivePower_L3: RationalNumberType? = nil) {
        self.eVSEMaximumChargePower = eVSEMaximumChargePower
        self.eVSEMaximumChargePower_L2 = eVSEMaximumChargePower_L2
        self.eVSEMaximumChargePower_L3 = eVSEMaximumChargePower_L3
        self.eVSEMinimumChargePower = eVSEMinimumChargePower
        self.eVSEMinimumChargePower_L2 = eVSEMinimumChargePower_L2
        self.eVSEMinimumChargePower_L3 = eVSEMinimumChargePower_L3
        self.eVSENominalFrequency = eVSENominalFrequency
        self.maximumPowerAsymmetry = maximumPowerAsymmetry
        self.eVSEPowerRampLimitation = eVSEPowerRampLimitation
        self.eVSEPresentActivePower = eVSEPresentActivePower
        self.eVSEPresentActivePower_L2 = eVSEPresentActivePower_L2
        self.eVSEPresentActivePower_L3 = eVSEPresentActivePower_L3
    }
}

internal func encodeAC_CPDResEnergyTransferMode(_ w: BitWriter, _ msg: AC_CPDResEnergyTransferMode) {
    w.writeBits(0, 1)   // SE
    encodeRationalNumberType(w, msg.eVSEMaximumChargePower)
    var st110 = 0
    var done110 = false
    while !done110 {
        switch st110 {
        case 0:
            if let v = msg.eVSEMaximumChargePower_L2 {
                w.writeBits(0, 2)   // EVSEMaximumChargePower_L2
                encodeRationalNumberType(w, v)
                st110 = 1
            } else if let v = msg.eVSEMaximumChargePower_L3 {
                w.writeBits(1, 2)   // EVSEMaximumChargePower_L3
                encodeRationalNumberType(w, v)
                st110 = 2
            } else {
                w.writeBits(2, 2)   // SE(EVSEMinimumChargePower)
                encodeRationalNumberType(w, msg.eVSEMinimumChargePower)
                done110 = true
            }
        case 1:
            if let v = msg.eVSEMaximumChargePower_L3 {
                w.writeBits(0, 2)   // EVSEMaximumChargePower_L3
                encodeRationalNumberType(w, v)
                st110 = 2
            } else {
                w.writeBits(1, 2)   // SE(EVSEMinimumChargePower)
                encodeRationalNumberType(w, msg.eVSEMinimumChargePower)
                done110 = true
            }
        case 2:
            w.writeBits(0, 1)   // SE(EVSEMinimumChargePower)
            encodeRationalNumberType(w, msg.eVSEMinimumChargePower)
            done110 = true
        default:
            done110 = true
        }
    }
    var st111 = 0
    var done111 = false
    while !done111 {
        switch st111 {
        case 0:
            if let v = msg.eVSEMinimumChargePower_L2 {
                w.writeBits(0, 2)   // EVSEMinimumChargePower_L2
                encodeRationalNumberType(w, v)
                st111 = 1
            } else if let v = msg.eVSEMinimumChargePower_L3 {
                w.writeBits(1, 2)   // EVSEMinimumChargePower_L3
                encodeRationalNumberType(w, v)
                st111 = 2
            } else {
                w.writeBits(2, 2)   // SE(EVSENominalFrequency)
                encodeRationalNumberType(w, msg.eVSENominalFrequency)
                done111 = true
            }
        case 1:
            if let v = msg.eVSEMinimumChargePower_L3 {
                w.writeBits(0, 2)   // EVSEMinimumChargePower_L3
                encodeRationalNumberType(w, v)
                st111 = 2
            } else {
                w.writeBits(1, 2)   // SE(EVSENominalFrequency)
                encodeRationalNumberType(w, msg.eVSENominalFrequency)
                done111 = true
            }
        case 2:
            w.writeBits(0, 1)   // SE(EVSENominalFrequency)
            encodeRationalNumberType(w, msg.eVSENominalFrequency)
            done111 = true
        default:
            done111 = true
        }
    }
    var st112 = 0
    var done112 = false
    while !done112 {
        switch st112 {
        case 0:
            if let v = msg.maximumPowerAsymmetry {
                w.writeBits(0, 3)   // MaximumPowerAsymmetry
                encodeRationalNumberType(w, v)
                st112 = 1
            } else if let v = msg.eVSEPowerRampLimitation {
                w.writeBits(1, 3)   // EVSEPowerRampLimitation
                encodeRationalNumberType(w, v)
                st112 = 2
            } else if let v = msg.eVSEPresentActivePower {
                w.writeBits(2, 3)   // EVSEPresentActivePower
                encodeRationalNumberType(w, v)
                st112 = 3
            } else if let v = msg.eVSEPresentActivePower_L2 {
                w.writeBits(3, 3)   // EVSEPresentActivePower_L2
                encodeRationalNumberType(w, v)
                st112 = 4
            } else if let v = msg.eVSEPresentActivePower_L3 {
                w.writeBits(4, 3)   // EVSEPresentActivePower_L3
                encodeRationalNumberType(w, v)
                st112 = 5
            } else {
                w.writeBits(5, 3)   // element EE
                done112 = true
            }
        case 1:
            if let v = msg.eVSEPowerRampLimitation {
                w.writeBits(0, 3)   // EVSEPowerRampLimitation
                encodeRationalNumberType(w, v)
                st112 = 2
            } else if let v = msg.eVSEPresentActivePower {
                w.writeBits(1, 3)   // EVSEPresentActivePower
                encodeRationalNumberType(w, v)
                st112 = 3
            } else if let v = msg.eVSEPresentActivePower_L2 {
                w.writeBits(2, 3)   // EVSEPresentActivePower_L2
                encodeRationalNumberType(w, v)
                st112 = 4
            } else if let v = msg.eVSEPresentActivePower_L3 {
                w.writeBits(3, 3)   // EVSEPresentActivePower_L3
                encodeRationalNumberType(w, v)
                st112 = 5
            } else {
                w.writeBits(4, 3)   // element EE
                done112 = true
            }
        case 2:
            if let v = msg.eVSEPresentActivePower {
                w.writeBits(0, 3)   // EVSEPresentActivePower
                encodeRationalNumberType(w, v)
                st112 = 3
            } else if let v = msg.eVSEPresentActivePower_L2 {
                w.writeBits(1, 3)   // EVSEPresentActivePower_L2
                encodeRationalNumberType(w, v)
                st112 = 4
            } else if let v = msg.eVSEPresentActivePower_L3 {
                w.writeBits(2, 3)   // EVSEPresentActivePower_L3
                encodeRationalNumberType(w, v)
                st112 = 5
            } else {
                w.writeBits(3, 3)   // element EE
                done112 = true
            }
        case 3:
            if let v = msg.eVSEPresentActivePower_L2 {
                w.writeBits(0, 2)   // EVSEPresentActivePower_L2
                encodeRationalNumberType(w, v)
                st112 = 4
            } else if let v = msg.eVSEPresentActivePower_L3 {
                w.writeBits(1, 2)   // EVSEPresentActivePower_L3
                encodeRationalNumberType(w, v)
                st112 = 5
            } else {
                w.writeBits(2, 2)   // element EE
                done112 = true
            }
        case 4:
            if let v = msg.eVSEPresentActivePower_L3 {
                w.writeBits(0, 2)   // EVSEPresentActivePower_L3
                encodeRationalNumberType(w, v)
                st112 = 5
            } else {
                w.writeBits(1, 2)   // element EE
                done112 = true
            }
        case 5:
            w.writeBits(0, 1)   // element EE
            done112 = true
        default:
            done112 = true
        }
    }
}

internal func decodeAC_CPDResEnergyTransferMode(_ r: BitReader) throws -> AC_CPDResEnergyTransferMode {
    _ = try r.readBits(1)   // SE
    let _eVSEMaximumChargePower = try decodeRationalNumberType(r)
    var _eVSEMaximumChargePower_L2: RationalNumberType? = nil
    var _eVSEMaximumChargePower_L3: RationalNumberType? = nil
    var _eVSEMinimumChargePower: RationalNumberType? = nil
    var st113 = 0
    var done113 = false
    while !done113 {
        switch st113 {
        case 0:
            switch try r.readBits(2) {
            case 0:   // EVSEMaximumChargePower_L2
                _eVSEMaximumChargePower_L2 = try decodeRationalNumberType(r)
                st113 = 1
            case 1:   // EVSEMaximumChargePower_L3
                _eVSEMaximumChargePower_L3 = try decodeRationalNumberType(r)
                st113 = 2
            case 2:   // SE(EVSEMinimumChargePower)
                _eVSEMinimumChargePower = try decodeRationalNumberType(r)
                done113 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 1:
            switch try r.readBits(2) {
            case 0:   // EVSEMaximumChargePower_L3
                _eVSEMaximumChargePower_L3 = try decodeRationalNumberType(r)
                st113 = 2
            case 1:   // SE(EVSEMinimumChargePower)
                _eVSEMinimumChargePower = try decodeRationalNumberType(r)
                done113 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 2:
            switch try r.readBits(1) {
            case 0:   // SE(EVSEMinimumChargePower)
                _eVSEMinimumChargePower = try decodeRationalNumberType(r)
                done113 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        default:
            done113 = true
        }
    }
    guard let _eVSEMinimumChargePower else {
        throw ExiError.invalidEventCode("EVSEMinimumChargePower is required but the element ended")
    }
    var _eVSEMinimumChargePower_L2: RationalNumberType? = nil
    var _eVSEMinimumChargePower_L3: RationalNumberType? = nil
    var _eVSENominalFrequency: RationalNumberType? = nil
    var st114 = 0
    var done114 = false
    while !done114 {
        switch st114 {
        case 0:
            switch try r.readBits(2) {
            case 0:   // EVSEMinimumChargePower_L2
                _eVSEMinimumChargePower_L2 = try decodeRationalNumberType(r)
                st114 = 1
            case 1:   // EVSEMinimumChargePower_L3
                _eVSEMinimumChargePower_L3 = try decodeRationalNumberType(r)
                st114 = 2
            case 2:   // SE(EVSENominalFrequency)
                _eVSENominalFrequency = try decodeRationalNumberType(r)
                done114 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 1:
            switch try r.readBits(2) {
            case 0:   // EVSEMinimumChargePower_L3
                _eVSEMinimumChargePower_L3 = try decodeRationalNumberType(r)
                st114 = 2
            case 1:   // SE(EVSENominalFrequency)
                _eVSENominalFrequency = try decodeRationalNumberType(r)
                done114 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 2:
            switch try r.readBits(1) {
            case 0:   // SE(EVSENominalFrequency)
                _eVSENominalFrequency = try decodeRationalNumberType(r)
                done114 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        default:
            done114 = true
        }
    }
    guard let _eVSENominalFrequency else {
        throw ExiError.invalidEventCode("EVSENominalFrequency is required but the element ended")
    }
    var _maximumPowerAsymmetry: RationalNumberType? = nil
    var _eVSEPowerRampLimitation: RationalNumberType? = nil
    var _eVSEPresentActivePower: RationalNumberType? = nil
    var _eVSEPresentActivePower_L2: RationalNumberType? = nil
    var _eVSEPresentActivePower_L3: RationalNumberType? = nil
    var st115 = 0
    var done115 = false
    while !done115 {
        switch st115 {
        case 0:
            switch try r.readBits(3) {
            case 0:   // MaximumPowerAsymmetry
                _maximumPowerAsymmetry = try decodeRationalNumberType(r)
                st115 = 1
            case 1:   // EVSEPowerRampLimitation
                _eVSEPowerRampLimitation = try decodeRationalNumberType(r)
                st115 = 2
            case 2:   // EVSEPresentActivePower
                _eVSEPresentActivePower = try decodeRationalNumberType(r)
                st115 = 3
            case 3:   // EVSEPresentActivePower_L2
                _eVSEPresentActivePower_L2 = try decodeRationalNumberType(r)
                st115 = 4
            case 4:   // EVSEPresentActivePower_L3
                _eVSEPresentActivePower_L3 = try decodeRationalNumberType(r)
                st115 = 5
            case 5:   // element EE
                done115 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 1:
            switch try r.readBits(3) {
            case 0:   // EVSEPowerRampLimitation
                _eVSEPowerRampLimitation = try decodeRationalNumberType(r)
                st115 = 2
            case 1:   // EVSEPresentActivePower
                _eVSEPresentActivePower = try decodeRationalNumberType(r)
                st115 = 3
            case 2:   // EVSEPresentActivePower_L2
                _eVSEPresentActivePower_L2 = try decodeRationalNumberType(r)
                st115 = 4
            case 3:   // EVSEPresentActivePower_L3
                _eVSEPresentActivePower_L3 = try decodeRationalNumberType(r)
                st115 = 5
            case 4:   // element EE
                done115 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 2:
            switch try r.readBits(3) {
            case 0:   // EVSEPresentActivePower
                _eVSEPresentActivePower = try decodeRationalNumberType(r)
                st115 = 3
            case 1:   // EVSEPresentActivePower_L2
                _eVSEPresentActivePower_L2 = try decodeRationalNumberType(r)
                st115 = 4
            case 2:   // EVSEPresentActivePower_L3
                _eVSEPresentActivePower_L3 = try decodeRationalNumberType(r)
                st115 = 5
            case 3:   // element EE
                done115 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 3:
            switch try r.readBits(2) {
            case 0:   // EVSEPresentActivePower_L2
                _eVSEPresentActivePower_L2 = try decodeRationalNumberType(r)
                st115 = 4
            case 1:   // EVSEPresentActivePower_L3
                _eVSEPresentActivePower_L3 = try decodeRationalNumberType(r)
                st115 = 5
            case 2:   // element EE
                done115 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 4:
            switch try r.readBits(2) {
            case 0:   // EVSEPresentActivePower_L3
                _eVSEPresentActivePower_L3 = try decodeRationalNumberType(r)
                st115 = 5
            case 1:   // element EE
                done115 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 5:
            switch try r.readBits(1) {
            case 0:   // element EE
                done115 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        default:
            done115 = true
        }
    }
    return AC_CPDResEnergyTransferMode(eVSEMaximumChargePower: _eVSEMaximumChargePower, eVSEMaximumChargePower_L2: _eVSEMaximumChargePower_L2, eVSEMaximumChargePower_L3: _eVSEMaximumChargePower_L3, eVSEMinimumChargePower: _eVSEMinimumChargePower, eVSEMinimumChargePower_L2: _eVSEMinimumChargePower_L2, eVSEMinimumChargePower_L3: _eVSEMinimumChargePower_L3, eVSENominalFrequency: _eVSENominalFrequency, maximumPowerAsymmetry: _maximumPowerAsymmetry, eVSEPowerRampLimitation: _eVSEPowerRampLimitation, eVSEPresentActivePower: _eVSEPresentActivePower, eVSEPresentActivePower_L2: _eVSEPresentActivePower_L2, eVSEPresentActivePower_L3: _eVSEPresentActivePower_L3)
}
