// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Swift back end). Do not edit by hand.
// Schema target namespace: cloud.charging.v2g.iso20.ac

import ExiRuntime

public final class DisplayParametersType {
    public var presentSOC: Int8?
    public var minimumSOC: Int8?
    public var targetSOC: Int8?
    public var maximumSOC: Int8?
    public var remainingTimeToMinimumSOC: UInt32?
    public var remainingTimeToTargetSOC: UInt32?
    public var remainingTimeToMaximumSOC: UInt32?
    public var chargingComplete: Bool?
    public var batteryEnergyCapacity: RationalNumberType?
    public var inletHot: Bool?

    public init(presentSOC: Int8? = nil, minimumSOC: Int8? = nil, targetSOC: Int8? = nil, maximumSOC: Int8? = nil, remainingTimeToMinimumSOC: UInt32? = nil, remainingTimeToTargetSOC: UInt32? = nil, remainingTimeToMaximumSOC: UInt32? = nil, chargingComplete: Bool? = nil, batteryEnergyCapacity: RationalNumberType? = nil, inletHot: Bool? = nil) {
        self.presentSOC = presentSOC
        self.minimumSOC = minimumSOC
        self.targetSOC = targetSOC
        self.maximumSOC = maximumSOC
        self.remainingTimeToMinimumSOC = remainingTimeToMinimumSOC
        self.remainingTimeToTargetSOC = remainingTimeToTargetSOC
        self.remainingTimeToMaximumSOC = remainingTimeToMaximumSOC
        self.chargingComplete = chargingComplete
        self.batteryEnergyCapacity = batteryEnergyCapacity
        self.inletHot = inletHot
    }
}

internal func encodeDisplayParametersType(_ w: BitWriter, _ msg: DisplayParametersType) {
    var st78 = 0
    var done78 = false
    while !done78 {
        switch st78 {
        case 0:
            if let v = msg.presentSOC {
                w.writeBits(0, 4)   // PresentSOC
                w.writeBits(0, 1)   // value-start
                w.writeBits(UInt32(v), 7)
                w.writeBits(0, 1)   // child EE
                st78 = 1
            } else if let v = msg.minimumSOC {
                w.writeBits(1, 4)   // MinimumSOC
                w.writeBits(0, 1)   // value-start
                w.writeBits(UInt32(v), 7)
                w.writeBits(0, 1)   // child EE
                st78 = 2
            } else if let v = msg.targetSOC {
                w.writeBits(2, 4)   // TargetSOC
                w.writeBits(0, 1)   // value-start
                w.writeBits(UInt32(v), 7)
                w.writeBits(0, 1)   // child EE
                st78 = 3
            } else if let v = msg.maximumSOC {
                w.writeBits(3, 4)   // MaximumSOC
                w.writeBits(0, 1)   // value-start
                w.writeBits(UInt32(v), 7)
                w.writeBits(0, 1)   // child EE
                st78 = 4
            } else if let v = msg.remainingTimeToMinimumSOC {
                w.writeBits(4, 4)   // RemainingTimeToMinimumSOC
                w.writeBits(0, 1)   // value-start
                ExiPrimitives.writeUnsignedInteger(w, UInt64(v))
                w.writeBits(0, 1)   // child EE
                st78 = 5
            } else if let v = msg.remainingTimeToTargetSOC {
                w.writeBits(5, 4)   // RemainingTimeToTargetSOC
                w.writeBits(0, 1)   // value-start
                ExiPrimitives.writeUnsignedInteger(w, UInt64(v))
                w.writeBits(0, 1)   // child EE
                st78 = 6
            } else if let v = msg.remainingTimeToMaximumSOC {
                w.writeBits(6, 4)   // RemainingTimeToMaximumSOC
                w.writeBits(0, 1)   // value-start
                ExiPrimitives.writeUnsignedInteger(w, UInt64(v))
                w.writeBits(0, 1)   // child EE
                st78 = 7
            } else if let v = msg.chargingComplete {
                w.writeBits(7, 4)   // ChargingComplete
                w.writeBits(0, 1)   // value-start
                w.writeBits(v ? 1 : 0, 1)
                w.writeBits(0, 1)   // child EE
                st78 = 8
            } else if let v = msg.batteryEnergyCapacity {
                w.writeBits(8, 4)   // BatteryEnergyCapacity
                encodeRationalNumberType(w, v)
                st78 = 9
            } else if let v = msg.inletHot {
                w.writeBits(9, 4)   // InletHot
                w.writeBits(0, 1)   // value-start
                w.writeBits(v ? 1 : 0, 1)
                w.writeBits(0, 1)   // child EE
                st78 = 10
            } else {
                w.writeBits(10, 4)   // element EE
                done78 = true
            }
        case 1:
            if let v = msg.minimumSOC {
                w.writeBits(0, 4)   // MinimumSOC
                w.writeBits(0, 1)   // value-start
                w.writeBits(UInt32(v), 7)
                w.writeBits(0, 1)   // child EE
                st78 = 2
            } else if let v = msg.targetSOC {
                w.writeBits(1, 4)   // TargetSOC
                w.writeBits(0, 1)   // value-start
                w.writeBits(UInt32(v), 7)
                w.writeBits(0, 1)   // child EE
                st78 = 3
            } else if let v = msg.maximumSOC {
                w.writeBits(2, 4)   // MaximumSOC
                w.writeBits(0, 1)   // value-start
                w.writeBits(UInt32(v), 7)
                w.writeBits(0, 1)   // child EE
                st78 = 4
            } else if let v = msg.remainingTimeToMinimumSOC {
                w.writeBits(3, 4)   // RemainingTimeToMinimumSOC
                w.writeBits(0, 1)   // value-start
                ExiPrimitives.writeUnsignedInteger(w, UInt64(v))
                w.writeBits(0, 1)   // child EE
                st78 = 5
            } else if let v = msg.remainingTimeToTargetSOC {
                w.writeBits(4, 4)   // RemainingTimeToTargetSOC
                w.writeBits(0, 1)   // value-start
                ExiPrimitives.writeUnsignedInteger(w, UInt64(v))
                w.writeBits(0, 1)   // child EE
                st78 = 6
            } else if let v = msg.remainingTimeToMaximumSOC {
                w.writeBits(5, 4)   // RemainingTimeToMaximumSOC
                w.writeBits(0, 1)   // value-start
                ExiPrimitives.writeUnsignedInteger(w, UInt64(v))
                w.writeBits(0, 1)   // child EE
                st78 = 7
            } else if let v = msg.chargingComplete {
                w.writeBits(6, 4)   // ChargingComplete
                w.writeBits(0, 1)   // value-start
                w.writeBits(v ? 1 : 0, 1)
                w.writeBits(0, 1)   // child EE
                st78 = 8
            } else if let v = msg.batteryEnergyCapacity {
                w.writeBits(7, 4)   // BatteryEnergyCapacity
                encodeRationalNumberType(w, v)
                st78 = 9
            } else if let v = msg.inletHot {
                w.writeBits(8, 4)   // InletHot
                w.writeBits(0, 1)   // value-start
                w.writeBits(v ? 1 : 0, 1)
                w.writeBits(0, 1)   // child EE
                st78 = 10
            } else {
                w.writeBits(9, 4)   // element EE
                done78 = true
            }
        case 2:
            if let v = msg.targetSOC {
                w.writeBits(0, 4)   // TargetSOC
                w.writeBits(0, 1)   // value-start
                w.writeBits(UInt32(v), 7)
                w.writeBits(0, 1)   // child EE
                st78 = 3
            } else if let v = msg.maximumSOC {
                w.writeBits(1, 4)   // MaximumSOC
                w.writeBits(0, 1)   // value-start
                w.writeBits(UInt32(v), 7)
                w.writeBits(0, 1)   // child EE
                st78 = 4
            } else if let v = msg.remainingTimeToMinimumSOC {
                w.writeBits(2, 4)   // RemainingTimeToMinimumSOC
                w.writeBits(0, 1)   // value-start
                ExiPrimitives.writeUnsignedInteger(w, UInt64(v))
                w.writeBits(0, 1)   // child EE
                st78 = 5
            } else if let v = msg.remainingTimeToTargetSOC {
                w.writeBits(3, 4)   // RemainingTimeToTargetSOC
                w.writeBits(0, 1)   // value-start
                ExiPrimitives.writeUnsignedInteger(w, UInt64(v))
                w.writeBits(0, 1)   // child EE
                st78 = 6
            } else if let v = msg.remainingTimeToMaximumSOC {
                w.writeBits(4, 4)   // RemainingTimeToMaximumSOC
                w.writeBits(0, 1)   // value-start
                ExiPrimitives.writeUnsignedInteger(w, UInt64(v))
                w.writeBits(0, 1)   // child EE
                st78 = 7
            } else if let v = msg.chargingComplete {
                w.writeBits(5, 4)   // ChargingComplete
                w.writeBits(0, 1)   // value-start
                w.writeBits(v ? 1 : 0, 1)
                w.writeBits(0, 1)   // child EE
                st78 = 8
            } else if let v = msg.batteryEnergyCapacity {
                w.writeBits(6, 4)   // BatteryEnergyCapacity
                encodeRationalNumberType(w, v)
                st78 = 9
            } else if let v = msg.inletHot {
                w.writeBits(7, 4)   // InletHot
                w.writeBits(0, 1)   // value-start
                w.writeBits(v ? 1 : 0, 1)
                w.writeBits(0, 1)   // child EE
                st78 = 10
            } else {
                w.writeBits(8, 4)   // element EE
                done78 = true
            }
        case 3:
            if let v = msg.maximumSOC {
                w.writeBits(0, 4)   // MaximumSOC
                w.writeBits(0, 1)   // value-start
                w.writeBits(UInt32(v), 7)
                w.writeBits(0, 1)   // child EE
                st78 = 4
            } else if let v = msg.remainingTimeToMinimumSOC {
                w.writeBits(1, 4)   // RemainingTimeToMinimumSOC
                w.writeBits(0, 1)   // value-start
                ExiPrimitives.writeUnsignedInteger(w, UInt64(v))
                w.writeBits(0, 1)   // child EE
                st78 = 5
            } else if let v = msg.remainingTimeToTargetSOC {
                w.writeBits(2, 4)   // RemainingTimeToTargetSOC
                w.writeBits(0, 1)   // value-start
                ExiPrimitives.writeUnsignedInteger(w, UInt64(v))
                w.writeBits(0, 1)   // child EE
                st78 = 6
            } else if let v = msg.remainingTimeToMaximumSOC {
                w.writeBits(3, 4)   // RemainingTimeToMaximumSOC
                w.writeBits(0, 1)   // value-start
                ExiPrimitives.writeUnsignedInteger(w, UInt64(v))
                w.writeBits(0, 1)   // child EE
                st78 = 7
            } else if let v = msg.chargingComplete {
                w.writeBits(4, 4)   // ChargingComplete
                w.writeBits(0, 1)   // value-start
                w.writeBits(v ? 1 : 0, 1)
                w.writeBits(0, 1)   // child EE
                st78 = 8
            } else if let v = msg.batteryEnergyCapacity {
                w.writeBits(5, 4)   // BatteryEnergyCapacity
                encodeRationalNumberType(w, v)
                st78 = 9
            } else if let v = msg.inletHot {
                w.writeBits(6, 4)   // InletHot
                w.writeBits(0, 1)   // value-start
                w.writeBits(v ? 1 : 0, 1)
                w.writeBits(0, 1)   // child EE
                st78 = 10
            } else {
                w.writeBits(7, 4)   // element EE
                done78 = true
            }
        case 4:
            if let v = msg.remainingTimeToMinimumSOC {
                w.writeBits(0, 3)   // RemainingTimeToMinimumSOC
                w.writeBits(0, 1)   // value-start
                ExiPrimitives.writeUnsignedInteger(w, UInt64(v))
                w.writeBits(0, 1)   // child EE
                st78 = 5
            } else if let v = msg.remainingTimeToTargetSOC {
                w.writeBits(1, 3)   // RemainingTimeToTargetSOC
                w.writeBits(0, 1)   // value-start
                ExiPrimitives.writeUnsignedInteger(w, UInt64(v))
                w.writeBits(0, 1)   // child EE
                st78 = 6
            } else if let v = msg.remainingTimeToMaximumSOC {
                w.writeBits(2, 3)   // RemainingTimeToMaximumSOC
                w.writeBits(0, 1)   // value-start
                ExiPrimitives.writeUnsignedInteger(w, UInt64(v))
                w.writeBits(0, 1)   // child EE
                st78 = 7
            } else if let v = msg.chargingComplete {
                w.writeBits(3, 3)   // ChargingComplete
                w.writeBits(0, 1)   // value-start
                w.writeBits(v ? 1 : 0, 1)
                w.writeBits(0, 1)   // child EE
                st78 = 8
            } else if let v = msg.batteryEnergyCapacity {
                w.writeBits(4, 3)   // BatteryEnergyCapacity
                encodeRationalNumberType(w, v)
                st78 = 9
            } else if let v = msg.inletHot {
                w.writeBits(5, 3)   // InletHot
                w.writeBits(0, 1)   // value-start
                w.writeBits(v ? 1 : 0, 1)
                w.writeBits(0, 1)   // child EE
                st78 = 10
            } else {
                w.writeBits(6, 3)   // element EE
                done78 = true
            }
        case 5:
            if let v = msg.remainingTimeToTargetSOC {
                w.writeBits(0, 3)   // RemainingTimeToTargetSOC
                w.writeBits(0, 1)   // value-start
                ExiPrimitives.writeUnsignedInteger(w, UInt64(v))
                w.writeBits(0, 1)   // child EE
                st78 = 6
            } else if let v = msg.remainingTimeToMaximumSOC {
                w.writeBits(1, 3)   // RemainingTimeToMaximumSOC
                w.writeBits(0, 1)   // value-start
                ExiPrimitives.writeUnsignedInteger(w, UInt64(v))
                w.writeBits(0, 1)   // child EE
                st78 = 7
            } else if let v = msg.chargingComplete {
                w.writeBits(2, 3)   // ChargingComplete
                w.writeBits(0, 1)   // value-start
                w.writeBits(v ? 1 : 0, 1)
                w.writeBits(0, 1)   // child EE
                st78 = 8
            } else if let v = msg.batteryEnergyCapacity {
                w.writeBits(3, 3)   // BatteryEnergyCapacity
                encodeRationalNumberType(w, v)
                st78 = 9
            } else if let v = msg.inletHot {
                w.writeBits(4, 3)   // InletHot
                w.writeBits(0, 1)   // value-start
                w.writeBits(v ? 1 : 0, 1)
                w.writeBits(0, 1)   // child EE
                st78 = 10
            } else {
                w.writeBits(5, 3)   // element EE
                done78 = true
            }
        case 6:
            if let v = msg.remainingTimeToMaximumSOC {
                w.writeBits(0, 3)   // RemainingTimeToMaximumSOC
                w.writeBits(0, 1)   // value-start
                ExiPrimitives.writeUnsignedInteger(w, UInt64(v))
                w.writeBits(0, 1)   // child EE
                st78 = 7
            } else if let v = msg.chargingComplete {
                w.writeBits(1, 3)   // ChargingComplete
                w.writeBits(0, 1)   // value-start
                w.writeBits(v ? 1 : 0, 1)
                w.writeBits(0, 1)   // child EE
                st78 = 8
            } else if let v = msg.batteryEnergyCapacity {
                w.writeBits(2, 3)   // BatteryEnergyCapacity
                encodeRationalNumberType(w, v)
                st78 = 9
            } else if let v = msg.inletHot {
                w.writeBits(3, 3)   // InletHot
                w.writeBits(0, 1)   // value-start
                w.writeBits(v ? 1 : 0, 1)
                w.writeBits(0, 1)   // child EE
                st78 = 10
            } else {
                w.writeBits(4, 3)   // element EE
                done78 = true
            }
        case 7:
            if let v = msg.chargingComplete {
                w.writeBits(0, 3)   // ChargingComplete
                w.writeBits(0, 1)   // value-start
                w.writeBits(v ? 1 : 0, 1)
                w.writeBits(0, 1)   // child EE
                st78 = 8
            } else if let v = msg.batteryEnergyCapacity {
                w.writeBits(1, 3)   // BatteryEnergyCapacity
                encodeRationalNumberType(w, v)
                st78 = 9
            } else if let v = msg.inletHot {
                w.writeBits(2, 3)   // InletHot
                w.writeBits(0, 1)   // value-start
                w.writeBits(v ? 1 : 0, 1)
                w.writeBits(0, 1)   // child EE
                st78 = 10
            } else {
                w.writeBits(3, 3)   // element EE
                done78 = true
            }
        case 8:
            if let v = msg.batteryEnergyCapacity {
                w.writeBits(0, 2)   // BatteryEnergyCapacity
                encodeRationalNumberType(w, v)
                st78 = 9
            } else if let v = msg.inletHot {
                w.writeBits(1, 2)   // InletHot
                w.writeBits(0, 1)   // value-start
                w.writeBits(v ? 1 : 0, 1)
                w.writeBits(0, 1)   // child EE
                st78 = 10
            } else {
                w.writeBits(2, 2)   // element EE
                done78 = true
            }
        case 9:
            if let v = msg.inletHot {
                w.writeBits(0, 2)   // InletHot
                w.writeBits(0, 1)   // value-start
                w.writeBits(v ? 1 : 0, 1)
                w.writeBits(0, 1)   // child EE
                st78 = 10
            } else {
                w.writeBits(1, 2)   // element EE
                done78 = true
            }
        case 10:
            w.writeBits(0, 1)   // element EE
            done78 = true
        default:
            done78 = true
        }
    }
}

internal func decodeDisplayParametersType(_ r: BitReader) throws -> DisplayParametersType {
    var _presentSOC: Int8? = nil
    var _minimumSOC: Int8? = nil
    var _targetSOC: Int8? = nil
    var _maximumSOC: Int8? = nil
    var _remainingTimeToMinimumSOC: UInt32? = nil
    var _remainingTimeToTargetSOC: UInt32? = nil
    var _remainingTimeToMaximumSOC: UInt32? = nil
    var _chargingComplete: Bool? = nil
    var _batteryEnergyCapacity: RationalNumberType? = nil
    var _inletHot: Bool? = nil
    var st79 = 0
    var done79 = false
    while !done79 {
        switch st79 {
        case 0:
            switch try r.readBits(4) {
            case 0:   // PresentSOC
                _ = try r.readBits(1)   // value-start
                _presentSOC = Int8(try r.readBits(7))
                _ = try r.readBits(1)   // child EE
                st79 = 1
            case 1:   // MinimumSOC
                _ = try r.readBits(1)   // value-start
                _minimumSOC = Int8(try r.readBits(7))
                _ = try r.readBits(1)   // child EE
                st79 = 2
            case 2:   // TargetSOC
                _ = try r.readBits(1)   // value-start
                _targetSOC = Int8(try r.readBits(7))
                _ = try r.readBits(1)   // child EE
                st79 = 3
            case 3:   // MaximumSOC
                _ = try r.readBits(1)   // value-start
                _maximumSOC = Int8(try r.readBits(7))
                _ = try r.readBits(1)   // child EE
                st79 = 4
            case 4:   // RemainingTimeToMinimumSOC
                _ = try r.readBits(1)   // value-start
                _remainingTimeToMinimumSOC = UInt32(try ExiPrimitives.readUnsignedInteger(r))
                _ = try r.readBits(1)   // child EE
                st79 = 5
            case 5:   // RemainingTimeToTargetSOC
                _ = try r.readBits(1)   // value-start
                _remainingTimeToTargetSOC = UInt32(try ExiPrimitives.readUnsignedInteger(r))
                _ = try r.readBits(1)   // child EE
                st79 = 6
            case 6:   // RemainingTimeToMaximumSOC
                _ = try r.readBits(1)   // value-start
                _remainingTimeToMaximumSOC = UInt32(try ExiPrimitives.readUnsignedInteger(r))
                _ = try r.readBits(1)   // child EE
                st79 = 7
            case 7:   // ChargingComplete
                _ = try r.readBits(1)   // value-start
                _chargingComplete = try r.readBits(1) != 0
                _ = try r.readBits(1)   // child EE
                st79 = 8
            case 8:   // BatteryEnergyCapacity
                _batteryEnergyCapacity = try decodeRationalNumberType(r)
                st79 = 9
            case 9:   // InletHot
                _ = try r.readBits(1)   // value-start
                _inletHot = try r.readBits(1) != 0
                _ = try r.readBits(1)   // child EE
                st79 = 10
            case 10:   // element EE
                done79 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 1:
            switch try r.readBits(4) {
            case 0:   // MinimumSOC
                _ = try r.readBits(1)   // value-start
                _minimumSOC = Int8(try r.readBits(7))
                _ = try r.readBits(1)   // child EE
                st79 = 2
            case 1:   // TargetSOC
                _ = try r.readBits(1)   // value-start
                _targetSOC = Int8(try r.readBits(7))
                _ = try r.readBits(1)   // child EE
                st79 = 3
            case 2:   // MaximumSOC
                _ = try r.readBits(1)   // value-start
                _maximumSOC = Int8(try r.readBits(7))
                _ = try r.readBits(1)   // child EE
                st79 = 4
            case 3:   // RemainingTimeToMinimumSOC
                _ = try r.readBits(1)   // value-start
                _remainingTimeToMinimumSOC = UInt32(try ExiPrimitives.readUnsignedInteger(r))
                _ = try r.readBits(1)   // child EE
                st79 = 5
            case 4:   // RemainingTimeToTargetSOC
                _ = try r.readBits(1)   // value-start
                _remainingTimeToTargetSOC = UInt32(try ExiPrimitives.readUnsignedInteger(r))
                _ = try r.readBits(1)   // child EE
                st79 = 6
            case 5:   // RemainingTimeToMaximumSOC
                _ = try r.readBits(1)   // value-start
                _remainingTimeToMaximumSOC = UInt32(try ExiPrimitives.readUnsignedInteger(r))
                _ = try r.readBits(1)   // child EE
                st79 = 7
            case 6:   // ChargingComplete
                _ = try r.readBits(1)   // value-start
                _chargingComplete = try r.readBits(1) != 0
                _ = try r.readBits(1)   // child EE
                st79 = 8
            case 7:   // BatteryEnergyCapacity
                _batteryEnergyCapacity = try decodeRationalNumberType(r)
                st79 = 9
            case 8:   // InletHot
                _ = try r.readBits(1)   // value-start
                _inletHot = try r.readBits(1) != 0
                _ = try r.readBits(1)   // child EE
                st79 = 10
            case 9:   // element EE
                done79 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 2:
            switch try r.readBits(4) {
            case 0:   // TargetSOC
                _ = try r.readBits(1)   // value-start
                _targetSOC = Int8(try r.readBits(7))
                _ = try r.readBits(1)   // child EE
                st79 = 3
            case 1:   // MaximumSOC
                _ = try r.readBits(1)   // value-start
                _maximumSOC = Int8(try r.readBits(7))
                _ = try r.readBits(1)   // child EE
                st79 = 4
            case 2:   // RemainingTimeToMinimumSOC
                _ = try r.readBits(1)   // value-start
                _remainingTimeToMinimumSOC = UInt32(try ExiPrimitives.readUnsignedInteger(r))
                _ = try r.readBits(1)   // child EE
                st79 = 5
            case 3:   // RemainingTimeToTargetSOC
                _ = try r.readBits(1)   // value-start
                _remainingTimeToTargetSOC = UInt32(try ExiPrimitives.readUnsignedInteger(r))
                _ = try r.readBits(1)   // child EE
                st79 = 6
            case 4:   // RemainingTimeToMaximumSOC
                _ = try r.readBits(1)   // value-start
                _remainingTimeToMaximumSOC = UInt32(try ExiPrimitives.readUnsignedInteger(r))
                _ = try r.readBits(1)   // child EE
                st79 = 7
            case 5:   // ChargingComplete
                _ = try r.readBits(1)   // value-start
                _chargingComplete = try r.readBits(1) != 0
                _ = try r.readBits(1)   // child EE
                st79 = 8
            case 6:   // BatteryEnergyCapacity
                _batteryEnergyCapacity = try decodeRationalNumberType(r)
                st79 = 9
            case 7:   // InletHot
                _ = try r.readBits(1)   // value-start
                _inletHot = try r.readBits(1) != 0
                _ = try r.readBits(1)   // child EE
                st79 = 10
            case 8:   // element EE
                done79 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 3:
            switch try r.readBits(4) {
            case 0:   // MaximumSOC
                _ = try r.readBits(1)   // value-start
                _maximumSOC = Int8(try r.readBits(7))
                _ = try r.readBits(1)   // child EE
                st79 = 4
            case 1:   // RemainingTimeToMinimumSOC
                _ = try r.readBits(1)   // value-start
                _remainingTimeToMinimumSOC = UInt32(try ExiPrimitives.readUnsignedInteger(r))
                _ = try r.readBits(1)   // child EE
                st79 = 5
            case 2:   // RemainingTimeToTargetSOC
                _ = try r.readBits(1)   // value-start
                _remainingTimeToTargetSOC = UInt32(try ExiPrimitives.readUnsignedInteger(r))
                _ = try r.readBits(1)   // child EE
                st79 = 6
            case 3:   // RemainingTimeToMaximumSOC
                _ = try r.readBits(1)   // value-start
                _remainingTimeToMaximumSOC = UInt32(try ExiPrimitives.readUnsignedInteger(r))
                _ = try r.readBits(1)   // child EE
                st79 = 7
            case 4:   // ChargingComplete
                _ = try r.readBits(1)   // value-start
                _chargingComplete = try r.readBits(1) != 0
                _ = try r.readBits(1)   // child EE
                st79 = 8
            case 5:   // BatteryEnergyCapacity
                _batteryEnergyCapacity = try decodeRationalNumberType(r)
                st79 = 9
            case 6:   // InletHot
                _ = try r.readBits(1)   // value-start
                _inletHot = try r.readBits(1) != 0
                _ = try r.readBits(1)   // child EE
                st79 = 10
            case 7:   // element EE
                done79 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 4:
            switch try r.readBits(3) {
            case 0:   // RemainingTimeToMinimumSOC
                _ = try r.readBits(1)   // value-start
                _remainingTimeToMinimumSOC = UInt32(try ExiPrimitives.readUnsignedInteger(r))
                _ = try r.readBits(1)   // child EE
                st79 = 5
            case 1:   // RemainingTimeToTargetSOC
                _ = try r.readBits(1)   // value-start
                _remainingTimeToTargetSOC = UInt32(try ExiPrimitives.readUnsignedInteger(r))
                _ = try r.readBits(1)   // child EE
                st79 = 6
            case 2:   // RemainingTimeToMaximumSOC
                _ = try r.readBits(1)   // value-start
                _remainingTimeToMaximumSOC = UInt32(try ExiPrimitives.readUnsignedInteger(r))
                _ = try r.readBits(1)   // child EE
                st79 = 7
            case 3:   // ChargingComplete
                _ = try r.readBits(1)   // value-start
                _chargingComplete = try r.readBits(1) != 0
                _ = try r.readBits(1)   // child EE
                st79 = 8
            case 4:   // BatteryEnergyCapacity
                _batteryEnergyCapacity = try decodeRationalNumberType(r)
                st79 = 9
            case 5:   // InletHot
                _ = try r.readBits(1)   // value-start
                _inletHot = try r.readBits(1) != 0
                _ = try r.readBits(1)   // child EE
                st79 = 10
            case 6:   // element EE
                done79 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 5:
            switch try r.readBits(3) {
            case 0:   // RemainingTimeToTargetSOC
                _ = try r.readBits(1)   // value-start
                _remainingTimeToTargetSOC = UInt32(try ExiPrimitives.readUnsignedInteger(r))
                _ = try r.readBits(1)   // child EE
                st79 = 6
            case 1:   // RemainingTimeToMaximumSOC
                _ = try r.readBits(1)   // value-start
                _remainingTimeToMaximumSOC = UInt32(try ExiPrimitives.readUnsignedInteger(r))
                _ = try r.readBits(1)   // child EE
                st79 = 7
            case 2:   // ChargingComplete
                _ = try r.readBits(1)   // value-start
                _chargingComplete = try r.readBits(1) != 0
                _ = try r.readBits(1)   // child EE
                st79 = 8
            case 3:   // BatteryEnergyCapacity
                _batteryEnergyCapacity = try decodeRationalNumberType(r)
                st79 = 9
            case 4:   // InletHot
                _ = try r.readBits(1)   // value-start
                _inletHot = try r.readBits(1) != 0
                _ = try r.readBits(1)   // child EE
                st79 = 10
            case 5:   // element EE
                done79 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 6:
            switch try r.readBits(3) {
            case 0:   // RemainingTimeToMaximumSOC
                _ = try r.readBits(1)   // value-start
                _remainingTimeToMaximumSOC = UInt32(try ExiPrimitives.readUnsignedInteger(r))
                _ = try r.readBits(1)   // child EE
                st79 = 7
            case 1:   // ChargingComplete
                _ = try r.readBits(1)   // value-start
                _chargingComplete = try r.readBits(1) != 0
                _ = try r.readBits(1)   // child EE
                st79 = 8
            case 2:   // BatteryEnergyCapacity
                _batteryEnergyCapacity = try decodeRationalNumberType(r)
                st79 = 9
            case 3:   // InletHot
                _ = try r.readBits(1)   // value-start
                _inletHot = try r.readBits(1) != 0
                _ = try r.readBits(1)   // child EE
                st79 = 10
            case 4:   // element EE
                done79 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 7:
            switch try r.readBits(3) {
            case 0:   // ChargingComplete
                _ = try r.readBits(1)   // value-start
                _chargingComplete = try r.readBits(1) != 0
                _ = try r.readBits(1)   // child EE
                st79 = 8
            case 1:   // BatteryEnergyCapacity
                _batteryEnergyCapacity = try decodeRationalNumberType(r)
                st79 = 9
            case 2:   // InletHot
                _ = try r.readBits(1)   // value-start
                _inletHot = try r.readBits(1) != 0
                _ = try r.readBits(1)   // child EE
                st79 = 10
            case 3:   // element EE
                done79 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 8:
            switch try r.readBits(2) {
            case 0:   // BatteryEnergyCapacity
                _batteryEnergyCapacity = try decodeRationalNumberType(r)
                st79 = 9
            case 1:   // InletHot
                _ = try r.readBits(1)   // value-start
                _inletHot = try r.readBits(1) != 0
                _ = try r.readBits(1)   // child EE
                st79 = 10
            case 2:   // element EE
                done79 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 9:
            switch try r.readBits(2) {
            case 0:   // InletHot
                _ = try r.readBits(1)   // value-start
                _inletHot = try r.readBits(1) != 0
                _ = try r.readBits(1)   // child EE
                st79 = 10
            case 1:   // element EE
                done79 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        case 10:
            switch try r.readBits(1) {
            case 0:   // element EE
                done79 = true
            default:
                throw ExiError.invalidEventCode("optional run")
            }
        default:
            done79 = true
        }
    }
    return DisplayParametersType(presentSOC: _presentSOC, minimumSOC: _minimumSOC, targetSOC: _targetSOC, maximumSOC: _maximumSOC, remainingTimeToMinimumSOC: _remainingTimeToMinimumSOC, remainingTimeToTargetSOC: _remainingTimeToTargetSOC, remainingTimeToMaximumSOC: _remainingTimeToMaximumSOC, chargingComplete: _chargingComplete, batteryEnergyCapacity: _batteryEnergyCapacity, inletHot: _inletHot)
}
