package cloud.charging.v2g.metering

import java.security.PublicKey
import java.security.Signature

/**
 * Verifying a station's meter-signed reading — the vehicle's half of `SigMeterReading` (-2) and
 * `MeterSignature` (-20).
 *
 * ## What this is for
 *
 * Those are standard fields, `maxLength 64`, which is exactly one raw ECDSA P-256 `r‖s` pair. They
 * exist so the **meter** — not the SECC, not the CPO backend — can sign what it measured and hand it
 * to the vehicle, and they are almost never populated in the field. It is the first leg of the
 * three-way comparison in `docs/CONCEPT.md` §4.3: the EV's own model against the *meter-signed*
 * reading against OCPP MeterValues.
 *
 * ## The payload is a convention, not a standard
 *
 * ISO 15118 defines the field and says nothing about what the signature covers, so the layout below
 * is this project's own (the C# `MeterSigningPayload` is the reference). A conforming peer would
 * have to be told it. That is also why [MeterSignatureTest] checks against a corpus generated by the
 * C# side rather than against this implementation's own output: three ports of one layout, each
 * tested against itself, agree perfectly and can be wrong together.
 *
 * ```
 * "V2G-METER-1\0"      12 bytes, domain separator
 * protocol              1 byte   2 or 20
 * sessionId             8 bytes
 * meterIdLength         1 byte
 * meterId               n bytes  UTF-8
 * reading               8 bytes  big-endian, Wh
 * timestamp             8 bytes  big-endian, unix seconds; 0 when absent
 * ```
 *
 * The domain separator stops a signature over the same numbers elsewhere being replayed in as a
 * meter reading; the session id makes a reading provably *yours* rather than merely genuine; and the
 * length prefix stops meter `"A1"` reading 23 and meter `"A"` reading 123 producing the same octets.
 */
object MeterSignature {

    /** The wire length of the signature field: r and s, 32 bytes each. */
    const val SIGNATURE_LENGTH = 64

    /**
     * The JCA name producing the raw `r‖s` form ISO 15118 puts on the wire, rather than the ASN.1/DER
     * the plain name yields. The same trap as everywhere else in this project — and here the DER form
     * would not even fit the 64-byte field, so for once it fails loudly.
     */
    private const val JCA_P1363 = "SHA256withECDSAinP1363Format"

    /**
     * Builds the octets the signature covers.
     *
     * Public rather than private because it is the thing to compare when a signature does not verify:
     * agreeing on the crypto and disagreeing on the payload is the failure mode, and a boolean cannot
     * show it.
     */
    fun payload(
        protocol: Int,
        sessionId: ByteArray,
        meterId: String,
        reading: ULong,
        timestamp: Long?,
    ): ByteArray {
        require(protocol == 2 || protocol == 20) { "protocol must be 2 or 20, was $protocol" }

        val id = meterId.toByteArray(Charsets.UTF_8)
        require(id.size <= 255) { "meter id is ${id.size} bytes; the layout allows 255" }

        val out = ByteArray(12 + 1 + sessionId.size + 1 + id.size + 16)
        var at = 0

        "V2G-METER-1".toByteArray(Charsets.US_ASCII).copyInto(out, at); at += 11
        out[at++] = 0
        out[at++] = protocol.toByte()
        sessionId.copyInto(out, at); at += sessionId.size
        out[at++] = id.size.toByte()
        id.copyInto(out, at); at += id.size
        writeBigEndian(out, at, reading.toLong()); at += 8
        // Absent encodes as zero rather than being omitted, so the payload's length never depends on
        // which optional fields are present.
        writeBigEndian(out, at, timestamp ?: 0L)

        return out
    }

    /**
     * Verifies a reading a station sent. A signature of the wrong length is refused before the
     * crypto sees it.
     */
    fun verify(
        signature: ByteArray,
        protocol: Int,
        sessionId: ByteArray,
        meterId: String,
        reading: ULong,
        timestamp: Long?,
        publicKey: PublicKey,
    ): Boolean {
        if (signature.size != SIGNATURE_LENGTH) return false

        val message = payload(protocol, sessionId, meterId, reading, timestamp)
        return Signature.getInstance(JCA_P1363).apply {
            initVerify(publicKey)
            update(message)
        }.verify(signature)
    }

    private fun writeBigEndian(into: ByteArray, at: Int, value: Long) {
        for (i in 0 until 8) into[at + i] = (value ushr ((7 - i) * 8)).toByte()
    }
}
