// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (TypeScript back end). Do not edit by hand.
// Schema target namespace: cloud.charging.v2g.iso20.ac

import { BitReader, BitWriter, ExiError, exiEnum } from "../runtime/index.ts";
import { AC_CPDResEnergyTransferMode } from "./AC_CPDResEnergyTransferMode.ts";
import { AC_CPDResEnergyTransferModeType, encodeAC_CPDResEnergyTransferModeType, decodeAC_CPDResEnergyTransferModeType } from "./AC_CPDResEnergyTransferModeType.ts";
import { BPT_AC_CPDResEnergyTransferModeType, encodeBPT_AC_CPDResEnergyTransferModeType, decodeBPT_AC_CPDResEnergyTransferModeType } from "./BPT_AC_CPDResEnergyTransferModeType.ts";
import { ChargeParameterDiscoveryResType } from "./ChargeParameterDiscoveryResType.ts";
import { MessageHeaderType, encodeMessageHeaderType, decodeMessageHeaderType } from "./MessageHeaderType.ts";
import { ResponseCode, ResponseCodeNames } from "./ResponseCode.ts";

export class AC_ChargeParameterDiscoveryResType extends ChargeParameterDiscoveryResType {
    readonly aC_CPDResEnergyTransferMode: AC_CPDResEnergyTransferModeType;

    constructor(header: MessageHeaderType, responseCode: ResponseCode, aC_CPDResEnergyTransferMode: AC_CPDResEnergyTransferModeType) {
        super(header, responseCode);
        this.aC_CPDResEnergyTransferMode = aC_CPDResEnergyTransferMode;
    }
}

export function encodeAC_ChargeParameterDiscoveryResType(w: BitWriter, msg: AC_ChargeParameterDiscoveryResType): void {
    w.writeBits(0, 1)   // SE
    encodeMessageHeaderType(w, msg.header)
    w.writeBits(0, 1)   // SE
    w.writeBits(0, 1)   // value-start
    w.writeBits(msg.responseCode, 6)
    w.writeBits(0, 1)   // child EE
    { const v = msg.aC_CPDResEnergyTransferMode; if (false) {}   // dispatch
        else if (v instanceof BPT_AC_CPDResEnergyTransferModeType) {
            w.writeBits(1, 2)   // BPT_AC_CPDResEnergyTransferMode
            encodeBPT_AC_CPDResEnergyTransferModeType(w, v)
        }
        else {
            if (v.constructor !== AC_CPDResEnergyTransferModeType) throw new TypeError(`AC_CPDResEnergyTransferMode: ${v.constructor.name} is not a substitution member`);
            w.writeBits(0, 2)   // AC_CPDResEnergyTransferMode
            encodeAC_CPDResEnergyTransferModeType(w, v)
        }
    }
    w.writeBits(0, 1)   // element EE
}

export function decodeAC_ChargeParameterDiscoveryResType(r: BitReader): AC_ChargeParameterDiscoveryResType {
    r.readBits(1)   // SE
    const _header = decodeMessageHeaderType(r)
    r.readBits(1)   // SE
    r.readBits(1)   // value-start
    const _responseCode = exiEnum("ResponseCode", ResponseCodeNames, r.readBits(6)) as ResponseCode
    r.readBits(1)   // child EE
    let _aC_CPDResEnergyTransferMode!: AC_CPDResEnergyTransferModeType;
    { const _c1 = r.readBits(2); if (false) {}   // dispatch
        else if (_c1 === 0) _aC_CPDResEnergyTransferMode = decodeAC_CPDResEnergyTransferModeType(r);
        else if (_c1 === 1) _aC_CPDResEnergyTransferMode = decodeBPT_AC_CPDResEnergyTransferModeType(r);
        else throw ExiError.invalidEventCode("substitution index");
    }
    r.readBits(1)   // element EE
    return new AC_ChargeParameterDiscoveryResType(_header, _responseCode, _aC_CPDResEnergyTransferMode);
}
