// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (TypeScript back end). Do not edit by hand.
// Schema target namespace: cloud.charging.v2g.iso20.ac

import type { JsonObject, JsonValue } from "../runtime/index.ts";
import { JsonPrimitives } from "../runtime/index.ts";
import { RationalNumberType } from "./RationalNumberType.ts";
import { Scheduled_AC_CLResControlModeType } from "./Scheduled_AC_CLResControlModeType.ts";
import { ACCodecJson } from "./ACCodecJson.Json.ts";

export function toJSONScheduled_AC_CLResControlModeType(value: Scheduled_AC_CLResControlModeType): JsonObject {

    const json: JsonObject = {};

    json["@type"] = "Scheduled_AC_CLResControlModeType";

    if (value.eVSETargetActivePower !== null) {
        json["evseTargetActivePower"] = ACCodecJson.toJSON(value.eVSETargetActivePower);
    }

    if (value.eVSETargetActivePower_L2 !== null) {
        json["evseTargetActivePower_L2"] = ACCodecJson.toJSON(value.eVSETargetActivePower_L2);
    }

    if (value.eVSETargetActivePower_L3 !== null) {
        json["evseTargetActivePower_L3"] = ACCodecJson.toJSON(value.eVSETargetActivePower_L3);
    }

    if (value.eVSETargetReactivePower !== null) {
        json["evseTargetReactivePower"] = ACCodecJson.toJSON(value.eVSETargetReactivePower);
    }

    if (value.eVSETargetReactivePower_L2 !== null) {
        json["evseTargetReactivePower_L2"] = ACCodecJson.toJSON(value.eVSETargetReactivePower_L2);
    }

    if (value.eVSETargetReactivePower_L3 !== null) {
        json["evseTargetReactivePower_L3"] = ACCodecJson.toJSON(value.eVSETargetReactivePower_L3);
    }

    if (value.eVSEPresentActivePower !== null) {
        json["evsePresentActivePower"] = ACCodecJson.toJSON(value.eVSEPresentActivePower);
    }

    if (value.eVSEPresentActivePower_L2 !== null) {
        json["evsePresentActivePower_L2"] = ACCodecJson.toJSON(value.eVSEPresentActivePower_L2);
    }

    if (value.eVSEPresentActivePower_L3 !== null) {
        json["evsePresentActivePower_L3"] = ACCodecJson.toJSON(value.eVSEPresentActivePower_L3);
    }

    return json;
}

export function parseJSONScheduled_AC_CLResControlModeType(json: JsonObject): Scheduled_AC_CLResControlModeType {
    return new Scheduled_AC_CLResControlModeType(
        ((n) => n === null ? null : JsonPrimitives.cast(ACCodecJson.parseJSON(n, "Scheduled_AC_CLResControlModeType.evseTargetActivePower"), RationalNumberType, "evseTargetActivePower", "Scheduled_AC_CLResControlModeType"))(JsonPrimitives.optional(json, "evseTargetActivePower")),
        ((n) => n === null ? null : JsonPrimitives.cast(ACCodecJson.parseJSON(n, "Scheduled_AC_CLResControlModeType.evseTargetActivePower_L2"), RationalNumberType, "evseTargetActivePower_L2", "Scheduled_AC_CLResControlModeType"))(JsonPrimitives.optional(json, "evseTargetActivePower_L2")),
        ((n) => n === null ? null : JsonPrimitives.cast(ACCodecJson.parseJSON(n, "Scheduled_AC_CLResControlModeType.evseTargetActivePower_L3"), RationalNumberType, "evseTargetActivePower_L3", "Scheduled_AC_CLResControlModeType"))(JsonPrimitives.optional(json, "evseTargetActivePower_L3")),
        ((n) => n === null ? null : JsonPrimitives.cast(ACCodecJson.parseJSON(n, "Scheduled_AC_CLResControlModeType.evseTargetReactivePower"), RationalNumberType, "evseTargetReactivePower", "Scheduled_AC_CLResControlModeType"))(JsonPrimitives.optional(json, "evseTargetReactivePower")),
        ((n) => n === null ? null : JsonPrimitives.cast(ACCodecJson.parseJSON(n, "Scheduled_AC_CLResControlModeType.evseTargetReactivePower_L2"), RationalNumberType, "evseTargetReactivePower_L2", "Scheduled_AC_CLResControlModeType"))(JsonPrimitives.optional(json, "evseTargetReactivePower_L2")),
        ((n) => n === null ? null : JsonPrimitives.cast(ACCodecJson.parseJSON(n, "Scheduled_AC_CLResControlModeType.evseTargetReactivePower_L3"), RationalNumberType, "evseTargetReactivePower_L3", "Scheduled_AC_CLResControlModeType"))(JsonPrimitives.optional(json, "evseTargetReactivePower_L3")),
        ((n) => n === null ? null : JsonPrimitives.cast(ACCodecJson.parseJSON(n, "Scheduled_AC_CLResControlModeType.evsePresentActivePower"), RationalNumberType, "evsePresentActivePower", "Scheduled_AC_CLResControlModeType"))(JsonPrimitives.optional(json, "evsePresentActivePower")),
        ((n) => n === null ? null : JsonPrimitives.cast(ACCodecJson.parseJSON(n, "Scheduled_AC_CLResControlModeType.evsePresentActivePower_L2"), RationalNumberType, "evsePresentActivePower_L2", "Scheduled_AC_CLResControlModeType"))(JsonPrimitives.optional(json, "evsePresentActivePower_L2")),
        ((n) => n === null ? null : JsonPrimitives.cast(ACCodecJson.parseJSON(n, "Scheduled_AC_CLResControlModeType.evsePresentActivePower_L3"), RationalNumberType, "evsePresentActivePower_L3", "Scheduled_AC_CLResControlModeType"))(JsonPrimitives.optional(json, "evsePresentActivePower_L3"))
    );
}

