// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Kotlin back end). Do not edit by hand.

package cloud.charging.v2g.iso20.wpt

/** Opaque placeholder for the un-modelled XMLDSig element `Object`.
 *  Only ever encoded/decoded as absent; a present instance fails loud. */
class Object
