// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Kotlin back end). Do not edit by hand.

package cloud.charging.v2g.iso20.wpt

enum class WPT_PairingMethod {
    External_confirmation,
    LPE,
    LF_TxEV,
    LF_TxPrimaryDevice,
    Optical,
    Proprietary
}
