// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Kotlin back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cloud.charging.v2g.iso20.wpt

import cloud.charging.v2g.exi.JsonArray
import cloud.charging.v2g.exi.JsonLdException
import cloud.charging.v2g.exi.JsonObject
import cloud.charging.v2g.exi.JsonPrimitives
import cloud.charging.v2g.exi.JsonValue

internal fun toJsonWPT_TxRxSpecDataType(value: WPT_TxRxSpecDataType): JsonObject {

    val json = JsonObject()

    json["@type"] = JsonValue.of("WPT_TxRxSpecDataType")

    json["txRxIdentifier"] = JsonValue.of(value.txRxIdentifier)
    json["txRxPosition"] = WPTCodecJson.toJson(value.txRxPosition)
    json["txRxOrientation"] = WPTCodecJson.toJson(value.txRxOrientation)
    return json
}

internal fun parseJsonWPT_TxRxSpecDataType(json: JsonObject): WPT_TxRxSpecDataType =
    WPT_TxRxSpecDataType(
        JsonPrimitives.uint32(JsonPrimitives.required(json, "txRxIdentifier", "WPT_TxRxSpecDataType"), "txRxIdentifier", "WPT_TxRxSpecDataType"),
        JsonPrimitives.cast<WPT_CoordinateXYZType>(WPTCodecJson.parseJson(JsonPrimitives.required(json, "txRxPosition", "WPT_TxRxSpecDataType"), "WPT_TxRxSpecDataType.txRxPosition"), "txRxPosition", "WPT_TxRxSpecDataType"),
        JsonPrimitives.cast<WPT_CoordinateXYZType>(WPTCodecJson.parseJson(JsonPrimitives.required(json, "txRxOrientation", "WPT_TxRxSpecDataType"), "WPT_TxRxSpecDataType.txRxOrientation"), "txRxOrientation", "WPT_TxRxSpecDataType")
    )

