// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Kotlin back end). Do not edit by hand.
//
// Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
// This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
//
// Licensed under the Affero GPL license, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.gnu.org/licenses/agpl.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cloud.charging.v2g.iso20.wpt

import cloud.charging.v2g.exi.JsonArray
import cloud.charging.v2g.exi.JsonLdException
import cloud.charging.v2g.exi.JsonObject
import cloud.charging.v2g.exi.JsonPrimitives
import cloud.charging.v2g.exi.JsonValue

internal fun toJsonWPT_TxRxPulseOrderType(value: WPT_TxRxPulseOrderType): JsonObject {

    val json = JsonObject()

    json["@type"] = JsonValue.of("WPT_TxRxPulseOrderType")

    json["indexNumber"] = JsonValue.of(value.indexNumber)
    json["txRxIdentifier"] = JsonValue.of(value.txRxIdentifier)
    return json
}

internal fun parseJsonWPT_TxRxPulseOrderType(json: JsonObject): WPT_TxRxPulseOrderType =
    WPT_TxRxPulseOrderType(
        JsonPrimitives.uint16(JsonPrimitives.required(json, "indexNumber", "WPT_TxRxPulseOrderType"), "indexNumber", "WPT_TxRxPulseOrderType"),
        JsonPrimitives.uint32(JsonPrimitives.required(json, "txRxIdentifier", "WPT_TxRxPulseOrderType"), "txRxIdentifier", "WPT_TxRxPulseOrderType")
    )

