// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Kotlin back end). Do not edit by hand.

package cloud.charging.v2g.iso20.wpt

import cloud.charging.v2g.exi.JsonArray
import cloud.charging.v2g.exi.JsonLdException
import cloud.charging.v2g.exi.JsonObject
import cloud.charging.v2g.exi.JsonPrimitives
import cloud.charging.v2g.exi.JsonValue

internal fun toJsonWPT_ChargeLoopReqType(value: WPT_ChargeLoopReqType): JsonObject {

    val json = JsonObject()

    json["@type"] = JsonValue.of("WPT_ChargeLoopReqType")

    json["header"] = WPTCodecJson.toJson(value.header)
    value.displayParameters?.let { json["displayParameters"] = WPTCodecJson.toJson(it) }

    json["meterInfoRequested"] = JsonValue.of(value.meterInfoRequested)
    json["evpcPowerRequest"] = WPTCodecJson.toJson(value.eVPCPowerRequest)
    json["evpcPowerOutput"] = WPTCodecJson.toJson(value.eVPCPowerOutput)
    json["evpcChargeDiagnostics"] = JsonValue.of(value.eVPCChargeDiagnostics.name)
    value.eVPCOperatingFrequency?.let { json["evpcOperatingFrequency"] = WPTCodecJson.toJson(it) }

    value.eVPCPowerControlParameter?.let { json["evpcPowerControlParameter"] = WPTCodecJson.toJson(it) }

    val _manufacturerSpecificDataContainer = JsonArray()
    for (item in value.manufacturerSpecificDataContainer)
        _manufacturerSpecificDataContainer.add(JsonValue.of(JsonPrimitives.toHex(item)))
    json["manufacturerSpecificDataContainer"] = _manufacturerSpecificDataContainer

    return json
}

internal fun parseJsonWPT_ChargeLoopReqType(json: JsonObject): WPT_ChargeLoopReqType =
    WPT_ChargeLoopReqType(
        JsonPrimitives.cast<MessageHeaderType>(WPTCodecJson.parseJson(JsonPrimitives.required(json, "header", "WPT_ChargeLoopReqType"), "WPT_ChargeLoopReqType.header"), "header", "WPT_ChargeLoopReqType"),
        JsonPrimitives.optional(json, "displayParameters")?.let { JsonPrimitives.cast<DisplayParametersType>(WPTCodecJson.parseJson(it, "WPT_ChargeLoopReqType.displayParameters"), "displayParameters", "WPT_ChargeLoopReqType") },
        JsonPrimitives.bool(JsonPrimitives.required(json, "meterInfoRequested", "WPT_ChargeLoopReqType"), "meterInfoRequested", "WPT_ChargeLoopReqType"),
        JsonPrimitives.cast<RationalNumberType>(WPTCodecJson.parseJson(JsonPrimitives.required(json, "evpcPowerRequest", "WPT_ChargeLoopReqType"), "WPT_ChargeLoopReqType.evpcPowerRequest"), "evpcPowerRequest", "WPT_ChargeLoopReqType"),
        JsonPrimitives.cast<RationalNumberType>(WPTCodecJson.parseJson(JsonPrimitives.required(json, "evpcPowerOutput", "WPT_ChargeLoopReqType"), "WPT_ChargeLoopReqType.evpcPowerOutput"), "evpcPowerOutput", "WPT_ChargeLoopReqType"),
        JsonPrimitives.enumeration(JsonPrimitives.required(json, "evpcChargeDiagnostics", "WPT_ChargeLoopReqType"), "evpcChargeDiagnostics", "WPT_ChargeLoopReqType", WPT_EVPCChargeDiagnostics.values()),
        JsonPrimitives.optional(json, "evpcOperatingFrequency")?.let { JsonPrimitives.cast<RationalNumberType>(WPTCodecJson.parseJson(it, "WPT_ChargeLoopReqType.evpcOperatingFrequency"), "evpcOperatingFrequency", "WPT_ChargeLoopReqType") },
        JsonPrimitives.optional(json, "evpcPowerControlParameter")?.let { JsonPrimitives.cast<WPT_EVPCPowerControlParameterType>(WPTCodecJson.parseJson(it, "WPT_ChargeLoopReqType.evpcPowerControlParameter"), "evpcPowerControlParameter", "WPT_ChargeLoopReqType") },
        (JsonPrimitives.optional(json, "manufacturerSpecificDataContainer") as? JsonArray)?.asList()?.map { JsonPrimitives.binary(it, "manufacturerSpecificDataContainer", "WPT_ChargeLoopReqType") } ?: emptyList()
    )

