// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Kotlin back end). Do not edit by hand.

package cloud.charging.v2g.iso20.dc

import cloud.charging.v2g.exi.JsonArray
import cloud.charging.v2g.exi.JsonLdException
import cloud.charging.v2g.exi.JsonObject
import cloud.charging.v2g.exi.JsonPrimitives
import cloud.charging.v2g.exi.JsonValue

internal fun toJsonBPT_Dynamic_DC_CLResControlModeType(value: BPT_Dynamic_DC_CLResControlModeType): JsonObject {

    val json = JsonObject()

    json["@type"] = JsonValue.of("BPT_Dynamic_DC_CLResControlModeType")

    value.departureTime?.let { json["departureTime"] = JsonValue.of(it) }

    value.minimumSOC?.let { json["minimumSOC"] = JsonValue.of(it) }

    value.targetSOC?.let { json["targetSOC"] = JsonValue.of(it) }

    value.ackMaxDelay?.let { json["ackMaxDelay"] = JsonValue.of(it) }

    json["evseMaximumChargePower"] = DCCodecJson.toJson(value.eVSEMaximumChargePower)
    json["evseMinimumChargePower"] = DCCodecJson.toJson(value.eVSEMinimumChargePower)
    json["evseMaximumChargeCurrent"] = DCCodecJson.toJson(value.eVSEMaximumChargeCurrent)
    json["evseMaximumVoltage"] = DCCodecJson.toJson(value.eVSEMaximumVoltage)
    json["evseMaximumDischargePower"] = DCCodecJson.toJson(value.eVSEMaximumDischargePower)
    json["evseMinimumDischargePower"] = DCCodecJson.toJson(value.eVSEMinimumDischargePower)
    json["evseMaximumDischargeCurrent"] = DCCodecJson.toJson(value.eVSEMaximumDischargeCurrent)
    json["evseMinimumVoltage"] = DCCodecJson.toJson(value.eVSEMinimumVoltage)
    return json
}

internal fun parseJsonBPT_Dynamic_DC_CLResControlModeType(json: JsonObject): BPT_Dynamic_DC_CLResControlModeType =
    BPT_Dynamic_DC_CLResControlModeType(
        JsonPrimitives.optional(json, "departureTime")?.let { JsonPrimitives.uint32(it, "departureTime", "BPT_Dynamic_DC_CLResControlModeType") },
        JsonPrimitives.optional(json, "minimumSOC")?.let { JsonPrimitives.int8(it, "minimumSOC", "BPT_Dynamic_DC_CLResControlModeType") },
        JsonPrimitives.optional(json, "targetSOC")?.let { JsonPrimitives.int8(it, "targetSOC", "BPT_Dynamic_DC_CLResControlModeType") },
        JsonPrimitives.optional(json, "ackMaxDelay")?.let { JsonPrimitives.uint16(it, "ackMaxDelay", "BPT_Dynamic_DC_CLResControlModeType") },
        JsonPrimitives.cast<RationalNumberType>(DCCodecJson.parseJson(JsonPrimitives.required(json, "evseMaximumChargePower", "BPT_Dynamic_DC_CLResControlModeType"), "BPT_Dynamic_DC_CLResControlModeType.evseMaximumChargePower"), "evseMaximumChargePower", "BPT_Dynamic_DC_CLResControlModeType"),
        JsonPrimitives.cast<RationalNumberType>(DCCodecJson.parseJson(JsonPrimitives.required(json, "evseMinimumChargePower", "BPT_Dynamic_DC_CLResControlModeType"), "BPT_Dynamic_DC_CLResControlModeType.evseMinimumChargePower"), "evseMinimumChargePower", "BPT_Dynamic_DC_CLResControlModeType"),
        JsonPrimitives.cast<RationalNumberType>(DCCodecJson.parseJson(JsonPrimitives.required(json, "evseMaximumChargeCurrent", "BPT_Dynamic_DC_CLResControlModeType"), "BPT_Dynamic_DC_CLResControlModeType.evseMaximumChargeCurrent"), "evseMaximumChargeCurrent", "BPT_Dynamic_DC_CLResControlModeType"),
        JsonPrimitives.cast<RationalNumberType>(DCCodecJson.parseJson(JsonPrimitives.required(json, "evseMaximumVoltage", "BPT_Dynamic_DC_CLResControlModeType"), "BPT_Dynamic_DC_CLResControlModeType.evseMaximumVoltage"), "evseMaximumVoltage", "BPT_Dynamic_DC_CLResControlModeType"),
        JsonPrimitives.cast<RationalNumberType>(DCCodecJson.parseJson(JsonPrimitives.required(json, "evseMaximumDischargePower", "BPT_Dynamic_DC_CLResControlModeType"), "BPT_Dynamic_DC_CLResControlModeType.evseMaximumDischargePower"), "evseMaximumDischargePower", "BPT_Dynamic_DC_CLResControlModeType"),
        JsonPrimitives.cast<RationalNumberType>(DCCodecJson.parseJson(JsonPrimitives.required(json, "evseMinimumDischargePower", "BPT_Dynamic_DC_CLResControlModeType"), "BPT_Dynamic_DC_CLResControlModeType.evseMinimumDischargePower"), "evseMinimumDischargePower", "BPT_Dynamic_DC_CLResControlModeType"),
        JsonPrimitives.cast<RationalNumberType>(DCCodecJson.parseJson(JsonPrimitives.required(json, "evseMaximumDischargeCurrent", "BPT_Dynamic_DC_CLResControlModeType"), "BPT_Dynamic_DC_CLResControlModeType.evseMaximumDischargeCurrent"), "evseMaximumDischargeCurrent", "BPT_Dynamic_DC_CLResControlModeType"),
        JsonPrimitives.cast<RationalNumberType>(DCCodecJson.parseJson(JsonPrimitives.required(json, "evseMinimumVoltage", "BPT_Dynamic_DC_CLResControlModeType"), "BPT_Dynamic_DC_CLResControlModeType.evseMinimumVoltage"), "evseMinimumVoltage", "BPT_Dynamic_DC_CLResControlModeType")
    )

