// <auto-generated/>
// Generated by WWCP_ISO15118_EXI_SourceGenerator (Kotlin back end). Do not edit by hand.

package cloud.charging.v2g.iso20.dc

import cloud.charging.v2g.exi.JsonArray
import cloud.charging.v2g.exi.JsonLdException
import cloud.charging.v2g.exi.JsonObject
import cloud.charging.v2g.exi.JsonPrimitives
import cloud.charging.v2g.exi.JsonValue

internal fun toJsonDC_CableCheckResType(value: DC_CableCheckResType): JsonObject {

    val json = JsonObject()

    json["@type"] = JsonValue.of("DC_CableCheckResType")

    json["header"] = DCCodecJson.toJson(value.header)
    json["responseCode"] = JsonValue.of(value.responseCode.name)
    json["evseProcessing"] = JsonValue.of(value.eVSEProcessing.name)
    return json
}

internal fun parseJsonDC_CableCheckResType(json: JsonObject): DC_CableCheckResType =
    DC_CableCheckResType(
        JsonPrimitives.cast<MessageHeaderType>(DCCodecJson.parseJson(JsonPrimitives.required(json, "header", "DC_CableCheckResType"), "DC_CableCheckResType.header"), "header", "DC_CableCheckResType"),
        JsonPrimitives.enumeration(JsonPrimitives.required(json, "responseCode", "DC_CableCheckResType"), "responseCode", "DC_CableCheckResType", ResponseCode.values()),
        JsonPrimitives.enumeration(JsonPrimitives.required(json, "evseProcessing", "DC_CableCheckResType"), "evseProcessing", "DC_CableCheckResType", Processing.values())
    )

