// <auto-generated/>
// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Kotlin back end). Do not edit by hand.

package cloud.charging.v2g.iso20.dc

import cloud.charging.v2g.exi.JsonArray
import cloud.charging.v2g.exi.JsonLdException
import cloud.charging.v2g.exi.JsonObject
import cloud.charging.v2g.exi.JsonPrimitives
import cloud.charging.v2g.exi.JsonValue

internal fun toJsonDC_CableCheckReqType(value: DC_CableCheckReqType): JsonObject {

    val json = JsonObject()

    json["@type"] = JsonValue.of("DC_CableCheckReqType")

    json["header"] = DCCodecJson.toJson(value.header)
    return json
}

internal fun parseJsonDC_CableCheckReqType(json: JsonObject): DC_CableCheckReqType =
    DC_CableCheckReqType(
        JsonPrimitives.cast<MessageHeaderType>(DCCodecJson.parseJson(JsonPrimitives.required(json, "header", "DC_CableCheckReqType"), "DC_CableCheckReqType.header"), "header", "DC_CableCheckReqType")
    )

